/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x2BAC10:
        i_parser.PrintString("devdesc", "TPM log buffer init failure.");
        i_parser.PrintString("moduleid", "MOD_TPMLOGMGR_INITIALIZE");
        i_parser.PrintString("reasoncode", "RC_TPMLOGMGR_INIT_FAIL");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BB012:
        i_parser.PrintString("devdesc", "TPM log header entry is missing.");
        i_parser.PrintString("moduleid", "MOD_TPMLOGMGR_INITIALIZEEXISTLOG");
        i_parser.PrintString("reasoncode", "RC_TPMLOGMGR_LOGWALKFAIL");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BAA11:
        i_parser.PrintString("devdesc", "TPM log buffer add failure.");
        i_parser.PrintString("moduleid", "MOD_TPMLOGMGR_ADDEVENT");
        i_parser.PrintString("reasoncode", "RC_TPMLOGMGR_ADDEVENT_FAIL");
        i_parser.PrintString("userdata1[0:31]", "Max log size");
        i_parser.PrintString("userdata1[32:63]", "Log buffer NULL");
        i_parser.PrintString("userdata2[0:31]", "Current Log Size");
        i_parser.PrintString("userdata2[32:63]", "New entry size");
        break;

    case 0x2BAB11:
        i_parser.PrintString("devdesc", "log buffer marshal failure.");
        i_parser.PrintString("moduleid", "MOD_TPMLOGMGR_ADDEVENT");
        i_parser.PrintString("reasoncode", "RC_TPMLOGMGR_ADDEVENTMARSH_FAIL");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BB10D:
        i_parser.PrintString("devdesc", "msg_sendrecv() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_SEPARATOR");
        i_parser.PrintString("reasoncode", "RC_SENDRECV_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_sendrecv()");
        break;

    case 0x2BB20D:
        i_parser.PrintString("devdesc", "msg_send() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_SEPARATOR");
        i_parser.PrintString("reasoncode", "RC_SEND_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_send()");
        break;

    case 0x2BB10A:
        i_parser.PrintString("devdesc", "msg_sendrecv() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_PCREXTEND");
        i_parser.PrintString("reasoncode", "RC_SENDRECV_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_sendrecv()");
        break;

    case 0x2BB20A:
        i_parser.PrintString("devdesc", "msg_send() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_PCREXTEND");
        i_parser.PrintString("reasoncode", "RC_SEND_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_send()");
        break;

    case 0x2BB115:
        i_parser.PrintString("devdesc", "msg_sendrecv() failed");
        i_parser.PrintString("moduleid", "MOD_INIT_BACKUP_TPM");
        i_parser.PrintString("reasoncode", "RC_SENDRECV_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_sendrecv()");
        break;

    case 0x2BB717:
        i_parser.PrintString("devdesc", "TPM testcase error. See the return code for details.");
        i_parser.PrintString("moduleid", "MOD_TEST_CMP_PRIMARY_AND_BACKUP_TPM");
        i_parser.PrintString("reasoncode", "RC_BACKUP_TPM_TEST_FAIL");
        i_parser.PrintString("userdata1", "return code");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BB118:
        i_parser.PrintString("devdesc", "msg_sendrecv() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_GETRANDOM");
        i_parser.PrintString("reasoncode", "RC_SENDRECV_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_sendrecv()");
        i_parser.PrintString("userdata2", "TPM HUID if it's not nullptr");
        break;

    case 0x2BB30C:
        i_parser.PrintString("devdesc", "msg_respond() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_SYNCRESPONSE");
        i_parser.PrintString("reasoncode", "RC_MSGRESPOND_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_respond()");
        break;

    case 0x2BA909:
        i_parser.PrintString("devdesc", "Unmarshal error while replaying tpm log.");
        i_parser.PrintString("moduleid", "MOD_TPM_REPLAY_LOG");
        i_parser.PrintString("reasoncode", "RC_TPM_UNMARSHALING_FAIL");
        i_parser.PrintString("userdata1", "Starting address of event that caused error");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BB414:
        i_parser.PrintString("devdesc", "Failed to set SEEPROM lock and/or TPM deconfig protection for this processor, so we cannot guarrantee platform secuirty for this processor");
        i_parser.PrintString("moduleid", "TRUSTEDBOOT::MOD_TPM_MARK_FAILED");
        i_parser.PrintString("reasoncode", "TRUSTEDBOOT::RC_UPDATE_SECURITY_CTRL_HWP_FAIL");
        i_parser.PrintString("userdata1", "Processor Target");
        i_parser.PrintString("userdata2", "TPM Target");
        break;

    case 0x2BAD06:
        i_parser.PrintString("devdesc", "The system (or node, if multi-node system) is configured in the hardware (via processor secure jumpers) to enable Secure Boot, and the system's/node's TPM required policy is configured to require at least one functional boot processor TPM in order to boot with Trusted Boot enabled. Therefore, the system (or node, if multi-node system) will terminate due to lack of functional boot processor TPM.");
        i_parser.PrintString("moduleid", "MOD_TPM_VERIFYFUNCTIONAL");
        i_parser.PrintString("reasoncode", "RC_TPM_NOFUNCTIONALTPM_FAIL");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BBA0B:
        i_parser.PrintString("devdesc", "Unable to reach the TPM");
        i_parser.PrintString("moduleid", "MOD_TPM_TPMDAEMON");
        i_parser.PrintString("reasoncode", "RC_UNREACHABLE_TPM");
        i_parser.PrintString("userdata1", "TPM HUID or nullptr");
        break;

    case 0x2BB30B:
        i_parser.PrintString("devdesc", "msg_respond() failed");
        i_parser.PrintString("moduleid", "MOD_TPM_TPMDAEMON");
        i_parser.PrintString("reasoncode", "RC_MSGRESPOND_FAIL");
        i_parser.PrintString("userdata1", "rc from msq_respond()");
        break;

    case 0x2BB819:
        i_parser.PrintString("devdesc", "Caller attempted to get a random number from a TPM using an invalid TPM target.");
        i_parser.PrintString("moduleid", "MOD_VALIDATE_TPM_HANDLE");
        i_parser.PrintString("reasoncode", "RC_INVALID_TPM_HANDLE");
        i_parser.PrintString("userdata1", "TPM HUID if it's not nullptr");
        break;

    case 0x2BB919:
        i_parser.PrintString("devdesc", "Call attempted to get a random number from a TPM that was not functional");
        i_parser.PrintString("moduleid", "MOD_VALIDATE_TPM_HANDLE");
        i_parser.PrintString("reasoncode", "RC_NON_FUNCTIONAL_TPM_HANDLE");
        i_parser.PrintString("userdata1", "TPM HUID if it's not nullptr");
        break;

    case 0x2BA604:
        i_parser.PrintString("devdesc", "Unsupported command code during marshal");
        i_parser.PrintString("moduleid", "MOD_TPM_MARSHALCMDDATA");
        i_parser.PrintString("reasoncode", "RC_TPM_MARSHAL_INVALID_CMD");
        i_parser.PrintString("userdata1", "Command Code");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BA704:
        i_parser.PrintString("devdesc", "Marshaling error detected");
        i_parser.PrintString("moduleid", "MOD_TPM_MARSHALCMDDATA");
        i_parser.PrintString("reasoncode", "RC_TPM_MARSHALING_FAIL");
        i_parser.PrintString("userdata1", "stage");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BA805:
        i_parser.PrintString("devdesc", "Unsupported command code during unmarshal");
        i_parser.PrintString("moduleid", "MOD_TPM_UNMARSHALRESPDATA");
        i_parser.PrintString("reasoncode", "RC_TPM_UNMARSHAL_INVALID_CMD");
        i_parser.PrintString("userdata1", "commandcode");
        i_parser.PrintString("userdata2", "stage");
        break;

    case 0x2BA905:
        i_parser.PrintString("devdesc", "Unmarshaling error detected");
        i_parser.PrintString("moduleid", "MOD_TPM_UNMARSHALRESPDATA");
        i_parser.PrintString("reasoncode", "RC_TPM_UNMARSHALING_FAIL");
        i_parser.PrintString("userdata1", "Stage");
        i_parser.PrintString("userdata2", "Remaining response buffer size");
        break;

    case 0x2BA002:
        i_parser.PrintString("devdesc", "TPM_Startup operation failure.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_STARTUP");
        i_parser.PrintString("reasoncode", "RC_TPM_START_FAIL");
        i_parser.PrintString("userdata1", "responseCode");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BA203:
        i_parser.PrintString("devdesc", "Command failure reading TPM FW version.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPFWVERSION");
        i_parser.PrintString("reasoncode", "RC_TPM_GETCAP_FAIL");
        i_parser.PrintString("userdata1", "responseCode");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BA303:
        i_parser.PrintString("devdesc", "Command failure reading TPM FW version.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPFWVERSION");
        i_parser.PrintString("reasoncode", "RC_TPM_GETCAP_FW_INVALID_RESP");
        i_parser.PrintString("userdata1", "capability");
        i_parser.PrintString("userdata2", "property");
        break;

    case 0x2BA403:
        i_parser.PrintString("devdesc", "Command failure reading TPM FW version.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPFWVERSION");
        i_parser.PrintString("reasoncode", "RC_TPM_GETCAP2_FAIL");
        i_parser.PrintString("userdata1", "responseCode");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BA503:
        i_parser.PrintString("devdesc", "Command failure reading TPM FW version.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPFWVERSION");
        i_parser.PrintString("reasoncode", "RC_TPM_GETCAP2_FW_INVALID_RESP");
        i_parser.PrintString("userdata1", "capability");
        i_parser.PrintString("userdata2", "property");
        break;

    case 0x2BA20E:
        i_parser.PrintString("devdesc", "Command failure reading TPM capability.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPNVINDEX");
        i_parser.PrintString("reasoncode", "RC_TPM_GETCAP_FAIL");
        i_parser.PrintString("userdata1", "responseCode");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BA30E:
        i_parser.PrintString("devdesc", "Command failure reading TPM NV indexes.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPNVINDEX");
        i_parser.PrintString("reasoncode", "RC_TPM_GETCAP_FW_INVALID_RESP");
        i_parser.PrintString("userdata1", "capability");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x2BB50E:
        i_parser.PrintString("devdesc", "Command failure reading TPM NV indexes.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_GETCAPNVINDEX");
        i_parser.PrintString("reasoncode", "RC_TPM_NVINDEX_VALIDATE_FAIL");
        i_parser.PrintString("userdata1[0:3]", "foundRSAEKCert");
        i_parser.PrintString("userdata1[4:7]", "foundECCEKCert");
        i_parser.PrintString("userdata1[8:11]", "foundPlatCert");
        i_parser.PrintString("userdata1[12:31]", "0");
        i_parser.PrintString("userdata2[0:3]", "moreData");
        i_parser.PrintString("userdata2[4:31]", "0");
        break;

    case 0x2BAF07:
        i_parser.PrintString("devdesc", "PCR Extend invalid arguments detected");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_PCREXTEND");
        i_parser.PrintString("reasoncode", "RC_TPM_INVALID_ARGS");
        i_parser.PrintString("userdata1", "Digest Ptr");
        i_parser.PrintString("userdata2[0:15]", "Full Digest Size 1");
        i_parser.PrintString("userdata2[16:31]", "Full Digest Size 2");
        i_parser.PrintString("userdata2[32:63]", "PCR");
        break;

    case 0x2BAE07:
        i_parser.PrintString("devdesc", "Command failure performing PCR extend.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_PCREXTEND");
        i_parser.PrintString("reasoncode", "RC_TPM_COMMAND_FAIL");
        i_parser.PrintString("userdata1", "responseCode");
        i_parser.PrintString("userdata2", "dataSize");
        break;

    case 0x2BAF08:
        i_parser.PrintString("devdesc", "pcr read invalid arguments");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_PCRREAD");
        i_parser.PrintString("reasoncode", "RC_TPM_INVALID_ARGS");
        i_parser.PrintString("userdata1", "Digest Ptr");
        i_parser.PrintString("userdata2[0:31]", "Full Digest Size");
        i_parser.PrintString("userdata2[32:63]", "PCR");
        break;

    case 0x2BAE08:
        i_parser.PrintString("devdesc", "Command failure performing PCR read.");
        i_parser.PrintString("moduleid", "MOD_TPM_CMD_PCRREAD");
        i_parser.PrintString("reasoncode", "RC_TPM_COMMAND_FAIL");
        i_parser.PrintString("userdata1", "responseCode");
        i_parser.PrintString("userdata2", "dataSize");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2B00, SrcDataParse, ERRL_CID_HOSTBOOT);
