/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x70F01:
        i_parser.PrintString("devdesc", "I2C offset length is invalid");
        i_parser.PrintString("moduleid", "I2C_PERFORM_OP");
        i_parser.PrintString("reasoncode", "I2C_RUNTIME_INVALID_OFFSET_LENGTH");
        i_parser.PrintString("userdata1", "Offset length");
        i_parser.PrintString("userdata2", "Op type");
        break;

    case 0x70D01:
        i_parser.PrintString("devdesc", "I2C read/write interface not linked.");
        i_parser.PrintString("moduleid", "I2C_PERFORM_OP");
        i_parser.PrintString("reasoncode", "I2C_RUNTIME_INTERFACE_ERR");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "Op type");
        break;

    case 0x70E01:
        i_parser.PrintString("devdesc", "I2C access error");
        i_parser.PrintString("moduleid", "I2C_PERFORM_OP");
        i_parser.PrintString("reasoncode", "I2C_RUNTIME_ERR");
        i_parser.PrintString("userdata1", "Hypervisor return code");
        i_parser.PrintString("userdata2", "Op type");
        break;

    case 0x71201:
        i_parser.PrintString("devdesc", "I2C master encountered an error while trying to unlock the eepromPage");
        i_parser.PrintString("moduleid", "I2C_PERFORM_OP");
        i_parser.PrintString("reasoncode", "I2C_FAILURE_UNLOCKING_EEPROM_PAGE");
        i_parser.PrintString("userdata1", "Target Huid");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x7110E:
        i_parser.PrintString("devdesc", "There was a request for an invalid EEPROM page");
        i_parser.PrintString("moduleid", "I2C_CHOOSE_EEPROM_PAGE");
        i_parser.PrintString("reasoncode", "I2C_INVALID_EEPROM_PAGE_REQUEST");
        i_parser.PrintString("userdata1", "Target Huid");
        i_parser.PrintString("userdata2", "Requested Page");
        break;

    case 0x7070C:
        i_parser.PrintString("devdesc", "Master Sentinel chip was used as a target for an I2C operation.  This is not permitted.");
        i_parser.PrintString("moduleid", "I2C_PAGE_SWITCH_OP");
        i_parser.PrintString("reasoncode", "I2C_MASTER_SENTINEL_TARGET");
        i_parser.PrintString("userdata1", "Operation Type requested");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x7100C:
        i_parser.PrintString("devdesc", "There was an error retrieving the EEPROM page mutex for this i2c master engine");
        i_parser.PrintString("moduleid", "I2C_PAGE_SWITCH_OP");
        i_parser.PrintString("reasoncode", "I2C_INVALID_EEPROM_PAGE_MUTEX");
        i_parser.PrintString("userdata1", "Target Huid");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x70A0C:
        i_parser.PrintString("devdesc", "ATTR_EEPROM_PAGE_ARRAY not found");
        i_parser.PrintString("moduleid", "I2C_PAGE_SWITCH_OP");
        i_parser.PrintString("reasoncode", "I2C_ATTRIBUTE_NOT_FOUND");
        i_parser.PrintString("userdata1", "Target HUID for the attribute");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x7100D:
        i_parser.PrintString("devdesc", "There was an error retrieving the EEPROM page mutex for this i2c master engine");
        i_parser.PrintString("moduleid", "I2C_PAGE_UNLOCK_OP");
        i_parser.PrintString("reasoncode", "I2C_INVALID_EEPROM_PAGE_MUTEX");
        i_parser.PrintString("userdata1", "Target Huid");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x70701:
        i_parser.PrintString("devdesc", "Master Sentinel chip was used as a target for an I2C operation.  This is not permitted.");
        i_parser.PrintString("moduleid", "I2C_PERFORM_OP");
        i_parser.PrintString("reasoncode", "I2C_MASTER_SENTINEL_TARGET");
        i_parser.PrintString("userdata1", "Operation Type requested");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x70201:
        i_parser.PrintString("devdesc", "Invalid operation type.");
        i_parser.PrintString("moduleid", "I2C_PERFORM_OP");
        i_parser.PrintString("reasoncode", "I2C_INVALID_OP_TYPE");
        i_parser.PrintString("userdata1", "i_opType");
        i_parser.PrintString("userdata2[0:15]", "Offset Length");
        i_parser.PrintString("userdata2[16:31]", "Master Port");
        i_parser.PrintString("userdata2[32:47]", "Master Engine");
        i_parser.PrintString("userdata2[48:63]", "Slave Device Address");
        break;

    case 0x70302:
        i_parser.PrintString("devdesc", "Timed out waiting for data in FIFO to read");
        i_parser.PrintString("moduleid", "I2C_READ");
        i_parser.PrintString("reasoncode", "I2C_FIFO_TIMEOUT");
        i_parser.PrintString("userdata1[0:31]", "Status Register Value");
        i_parser.PrintString("userdata1[32:63]", "Master Target");
        i_parser.PrintString("userdata2[0:7]", "Master Engine");
        i_parser.PrintString("userdata2[8:15]", "Master Port");
        i_parser.PrintString("userdata2[16:31]", "Slave Device Address");
        i_parser.PrintString("userdata2[32:47]", "Bus Speed");
        i_parser.PrintString("userdata2[48:63]", "Bit Rate Devisor");
        break;

    case 0x70505:
        i_parser.PrintString("devdesc", "Timed out waiting for command complete.");
        i_parser.PrintString("moduleid", "I2C_WAIT_FOR_CMD_COMP");
        i_parser.PrintString("reasoncode", "I2C_CMD_COMP_TIMEOUT");
        i_parser.PrintString("userdata1[0:31]", "Status Register Value");
        i_parser.PrintString("userdata1[32:63]", "Master Target");
        i_parser.PrintString("userdata2[0:7]", "Master Engine");
        i_parser.PrintString("userdata2[8:15]", "Master Port");
        i_parser.PrintString("userdata2[16:31]", "Slave Device Address");
        i_parser.PrintString("userdata2[32:47]", "Bus Speed");
        i_parser.PrintString("userdata2[48:63]", "Bit Rate Devisor");
        break;

    case 0x70607:
        i_parser.PrintString("devdesc", "Error was found in I2C status register. Check userdata to determine what the error was.");
        i_parser.PrintString("moduleid", "I2C_CHECK_FOR_ERRORS");
        i_parser.PrintString("reasoncode", "I2C_HW_ERROR_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Status Register Value");
        i_parser.PrintString("userdata1[32:63]", "Master Target");
        i_parser.PrintString("userdata2[0:7]", "Master Engine");
        i_parser.PrintString("userdata2[8:15]", "Master Port");
        i_parser.PrintString("userdata2[16:31]", "Slave Device Address");
        i_parser.PrintString("userdata2[32:47]", "Bus Speed");
        i_parser.PrintString("userdata2[48:63]", "Bit Rate Devisor");
        break;

    case 0x70B07:
        i_parser.PrintString("devdesc", "a NACK Error was found in the I2C status register.");
        i_parser.PrintString("moduleid", "I2C_CHECK_FOR_ERRORS");
        i_parser.PrintString("reasoncode", "I2C_NACK_ONLY_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Status Register Value");
        i_parser.PrintString("userdata1[32:63]", "Master Target");
        i_parser.PrintString("userdata2[0:7]", "Master Engine");
        i_parser.PrintString("userdata2[8:15]", "Master Port");
        i_parser.PrintString("userdata2[16:31]", "Slave Device Address");
        i_parser.PrintString("userdata2[32:47]", "Bus Speed");
        i_parser.PrintString("userdata2[48:63]", "Bit Rate Devisor");
        break;

    case 0x70C07:
        i_parser.PrintString("devdesc", "Bus Arbitration Lost Error was found in the I2C status register.");
        i_parser.PrintString("moduleid", "I2C_CHECK_FOR_ERRORS");
        i_parser.PrintString("reasoncode", "I2C_ARBITRATION_LOST_ONLY_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Status Register Value");
        i_parser.PrintString("userdata1[32:63]", "Master Target");
        i_parser.PrintString("userdata2[0:7]", "Master Engine");
        i_parser.PrintString("userdata2[8:15]", "Master Port");
        i_parser.PrintString("userdata2[16:31]", "Slave Device Address");
        i_parser.PrintString("userdata2[32:47]", "Bus Speed");
        i_parser.PrintString("userdata2[48:63]", "Bit Rate Devisor");
        break;

    case 0x70303:
        i_parser.PrintString("devdesc", "Timed out waiting for space to write into FIFO.");
        i_parser.PrintString("moduleid", "I2C_WRITE");
        i_parser.PrintString("reasoncode", "I2C_FIFO_TIMEOUT");
        i_parser.PrintString("userdata1[0:31]", "Status Register Value");
        i_parser.PrintString("userdata1[32:63]", "Master Target");
        i_parser.PrintString("userdata2[0:7]", "Master Engine");
        i_parser.PrintString("userdata2[8:15]", "Master Port");
        i_parser.PrintString("userdata2[16:31]", "Slave Device Address");
        i_parser.PrintString("userdata2[32:47]", "Bus Speed");
        i_parser.PrintString("userdata2[48:63]", "Bit Rate Devisor");
        break;

    case 0x70A0B:
        i_parser.PrintString("devdesc", "ATTR_I2C_BUS_SPEED_ARRAY not found");
        i_parser.PrintString("moduleid", "I2C_FORCE_RESET_AND_UNLOCK");
        i_parser.PrintString("reasoncode", "I2C_ATTRIBUTE_NOT_FOUND");
        i_parser.PrintString("userdata1", "Target for the attribute");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x70A09:
        i_parser.PrintString("devdesc", "ATTR_I2C_BUS_SPEED_ARRAY not found");
        i_parser.PrintString("moduleid", "I2C_SEND_SLAVE_STOP");
        i_parser.PrintString("reasoncode", "I2C_ATTRIBUTE_NOT_FOUND");
        i_parser.PrintString("userdata1", "Target for the attribute");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x70A0A:
        i_parser.PrintString("devdesc", "ATTR_I2C_BUS_SPEED_ARRAY not found");
        i_parser.PrintString("moduleid", "I2C_PROCESS_ACTIVE_MASTERS");
        i_parser.PrintString("reasoncode", "I2C_ATTRIBUTE_NOT_FOUND");
        i_parser.PrintString("userdata1", "Target for the attribute");
        i_parser.PrintString("userdata2[0:31]", "Operation");
        i_parser.PrintString("userdata2[32:64]", "Type");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x700, SrcDataParse, ERRL_CID_HOSTBOOT);
