/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x130101:
        i_parser.PrintString("devdesc", "Unexpected data from LPC-UART interface.");
        i_parser.PrintString("moduleid", "CONSOLE::MOD_CONSOLE_UART_PUTC");
        i_parser.PrintString("reasoncode", "CONSOLE::RC_INVALID_DATA");
        break;

    case 0x130201:
        i_parser.PrintString("devdesc", "Timeout from LPC-UART interface.");
        i_parser.PrintString("moduleid", "CONSOLE::MOD_CONSOLE_UART_PUTC");
        i_parser.PrintString("reasoncode", "CONSOLE::RC_TIMEOUT");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1300, SrcDataParse, ERRL_CID_HOSTBOOT);
