/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x333010:
        i_parser.PrintString("devdesc", "Error calling mm_alloc_block for WOFDATA");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_MM_ALLOC_BLOCK_FAILED");
        i_parser.PrintString("userdata1", "Address being allocated");
        i_parser.PrintString("userdata2[00:31]", "Size of block allocation");
        i_parser.PrintString("userdata2[32:63]", "rc from mm_alloc_block");
        break;

    case 0x333110:
        i_parser.PrintString("devdesc", "Error calling mm_set_permission for WOFDATA");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_MM_SET_PERMISSION_FAILED");
        i_parser.PrintString("userdata1", "Address being changed");
        i_parser.PrintString("userdata2[00:31]", "Size of change");
        i_parser.PrintString("userdata2[32:63]", "rc from mm_set_permission");
        break;

    case 0x332B10:
        i_parser.PrintString("devdesc", "Image header magic value mismatch");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_WOF_IMAGE_MAGIC_MISMATCH");
        i_parser.PrintString("userdata1[00:31]", "Image header magic value");
        i_parser.PrintString("userdata1[32:63]", "Expected magic value");
        i_parser.PrintString("userdata2[00:31]", "LID ID");
        i_parser.PrintString("userdata2[32:63]", "Image header version");
        break;

    case 0x332E10:
        i_parser.PrintString("devdesc", "Image header version not supported");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_WOF_IMAGE_VERSION_MISMATCH");
        i_parser.PrintString("userdata1[00:31]", "Image header version");
        i_parser.PrintString("userdata1[32:63]", "Supported header version");
        i_parser.PrintString("userdata2", "LID ID");
        break;

    case 0x332C10:
        i_parser.PrintString("devdesc", "WOF tables header magic value mismatch");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_WOF_TABLES_MAGIC_MISMATCH");
        i_parser.PrintString("userdata1[00:31]", "WOF tables header magic value");
        i_parser.PrintString("userdata1[32:63]", "Expected magic value");
        i_parser.PrintString("userdata2[00:31]", "WOF tables entry number");
        i_parser.PrintString("userdata2[32:63]", "WOF tables header version");
        break;

    case 0x332F10:
        i_parser.PrintString("devdesc", "WOF tables header version not supported");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_WOF_TABLES_VERSION_MISMATCH");
        i_parser.PrintString("userdata1[00:31]", "WOF tables header version");
        i_parser.PrintString("userdata1[32:63]", "Max supported header version");
        i_parser.PrintString("userdata2", "WOF tables entry number");
        break;

    case 0x332D10:
        i_parser.PrintString("devdesc", "No WOF table match found");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_WOF_TABLE_NOT_FOUND");
        i_parser.PrintString("userdata1[00:15]", "Number of cores");
        i_parser.PrintString("userdata1[16:31]", "WOF Power Mode (0=Nominal,1=Turbo)");
        i_parser.PrintString("userdata1[32:63]", "Socket power");
        i_parser.PrintString("userdata2[00:31]", "Nest frequency");
        i_parser.PrintString("userdata2[32:63]", "Sort frequency");
        break;

    case 0x333210:
        i_parser.PrintString("devdesc", "Error calling mm_remove_pages for WOFDATA");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_MM_REMOVE_PAGES_FAILED");
        i_parser.PrintString("userdata1", "Address being removed");
        i_parser.PrintString("userdata2[00:31]", "Size of removal");
        i_parser.PrintString("userdata2[32:63]", "rc from mm_remove_pages");
        break;

    case 0x333310:
        i_parser.PrintString("devdesc", "Error calling mm_set_permission for WOFDATA");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_PARSE_WOF_TABLES");
        i_parser.PrintString("reasoncode", "fapi2::RC_MM_SET_PERMISSION2_FAILED");
        i_parser.PrintString("userdata1", "Address being changed");
        i_parser.PrintString("userdata2[00:31]", "Size of change");
        i_parser.PrintString("userdata2[32:63]", "rc from mm_set_permission");
        break;

    case 0x332A0C:
        i_parser.PrintString("devdesc", "Invalid attribute read request");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_TARGETING_ATTR");
        i_parser.PrintString("reasoncode", "RC_INVALID_ATTRIBUTE");
        i_parser.PrintString("userdata1[0:31]", "FAPI2 Target Type");
        i_parser.PrintString("userdata1[32:63]", "HB Target HUID");
        i_parser.PrintString("userdata2", "Requested attribute ID");
        break;

    case 0x332A0D:
        i_parser.PrintString("devdesc", "Invalid attribute write request");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_SET_TARGETING_ATTR");
        i_parser.PrintString("reasoncode", "RC_INVALID_ATTRIBUTE");
        i_parser.PrintString("userdata1[0:31]", "FAPI2 Target Type");
        i_parser.PrintString("userdata1[32:63]", "HB Target HUID");
        i_parser.PrintString("userdata2", "Requested attribute ID");
        break;

    case 0x333514:
        i_parser.PrintString("devdesc", "platGetMBvpdMemoryDataVersion could not find an mba parent target from the passed in dimm target.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_ATTR_CEN_VPD_VERSION");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PARENT_MBA");
        i_parser.PrintString("userdata1", "DIMM HUID");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x333414:
        i_parser.PrintString("devdesc", "platGetMBvpdMemoryDataVersion could not find the expected 1 mba from the passed dimm target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_ATTR_CEN_VPD_VERSION");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_SINGLE_MBA");
        i_parser.PrintString("userdata1", "Number of MBAs");
        i_parser.PrintString("userdata2", "DIMM HUID");
        break;

    case 0x333715:
        i_parser.PrintString("devdesc", "platGetMBvpdMemoryDataVersion requires a target of type TYPE_MBA or TYPE_MEMBUF");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_MB_VPD_ATTR");
        i_parser.PrintString("reasoncode", "fapi2::RC_INVALID_TARGET_TYPE");
        i_parser.PrintString("userdata1", "Target Type");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    case 0x333615:
        i_parser.PrintString("devdesc", "platGetMBvpdMemoryDataVersion could not find any child mba's from the passed in target of type TYPE_MEMBUF");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_MB_VPD_ATTR");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_CHILD_MBA");
        i_parser.PrintString("userdata1", "Target Type");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    case 0x333F18:
        i_parser.PrintString("devdesc", "platSetFreqMcaMhz should never be called");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_SET_ATTR_FREQ_MCA_MHZ");
        i_parser.PrintString("reasoncode", "fapi2::RC_SET_ATTR_NOT_VALID");
        i_parser.PrintString("userdata1", "HUID");
        i_parser.PrintString("userdata2", "Requested attr value");
        break;

    case 0x330B05:
        i_parser.PrintString("devdesc", "Couldn't find nimbus or cumulus procs in sys model");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PROCS_FOUND");
        i_parser.PrintString("userdata1", "Model Type we looked for (Nimbus)");
        i_parser.PrintString("userdata2", "Other Model Type we looked for (Cumulus)");
        break;

    case 0x330C05:
        i_parser.PrintString("devdesc", "Could not find a path to the target of that type");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PATH_TO_TARGET_FOUND");
        i_parser.PrintString("userdata1", "Index of target in array of objects");
        i_parser.PrintString("userdata2", "Unused");
        break;

    case 0x330D05:
        i_parser.PrintString("devdesc", "Could not find the parent EX of this CORE target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_CORE_NO_EX_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of core");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x330E05:
        i_parser.PrintString("devdesc", "Could not find the parent EQ of this CORE target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_CORE_NO_EQ_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of core");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331005:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this CORE target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_CORE_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of core");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331105:
        i_parser.PrintString("devdesc", "Could not find the parent EQ of this EX target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_EX_NO_EQ_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of EX");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331205:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this EX target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_EX_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of EX");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331305:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this EQ target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_EQ_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of EQ");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331405:
        i_parser.PrintString("devdesc", "Could not find the parent MSC of this MCA target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_MCA_NO_MCS_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of MCA");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331505:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this MCA target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_MCA_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of MCA");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331605:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this MCS target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_MCS_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of MCS");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331705:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this MCBIST target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_MCBIST_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of MCS");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331905:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this PHB target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_PHB_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of PHB");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331a05:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this PEC target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_PEC_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of PEC");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331b05:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this XBUS target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_XBUS_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of XBUS");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331c05:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this OBUS target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_OBUS_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of OBUS");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331d05:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this OBUS BRICK target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_OBRICK_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of OBUS BRICK");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331e05:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this PPE target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_PPE_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of PPE");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x331f05:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this PERV target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_PERV_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of PERV");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x332005:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this CAPP target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_CAPP_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of CAPP");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x332105:
        i_parser.PrintString("devdesc", "Could not find the parent PROC of this SBE target");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_SBE_NO_PROC_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Expected Parent HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual Parent HUID");
        i_parser.PrintString("userdata2[0:31]", "Instance of SBE");
        i_parser.PrintString("userdata2[32:63]", "fapi2 Type of expected parent");
        break;

    case 0x332305:
        i_parser.PrintString("devdesc", "Could not find the parent PERV of this unit target or the pervasive did not map to expected PROC");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_PARENT_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_UNIT_NO_PERV_FOUND");
        i_parser.PrintString("userdata1[0:31]", "Actual PROC HUID");
        i_parser.PrintString("userdata1[32:63]", "Actual PERV HUID");
        i_parser.PrintString("userdata2[0:31]", "Source unit's chip unit");
        i_parser.PrintString("userdata2[32:63]", "Source unit's targeting type");
        break;

    case 0x330B04:
        i_parser.PrintString("devdesc", "Could not find procs in system model");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_HWP_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PROCS_FOUND");
        i_parser.PrintString("userdata1", "Model Type we looked for");
        i_parser.PrintString("userdata2", "Other Model Type we looked for");
        break;

    case 0x330C04:
        i_parser.PrintString("devdesc", "Could not find a path to the target of that type");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_HWP_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PATH_TO_TARGET_FOUND");
        i_parser.PrintString("userdata1", "Index of target in array of objects");
        i_parser.PrintString("userdata2", "Unused");
        break;

    case 0x330B06:
        i_parser.PrintString("devdesc", "Could not find any procs in system model");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_CHILDREN_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PROCS_FOUND");
        i_parser.PrintString("userdata1", "Model Type we looked for");
        i_parser.PrintString("userdata2", "Other Model Type we looked for");
        break;

    case 0x330C06:
        i_parser.PrintString("devdesc", "Could not find a path to the target of that type");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_CHILDREN_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_NO_PATH_TO_TARGET_FOUND");
        i_parser.PrintString("userdata1", "Index of target in array of objects");
        i_parser.PrintString("userdata2", "Unused");
        break;

    case 0x332206:
        i_parser.PrintString("devdesc", "Invalid amount of child cores found on a proc");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_CHILDREN_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_INVALID_CHILD_COUNT");
        i_parser.PrintString("userdata1[0:31]", "Expected Child Count");
        i_parser.PrintString("userdata1[32:63]", "Actual Child Count");
        i_parser.PrintString("userdata2", "Parent HUID");
        break;

    case 0x33220B:
        i_parser.PrintString("devdesc", "Invalid amount of child cores found on a proc");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_CHILDREN_FILTER_TEST");
        i_parser.PrintString("reasoncode", "fapi2::RC_INVALID_CHILD_COUNT");
        i_parser.PrintString("userdata1[0:31]", "Expected Child Count");
        i_parser.PrintString("userdata1[32:63]", "Actual Child Count");
        i_parser.PrintString("userdata2", "Parent HUID");
        break;

    case 0x33270E:
        i_parser.PrintString("devdesc", "Passed buffer too small");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_VPD");
        i_parser.PrintString("reasoncode", "fapi2::RC_BUFFER_TOO_SMALL");
        i_parser.PrintString("userdata1", "Buffer size");
        i_parser.PrintString("userdata2", "Expected size");
        break;

    case 0x33280E:
        i_parser.PrintString("devdesc", "MR and MT types supported");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_VPD");
        i_parser.PrintString("reasoncode", "fapi2::RC_INVALID_TYPE");
        i_parser.PrintString("userdata1", "Vpd type");
        i_parser.PrintString("userdata2", "HUID of MCS target");
        break;

    case 0x33290E:
        i_parser.PrintString("devdesc", "Less than expected number of bytes returned.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_VPD");
        i_parser.PrintString("reasoncode", "fapi2::RC_RETURNED_VPD_TOO_SMALL");
        i_parser.PrintString("userdata1[0:31]", "Returned vpd in bytes");
        i_parser.PrintString("userdata1[32:64]", "Expected number of vpd bytes");
        i_parser.PrintString("userdata2", "Keyword");
        break;

    case 0x333913:
        i_parser.PrintString("devdesc", "Detecting more than 1 parent proc targets");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_CHIP_CFAM_TARGET");
        i_parser.PrintString("reasoncode", "fapi2::RC_INVALID_PARENT_TARGET_FOUND");
        i_parser.PrintString("userdata1", "Number of parent proc chips found");
        i_parser.PrintString("userdata2", "HUID of input target");
        break;

    case 0x333E17:
        i_parser.PrintString("devdesc", "Call to p9_xip_dd_section_support failed.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_RING");
        i_parser.PrintString("reasoncode", "fapi2::RC_DD_SUPPORT_CHECK_FAILED");
        i_parser.PrintString("userdata1", "requested section id");
        i_parser.PrintString("userdata2", "return code from p9_xip_dd_section_support");
        break;

    case 0x333A17:
        i_parser.PrintString("devdesc", "Call to p9_xip_get_section to retrieve the hw rings section has failed. See userdata2 for the return code value.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_RING");
        i_parser.PrintString("reasoncode", "fapi2::RC_GET_RING_SECTION_FAILED");
        i_parser.PrintString("userdata1", "requested section id");
        i_parser.PrintString("userdata2", "return code from p9_xip_get_section");
        break;

    case 0x333B17:
        i_parser.PrintString("devdesc", "A call to the tor_access_ring function failed. There could be an issue with the centaur hardware image. See userdata2 for the return code value.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_RING");
        i_parser.PrintString("reasoncode", "fapi2::RC_ACCESS_RING_FAILED");
        i_parser.PrintString("userdata1", "requested ring id");
        i_parser.PrintString("userdata2", "return code from tor_access_ring");
        break;

    case 0x333C17:
        i_parser.PrintString("devdesc", "There was an error returned from the RS4 decompression routine see userdata1 for return code value.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_RING");
        i_parser.PrintString("reasoncode", "fapi2::RC_FAILED_TO_DECOMPRESS_RING");
        i_parser.PrintString("userdata1", "return code from scan compression");
        break;

    case 0x334017:
        i_parser.PrintString("devdesc", "There was an error returned from the common ringid_get_ring_list API - see userdata1 for return code value.");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_RING");
        i_parser.PrintString("reasoncode", "fapi2::RC_FAILED_TO_GET_RING_LIST");
        i_parser.PrintString("userdata1", "return code from ringid_get_ring_list");
        break;

    case 0x333D17:
        i_parser.PrintString("devdesc", "The magic header for the hw image is not correct - expected value is XIP CNTR");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_GET_RING");
        i_parser.PrintString("reasoncode", "fapi2::RC_INCORRECT_HW_IMAGE_TYPE");
        i_parser.PrintString("userdata1", "expected HW image type");
        i_parser.PrintString("userdata2", "actual HW image type");
        break;

    case 0x332609:
        i_parser.PrintString("devdesc", "Unable to resolve other end of xbus");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_OTHER_END");
        i_parser.PrintString("reasoncode", "fapi2::RC_FOUND_NO_PEERS");
        i_parser.PrintString("userdata1[0:31]", "Unused");
        i_parser.PrintString("userdata1[32:63]", "Unused");
        i_parser.PrintString("userdata2", "Unused");
        break;

    case 0x332509:
        i_parser.PrintString("devdesc", "Unable to resolve other end of xbus");
        i_parser.PrintString("moduleid", "fapi2::MOD_FAPI2_PLAT_GET_OTHER_END");
        i_parser.PrintString("reasoncode", "fapi2::RC_FOUND_TOO_MANY_PEERS");
        i_parser.PrintString("userdata1[0:31]", "Unused");
        i_parser.PrintString("userdata1[32:63]", "Unused");
        i_parser.PrintString("userdata2", "Unused");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x3300, SrcDataParse, ERRL_CID_HOSTBOOT);
