/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x101201:
        i_parser.PrintString("devdesc", "MDMT could not be chosen for the supplied topology type");
        i_parser.PrintString("moduleid", "TOD_PICK_MDMT");
        i_parser.PrintString("reasoncode", "TOD_MASTER_TARGET_NOT_FOUND");
        i_parser.PrintString("userdata1", "TOD topology type");
        break;

    case 0x100202:
        i_parser.PrintString("devdesc", "MDMT could not find a functional node");
        i_parser.PrintString("moduleid", "TOD_BUILD_TOD_DRAWERS");
        i_parser.PrintString("reasoncode", "TOD_NO_FUNC_NODE_AVAILABLE");
        i_parser.PrintString("userdata1", "system target's HUID");
        break;

    case 0x100302:
        i_parser.PrintString("devdesc", "No TOD drawer could be configured for this topology type");
        i_parser.PrintString("moduleid", "TOD_BUILD_TOD_DRAWERS");
        i_parser.PrintString("reasoncode", "TOD_NO_DRAWERS");
        i_parser.PrintString("userdata1", "TOD configuration");
        break;

    case 0x101303:
        i_parser.PrintString("devdesc", "No valid MDMT found on either topology");
        i_parser.PrintString("moduleid", "TOD_QUERY_ACTIVE_CONFIG");
        i_parser.PrintString("reasoncode", "TOD_NO_VALID_MDMT_FOUND");
        break;

    case 0x101403:
        i_parser.PrintString("devdesc", "MDMT not found on active toplology");
        i_parser.PrintString("moduleid", "TOD_QUERY_ACTIVE_CONFIG");
        i_parser.PrintString("reasoncode", "TOD_NO_MDMT_ON_ACTIVE_CONFIG");
        i_parser.PrintString("userdata1", "Active configuration");
        break;

    case 0x100C1C:
        i_parser.PrintString("devdesc", "Invalid target is supplied as input, SYSTEM target has no parent");
        i_parser.PrintString("moduleid", "TOD_UTIL_MOD_GET_PARENT");
        i_parser.PrintString("reasoncode", "TOD_INVALID_TARGET");
        i_parser.PrintString("userdata1", "HUID of the input target");
        break;

    case 0x10171C:
        i_parser.PrintString("devdesc", "Parent of input CLASS for supplied Target is not found");
        i_parser.PrintString("moduleid", "TOD_UTIL_MOD_GET_PARENT");
        i_parser.PrintString("reasoncode", "TOD_PARENT_NOT_FOUND");
        i_parser.PrintString("userdata1", "HUID of supplied Target");
        i_parser.PrintString("userdata2[0:31]", "Size of the list");
        i_parser.PrintString("userdata2[32:63]", "Input CLASS");
        break;

    case 0x100C19:
        i_parser.PrintString("devdesc", "NULL Target is supplied as an input");
        i_parser.PrintString("moduleid", "TOD_FUNCTIONAL_TARGET");
        i_parser.PrintString("reasoncode", "TOD_INVALID_TARGET");
        break;

    case 0x101306:
        i_parser.PrintString("devdesc", "MDMT could not be found");
        i_parser.PrintString("moduleid", "TOD_SAVEREGS_HWP");
        i_parser.PrintString("reasoncode", "TOD_NO_VALID_MDMT_FOUND");
        i_parser.PrintString("userdata1", "Topology type (primary/secondary)");
        break;

    case 0x101312:
        i_parser.PrintString("devdesc", "No MDMT present on the system");
        i_parser.PrintString("moduleid", "TOD_INIT_HWP");
        i_parser.PrintString("reasoncode", "TOD_NO_VALID_MDMT_FOUND");
        i_parser.PrintString("userdata1", "EMOD_TOD_INIT_HWP");
        i_parser.PrintString("userdata2", "PRIMARY topology type");
        break;

    case 0x100D0F:
        i_parser.PrintString("devdesc", "TOD master drawer not found");
        i_parser.PrintString("moduleid", "TOD_TOPOLOGY_CREATE");
        i_parser.PrintString("reasoncode", "TOD_CREATION_ERR");
        i_parser.PrintString("userdata1", "Topology type : primary/secondary");
        break;

    case 0x101110:
        i_parser.PrintString("devdesc", "TOD drawer not specified");
        i_parser.PrintString("moduleid", "TOD_WIRE_PROCS");
        i_parser.PrintString("reasoncode", "TOD_INVALID_PARAM");
        i_parser.PrintString("userdata1", "Topology type : primary/secondary");
        break;

    case 0x100D10:
        i_parser.PrintString("devdesc", "TOD drawer has one or more disconnected procs");
        i_parser.PrintString("moduleid", "TOD_WIRE_PROCS");
        i_parser.PrintString("reasoncode", "TOD_CREATION_ERR");
        i_parser.PrintString("userdata1[0:31]", "Topology type : primary/secondary");
        i_parser.PrintString("userdata1[32:63]", "TOD drawer id");
        i_parser.PrintString("userdata2", "HUID of first disconnected proc");
        break;

    case 0x101111:
        i_parser.PrintString("devdesc", "TOD drawer not specified");
        i_parser.PrintString("moduleid", "TOD_WIRE_DRAWERS");
        i_parser.PrintString("reasoncode", "TOD_INVALID_PARAM");
        i_parser.PrintString("userdata1", "Topology type : primary/secondary");
        break;

    case 0x101211:
        i_parser.PrintString("devdesc", "MDMT could not be found");
        i_parser.PrintString("moduleid", "TOD_WIRE_DRAWERS");
        i_parser.PrintString("reasoncode", "TOD_MASTER_TARGET_NOT_FOUND");
        i_parser.PrintString("userdata1", "Topology type : primary/secondary");
        break;

    case 0x100D11:
        i_parser.PrintString("devdesc", "TOD drawer couldn't be wired");
        i_parser.PrintString("moduleid", "TOD_WIRE_DRAWERS");
        i_parser.PrintString("reasoncode", "TOD_CREATION_ERR");
        i_parser.PrintString("userdata1", "Topology type : primary/secondary");
        i_parser.PrintString("userdata2", "TOD drawer id");
        break;

    case 0x101A1F:
        i_parser.PrintString("devdesc", "Host interfaces are not initialized");
        i_parser.PrintString("moduleid", "TOD_RT_TOPOLOGY_RESET_BACKUP");
        i_parser.PrintString("reasoncode", "TOD_RT_NULL_FIRMWARE_REQUEST_PTR");
        i_parser.PrintString("userdata1", "None");
        i_parser.PrintString("userdata2", "None");
        break;

    case 0x100C1F:
        i_parser.PrintString("devdesc", "No/Multiple parent(s) found for processor osc target");
        i_parser.PrintString("moduleid", "TOD_RT_TOPOLOGY_RESET_BACKUP");
        i_parser.PrintString("reasoncode", "TOD_INVALID_TARGET");
        i_parser.PrintString("userdata1", "The number of parents found osc target");
        i_parser.PrintString("userdata2", "None");
        break;

    case 0x101A20:
        i_parser.PrintString("devdesc", "Host interfaces are not initialized");
        i_parser.PrintString("moduleid", "TOD_RT_TOPOLOGY_DATA");
        i_parser.PrintString("reasoncode", "TOD_RT_NULL_FIRMWARE_REQUEST_PTR");
        break;

    case 0x100714:
        i_parser.PrintString("devdesc", "Error: TOD HW logic is not running, only use case of resetBackup is when TOD is already running");
        i_parser.PrintString("moduleid", "TOD::TOD_RESET_BACKUP");
        i_parser.PrintString("reasoncode", "TOD::TOD_INVALID_ACTION");
        i_parser.PrintString("userdata1", "ChipTOD logic HW state, 1 means running, zero otherwise");
        break;

    case 0x100507:
        i_parser.PrintString("devdesc", "Error: Unsupported bus type was detected Possible Causes: Invalid bus configuration in targeting, or getBusPort method has not been updated to support all the bus type on a given system. Resolution:Development team should be contacted.");
        i_parser.PrintString("moduleid", "TOD_LOG_UNSUPPORTED_BUSTYPE");
        i_parser.PrintString("reasoncode", "TOD_UNSUPPORTED_BUSTYPE");
        i_parser.PrintString("userdata1", "Bus type that is not currently supported");
        break;

    case 0x100608:
        i_parser.PrintString("devdesc", "Error: Unsupported bus port was detected for the specified bus type. Possible Causes: Invalid bus configuration in targeting, or getBusPort method has not been updated to support all the possible port for a bus on a given system type. Resolution:Development team should be contacted.");
        i_parser.PrintString("moduleid", "TOD_LOG_UNSUPPORTED_BUSPORT");
        i_parser.PrintString("reasoncode", "TOD_UNSUPPORTED_BUSPORT");
        i_parser.PrintString("userdata1", "Bus port that is not currently supported");
        i_parser.PrintString("userdata2", "Bus Type for which the unsupported port has been reported");
        break;

    case 0x101517:
        i_parser.PrintString("devdesc", "This TOD end point target on processor is not receiving signal from the OSC.");
        i_parser.PrintString("moduleid", "TOD_ENDPOINT_CALLOUT");
        i_parser.PrintString("reasoncode", "TOD_MASTER_PATH_ERROR");
        i_parser.PrintString("userdata1", "TOD_ENDPOINT_CALLOUT");
        i_parser.PrintString("userdata2", "HUID of the TOD end point that is not receiving signal");
        break;

    case 0x10080B:
        i_parser.PrintString("devdesc", "Error: Erroneous TOD configuration Possible Causes: Programming issue Resolution: Development team should be contacted.");
        i_parser.PrintString("moduleid", "TOD_LOG_INVALID_CONFIG");
        i_parser.PrintString("reasoncode", "TOD_INVALID_CONFIG");
        i_parser.PrintString("userdata1", "The problematic configuration ( Primary/Secondary)");
        break;

    case 0x10090C:
        i_parser.PrintString("devdesc", "Error: The ordinal Id of one of the TOD procs did not fall in the range 0 <= Ordinal Id < getMaxProcsOnSystem Possible Causes: TOD logic has not been updated to support the latest system type where the no. of processor chips is either equal to or more than getMaxProcsOnSystem Resolution: Development team should be contacted.");
        i_parser.PrintString("moduleid", "TOD_LOG_UNSUPORTED_ORDINALID");
        i_parser.PrintString("reasoncode", "TOD_UNSUPORTED_ORDINALID");
        i_parser.PrintString("userdata1", "Ordinal Id for which the error is logged");
        break;

    case 0x100709:
        i_parser.PrintString("devdesc", "Error: Creation of TOD topology required when TOD HW is running");
        i_parser.PrintString("moduleid", "TOD_SETUP");
        i_parser.PrintString("reasoncode", "TOD_INVALID_ACTION");
        i_parser.PrintString("userdata1", "ChipTOD logic HW state, 1=running, zero otherwise");
        break;

    case 0x100713:
        i_parser.PrintString("devdesc", "Error: Initialization of chip TOD logic cannot be done when its already in the running state");
        i_parser.PrintString("moduleid", "TOD_INIT_ALREADY_RUNNING");
        i_parser.PrintString("reasoncode", "TOD_INVALID_ACTION");
        i_parser.PrintString("userdata1", "EMOD_TOD_INIT");
        i_parser.PrintString("userdata2", "ChipTOD logic HW state, 1=running, zero otherwise");
        break;

    case 0x101315:
        i_parser.PrintString("devdesc", "Error: Could not find MDMT on active topology even though TOD HW logic is running");
        i_parser.PrintString("moduleid", "TOD_MDMT_TOPOLOGY");
        i_parser.PrintString("reasoncode", "TOD_NO_VALID_MDMT_FOUND");
        i_parser.PrintString("userdata1", "EMOD_TOD_SET_ACTIVE_MDMT");
        i_parser.PrintString("userdata2", "Topology type on which MDMT was searched");
        break;

    case 0x101204:
        i_parser.PrintString("devdesc", "Either processor or drawer object was not found for the  MDMT found by reading the processor registers.");
        i_parser.PrintString("moduleid", "TOD_FIND_MASTER_PROC");
        i_parser.PrintString("reasoncode", "TOD_MASTER_TARGET_NOT_FOUND");
        i_parser.PrintString("userdata1[32:64]", "1 = Master proc was not found , zero otherwise");
        i_parser.PrintString("userdata1[32:63]", "1 = Master drawer was not found, zero otherwise");
        i_parser.PrintString("userdata2[0:31]", "EMOD_TOD_SET_ACTIVE_MDMT");
        i_parser.PrintString("userdata2[32:64]", "Active topology");
        break;

    case 0x10191E:
        i_parser.PrintString("devdesc", "Top level Target not found");
        i_parser.PrintString("moduleid", "TOD_IS_MPIPL");
        i_parser.PrintString("reasoncode", "TOD_TOP_LEVEL_TARGET_NOT_FOUND");
        break;

    case 0x100104:
        i_parser.PrintString("devdesc", "No master proc set for this drawer");
        i_parser.PrintString("moduleid", "TOD_FIND_MASTER_PROC");
        i_parser.PrintString("reasoncode", "TOD_NO_MASTER_PROC");
        i_parser.PrintString("userdata1", "TOD drawer id");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1000, SrcDataParse, ERRL_CID_HOSTBOOT);
