/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x31B0C:
        i_parser.PrintString("devdesc", "Caller passed a nullptr target when attempting to write the SCOM cache");
        i_parser.PrintString("moduleid", "SCOM::SCOM_WRITE_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_BAD_TARGET");
        break;

    case 0x31C0C:
        i_parser.PrintString("devdesc", "Caller attempted to write a Centaur cache that is not initialized.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_WRITE_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_CACHE_SEQ_ERROR");
        i_parser.PrintString("userdata1", "HUID of Centaur whose cache was not initialized");
        break;

    case 0x31B0D:
        i_parser.PrintString("devdesc", "Caller passed a nullptr target when attempting to read the SCOM cache");
        i_parser.PrintString("moduleid", "SCOM::SCOM_READ_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_BAD_TARGET");
        break;

    case 0x31C0D:
        i_parser.PrintString("devdesc", "Caller attempted to read a Centaur cache that is not initialized.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_READ_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_CACHE_SEQ_ERROR");
        i_parser.PrintString("userdata1", "HUID of Centaur whose cache was not initialized");
        break;

    case 0x3180B:
        i_parser.PrintString("devdesc", "Centaurs' SCOM cache cannot be verified when caching is enabled");
        i_parser.PrintString("moduleid", "SCOM::SCOM_VERIFY_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_BAD_CACHE_VERIFY_SEQ");
        break;

    case 0x31C0B:
        i_parser.PrintString("devdesc", "Caller attempted to read a Centaur cache that is not initialized.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_VERIFY_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_CACHE_SEQ_ERROR");
        i_parser.PrintString("userdata1", "HUID of Centaur whose cache was not initialized");
        break;

    case 0x31A0B:
        i_parser.PrintString("devdesc", "Failed attempting to read current value of sensitive Centaur SCOM register after locking down the Centaur.  The Centaur will be deconfigured in order to maintain system security.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_VERIFY_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_SENSITIVE_REG_READ_FAIL");
        i_parser.PrintString("userdata1", "HUID of offending Centaur");
        i_parser.PrintString("userdata2", "SCOM address");
        break;

    case 0x3190B:
        i_parser.PrintString("devdesc", "Secure Boot detected an unexpected discrepancy between the expected and actual values of a security sensitive Centaur SCOM register after locking down the Centaur.  The Centaur will be deconfigured in order to maintain system security.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_VERIFY_CENTAUR_CACHE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_CACHE_VERIFY_FAILURE");
        i_parser.PrintString("userdata1", "HUID of Centaur being verified");
        i_parser.PrintString("userdata2", "SCOM address registering the mismatch");
        break;

    case 0x30D05:
        i_parser.PrintString("devdesc", "EKB code has detected and error in the scom");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_P9");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_ISCHIPUNITSCOM_INVALID");
        i_parser.PrintString("userdata1", "Input address");
        i_parser.PrintString("userdata2[0:31]", "Target huid");
        i_parser.PrintString("userdata2[32:63]", "Target Type");
        break;

    case 0x30105:
        i_parser.PrintString("devdesc", "The scom address provided was invalid, check to see if the address matches a target in the scomdef file.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_P9");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_ADDR");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2[0:15]", "Target's Type");
        i_parser.PrintString("userdata2[16:31]", "Instance of this type");
        i_parser.PrintString("userdata2[32:39]", "Is this SCOM addr related to a chip unit?");
        i_parser.PrintString("userdata2[40:47]", "Does the target type and addr type match?");
        i_parser.PrintString("userdata2[48:55]", "Chip unit of the target");
        i_parser.PrintString("userdata2[56:63]", "Model of the target (ex: POWER9)");
        break;

    case 0x30905:
        i_parser.PrintString("devdesc", "Scom Translate not supported for this type");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_P9");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_P9_TRANS_INVALID_TYPE");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2[0:31]", "Target's Type");
        i_parser.PrintString("userdata2[32:63]", "Target's Huid");
        break;

    case 0x30C05:
        i_parser.PrintString("devdesc", "The scom target did not match the provided address");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_P9");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_TARGET_ADDR_MISMATCH");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2[0:15]", "Target's Type");
        i_parser.PrintString("userdata2[16:31]", "Instance of this type");
        i_parser.PrintString("userdata2[32:39]", "Is this SCOM addr related to a chip unit?");
        i_parser.PrintString("userdata2[40:47]", "Does the target type and addr type match?");
        i_parser.PrintString("userdata2[48:55]", "Chip unit of the target");
        i_parser.PrintString("userdata2[56:63]", "Model of the target (ex: POWER9)");
        break;

    case 0x30A05:
        i_parser.PrintString("devdesc", "Scom Translation did not modify the address");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_P9");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_TRANSLATION");
        i_parser.PrintString("userdata1", "Original Address");
        i_parser.PrintString("userdata2[0:15]", "l_chipUnit");
        i_parser.PrintString("userdata2[16:31]", "instance of target");
        i_parser.PrintString("userdata2[32:63]", "HUID of target");
        break;

    case 0x30D08:
        i_parser.PrintString("devdesc", "EKB code has detected and error in the scom");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_CENTAUR");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_ISCHIPUNITSCOM_INVALID");
        i_parser.PrintString("userdata1", "Input address");
        i_parser.PrintString("userdata2[0:31]", "Target huid");
        i_parser.PrintString("userdata2[32:63]", "Target Type");
        break;

    case 0x30108:
        i_parser.PrintString("devdesc", "The scom address provided was invalid, check to see if the address matches a target in the scomdef file.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_CENTAUR");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_ADDR");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2[0:15]", "Target's Type");
        i_parser.PrintString("userdata2[16:31]", "Instance of this type");
        i_parser.PrintString("userdata2[32:39]", "Is this SCOM addr related to a chip unit?");
        i_parser.PrintString("userdata2[40:47]", "Does the target type and addr type match?");
        i_parser.PrintString("userdata2[48:55]", "Chip unit of the target");
        i_parser.PrintString("userdata2[56:63]", "Model of the target (ex: POWER9)");
        break;

    case 0x31408:
        i_parser.PrintString("devdesc", "Scom Translate not supported for this type");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_CENTAUR");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_CEN_TRANS_INVALID_TYPE");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2[0:31]", "Target's Type");
        i_parser.PrintString("userdata2[32:63]", "Target's Huid");
        break;

    case 0x30C08:
        i_parser.PrintString("devdesc", "The scom target did not match the provided address");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_CENTAUR");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_TARGET_ADDR_MISMATCH");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2[0:15]", "Target's Type");
        i_parser.PrintString("userdata2[16:31]", "Instance of this type");
        i_parser.PrintString("userdata2[32:39]", "Is this SCOM addr related to a chip unit?");
        i_parser.PrintString("userdata2[40:47]", "Does the target type and addr type match?");
        i_parser.PrintString("userdata2[48:55]", "Chip unit of the target");
        i_parser.PrintString("userdata2[56:63]", "Model of the target (ex: POWER9)");
        break;

    case 0x30A08:
        i_parser.PrintString("devdesc", "Scom Translation did not modify the address");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE_CENTAUR");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_TRANSLATION");
        i_parser.PrintString("userdata1", "Original Address");
        i_parser.PrintString("userdata2[0:15]", "l_chipUnit");
        i_parser.PrintString("userdata2[16:31]", "instance of target");
        i_parser.PrintString("userdata2[32:63]", "HUID of target");
        break;

    case 0x3010A:
        i_parser.PrintString("devdesc", "The provided address is over 32 bits long which makes it invalid.");
        i_parser.PrintString("moduleid", "SCOM_OP_SANITY_CHECK");
        i_parser.PrintString("reasoncode", "SCOM_INVALID_ADDR");
        i_parser.PrintString("userdata1", "Scom address");
        i_parser.PrintString("userdata2", "Scom target");
        break;

    case 0x3160A:
        i_parser.PrintString("devdesc", "Buffer size is less than allowed or NULL data buffer");
        i_parser.PrintString("moduleid", "SCOM_OP_SANITY_CHECK");
        i_parser.PrintString("reasoncode", "SCOM_INVALID_DATA_BUFFER");
        i_parser.PrintString("userdata1[0:31]", "Buffer size");
        i_parser.PrintString("userdata1[32:63]", "Minimum allowed buffer size");
        i_parser.PrintString("userdata2", "Scom address");
        break;

    case 0x3170A:
        i_parser.PrintString("devdesc", "Scom invalid operation type");
        i_parser.PrintString("moduleid", "SCOM_OP_SANITY_CHECK");
        i_parser.PrintString("reasoncode", "SCOM_INVALID_OP_TYPE");
        i_parser.PrintString("userdata1", "Operation type");
        i_parser.PrintString("userdata2", "Scom address");
        break;

    case 0x30E04:
        i_parser.PrintString("devdesc", "Unsupported indirect scom form");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_FORM");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "HUID of Target");
        break;

    case 0x30504:
        i_parser.PrintString("devdesc", "Indirect SCOM Read error");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_READ_FAIL");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30604:
        i_parser.PrintString("devdesc", "Indirect SCOM complete bit did not come on");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_READ_TIMEOUT");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30704:
        i_parser.PrintString("devdesc", "Indirect SCOM Write failed for this address");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_WRITE_FAIL");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30804:
        i_parser.PrintString("devdesc", "Indirect SCOM complete bit did not come on");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_WRITE_TIMEOUT");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x31006:
        i_parser.PrintString("devdesc", "No read op on form 1 indirect scom.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_DO_FORM_1_INDIRECT_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_FORM_1_READ_REQUEST");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Operation Type");
        break;

    case 0x30F06:
        i_parser.PrintString("devdesc", "Bits 0:11 in user supplied data is not zero");
        i_parser.PrintString("moduleid", "SCOM::SCOM_DO_FORM_1_INDIRECT_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_FORM_1_INVALID_DATA");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "User supplied data");
        break;

    case 0x31509:
        i_parser.PrintString("devdesc", "SCOM access error");
        i_parser.PrintString("moduleid", "SCOM_RT_SEND_SCOM_TO_HYP");
        i_parser.PrintString("reasoncode", "SCOM_RUNTIME_HYP_ERR");
        i_parser.PrintString("userdata1[0:31]", "Hypervisor return code");
        i_parser.PrintString("userdata1[32:63]", "SCOM Op Type");
        i_parser.PrintString("userdata2", "SCOM address");
        break;

    case 0x31209:
        i_parser.PrintString("devdesc", "SCOM runtime interface not linked.");
        i_parser.PrintString("moduleid", "SCOM_RT_SEND_SCOM_TO_HYP");
        i_parser.PrintString("reasoncode", "SCOM_RUNTIME_INTERFACE_ERR");
        i_parser.PrintString("userdata1", "SCOM Op Type");
        i_parser.PrintString("userdata2", "SCOM address");
        break;

    case 0x31207:
        i_parser.PrintString("devdesc", "Wakeup runtime interface not linked.");
        i_parser.PrintString("moduleid", "SCOM_HANDLE_SPECIAL_WAKEUP");
        i_parser.PrintString("reasoncode", "SCOM_RUNTIME_INTERFACE_ERR");
        i_parser.PrintString("userdata1", "Target HUID");
        i_parser.PrintString("userdata2", "Wakeup Enable");
        break;

    case 0x31107:
        i_parser.PrintString("devdesc", "Hypervisor wakeup failed.");
        i_parser.PrintString("moduleid", "SCOM_HANDLE_SPECIAL_WAKEUP");
        i_parser.PrintString("reasoncode", "SCOM_RUNTIME_WAKEUP_ERR");
        i_parser.PrintString("userdata1", "Hypervisor return code");
        i_parser.PrintString("userdata2[0:31]", "Runtime Target ID");
        i_parser.PrintString("userdata2[32:63]", "Wakeup Mode");
        break;

    case 0x31307:
        i_parser.PrintString("devdesc", "Disabling special wakeup when not enabled.");
        i_parser.PrintString("moduleid", "SCOM_HANDLE_SPECIAL_WAKEUP");
        i_parser.PrintString("reasoncode", "SCOM_SPCWKUP_COUNT_ERR");
        i_parser.PrintString("userdata1", "Target HUID");
        i_parser.PrintString("userdata2[0:31]", "Wakeup Enable");
        i_parser.PrintString("userdata2[32:63]", "Wakeup Count");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x300, SrcDataParse, ERRL_CID_HOSTBOOT);
