/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x10303:
        i_parser.PrintString("devdesc", "Errl test. Error with non-decoded string and lots of trace buffers.");
        i_parser.PrintString("moduleid", "ERRORLOG::ERRL_RT_TEST_MOD_ID");
        i_parser.PrintString("reasoncode", "ERRORLOG::ERRL_TEST_REASON_CODE");
        break;

    case 0x10302:
        i_parser.PrintString("devdesc", "Errl test. Error with non-decoded string and lots of trace buffers.");
        i_parser.PrintString("moduleid", "ERRORLOG::ERRL_TEST_MOD_ID");
        i_parser.PrintString("reasoncode", "ERRORLOG::ERRL_TEST_REASON_CODE");
        break;

    case 0x10201:
        i_parser.PrintString("devdesc", "User Details unit test - create string user detail data.");
        i_parser.PrintString("moduleid", "ERRL_USERDATA_TEST_MOD_ID");
        i_parser.PrintString("reasoncode", "ERRL_TEST_STRING_UD");
        i_parser.PrintString("userdata1", "Test data 1");
        i_parser.PrintString("userdata2", "Test data 2");
        break;

    case 0x10401:
        i_parser.PrintString("devdesc", "User Details unit test - create string user detail data.");
        i_parser.PrintString("moduleid", "ERRL_USERDATA_TEST_MOD_ID");
        i_parser.PrintString("reasoncode", "ERRL_TEST_ATTRIBUTE_UD");
        i_parser.PrintString("userdata1", "Test data 1");
        i_parser.PrintString("userdata2", "Test data 2");
        break;

    case 0x10501:
        i_parser.PrintString("devdesc", "User Details unit test - create log register user detail data.");
        i_parser.PrintString("moduleid", "ERRL_USERDATA_TEST_MOD_ID");
        i_parser.PrintString("reasoncode", "ERRL_TEST_LOGREGISTER_UD");
        i_parser.PrintString("userdata1", "Test data 1");
        i_parser.PrintString("userdata2", "Test data 2");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x100, SrcDataParse, ERRL_CID_HOSTBOOT);
