/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x240907:
        i_parser.PrintString("devdesc", "readLPC> Unexpected target");
        i_parser.PrintString("moduleid", "LPC::MOD_READLPC");
        i_parser.PrintString("reasoncode", "LPC::RC_BAD_TARGET");
        i_parser.PrintString("userdata1[00:31]", "Requested target");
        i_parser.PrintString("userdata1[00:31]", "Current alt target");
        i_parser.PrintString("userdata2", "Read address");
        break;

    case 0x240908:
        i_parser.PrintString("devdesc", "writeLPC> Unexpected target");
        i_parser.PrintString("moduleid", "LPC::MOD_WRITELPC");
        i_parser.PrintString("reasoncode", "LPC::RC_BAD_TARGET");
        i_parser.PrintString("userdata1[00:31]", "Requested target");
        i_parser.PrintString("userdata1[00:31]", "Current alt target");
        i_parser.PrintString("userdata2", "Write address");
        break;

    case 0x240606:
        i_parser.PrintString("devdesc", "create_altmaster_objects> Alt-master object already exists");
        i_parser.PrintString("moduleid", "LPC::MOD_CREATE_ALTMASTER");
        i_parser.PrintString("reasoncode", "LPC::RC_ALTMASTER_EXISTS");
        i_parser.PrintString("userdata1", "Requested proc");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x240806:
        i_parser.PrintString("devdesc", "create_altmaster_objects> Cannot create another object using master sentinel");
        i_parser.PrintString("moduleid", "LPC::MOD_CREATE_ALTMASTER");
        i_parser.PrintString("reasoncode", "LPC::RC_CANT_USE_SENTINEL");
        i_parser.PrintString("userdata1", "<unused>");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x240706:
        i_parser.PrintString("devdesc", "create_altmaster_objects> Cannot create another object using master proc");
        i_parser.PrintString("moduleid", "LPC::MOD_CREATE_ALTMASTER");
        i_parser.PrintString("reasoncode", "LPC::RC_CANT_USE_MASTER");
        i_parser.PrintString("userdata1", "<unused>");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x240505:
        i_parser.PrintString("devdesc", "LpcDD::hwReset> Unsupported Reset Level requested");
        i_parser.PrintString("moduleid", "LPC::MOD_LPCDD_HWRESET");
        i_parser.PrintString("reasoncode", "LPC::RC_UNSUPPORTED_OPERATION");
        i_parser.PrintString("userdata1", "Unsupported Reset Level Parameter");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x240101:
        i_parser.PrintString("devdesc", "LpcDD> LPC invalid address");
        i_parser.PrintString("moduleid", "LPC::MOD_LPCDD_CHECKADDR");
        i_parser.PrintString("reasoncode", "LPC::RC_INVALID_ADDR");
        i_parser.PrintString("userdata1[0:31]", "LPC Address");
        i_parser.PrintString("userdata1[32:63]", "LPC Transaction Type");
        break;

    case 0x240302:
        i_parser.PrintString("devdesc", "LpcDD::_readLPC> Invalid buffer size requested (>4 bytes)");
        i_parser.PrintString("moduleid", "LPC::MOD_LPCDD_READLPC");
        i_parser.PrintString("reasoncode", "LPC::RC_BAD_ARG");
        i_parser.PrintString("userdata1[0:31]", "LPC Address");
        i_parser.PrintString("userdata1[32:63]", "LPC Transaction Type");
        i_parser.PrintString("userdata2", "Requested buffer size");
        break;

    case 0x240404:
        i_parser.PrintString("devdesc", "LpcDD::checkLpcErrors> Error(s) found in OPB Status Register");
        i_parser.PrintString("moduleid", "LPC::MOD_LPCDD_CHECKFORLPCERRORS");
        i_parser.PrintString("reasoncode", "LPC::RC_OPB_ERROR");
        i_parser.PrintString("userdata1", "OPBM Error Status Register");
        i_parser.PrintString("userdata2", "Reset Level");
        break;

    case 0x240A04:
        i_parser.PrintString("devdesc", "LpcDD::checkForLpcErrors> Error(s) found in LPCHC Status Register");
        i_parser.PrintString("moduleid", "LPC::MOD_LPCDD_CHECKFORLPCERRORS");
        i_parser.PrintString("reasoncode", "LPC::RC_LPCHC_ERROR");
        i_parser.PrintString("userdata1", "LPCHC Error Status Register");
        i_parser.PrintString("userdata2", "Reset Level");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2400, SrcDataParse, ERRL_CID_HOSTBOOT);
