/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x900509:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_SLCA_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x900532:
        i_parser.PrintString("devdesc", "Creation of mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_TPMDATA_CONSTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        i_parser.PrintString("userdata1[00:31]", "Address attempted to map upper");
        i_parser.PrintString("userdata1[32:63]", "Address attempted to map lower");
        i_parser.PrintString("userdata2[00:31]", "Size of mapped region upper");
        i_parser.PrintString("userdata2[32:63]", "Size of mapped region lower");
        break;

    case 0x900533:
        i_parser.PrintString("devdesc", "Unmap of a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_TPMDATA_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        i_parser.PrintString("userdata1[00:31]", "Address attempted to unmap upper");
        i_parser.PrintString("userdata1[32:63]", "Address attempted to unmap lower");
        break;

    case 0x900202:
        i_parser.PrintString("devdesc", "Top level target not found");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCIA_LOAD");
        i_parser.PrintString("reasoncode", "HDAT::RC_TOP_LVL_TGT_NOT_FOUND");
        break;

    case 0x900103:
        i_parser.PrintString("devdesc", "Input Target Pointer is NULL");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCIA_SET_CORE_INF");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBJECT");
        i_parser.PrintString("userdata1", "Index of proc target");
        break;

    case 0x900303:
        i_parser.PrintString("devdesc", "Invalid input target attribute");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCIA_SET_CORE_INF");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_TGT_ATTR");
        i_parser.PrintString("userdata1", "Index of proc target");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    case 0x900603:
        i_parser.PrintString("devdesc", "Target List is Empty");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCIA_SET_CORE_INF");
        i_parser.PrintString("reasoncode", "HDAT::RC_EMPTY_TARGET_LIST");
        break;

    case 0x900506:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCIA_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x90021f:
        i_parser.PrintString("devdesc", "Top level target not found");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCRD_LOAD");
        i_parser.PrintString("reasoncode", "HDAT::RC_TOP_LVL_TGT_NOT_FOUND");
        break;

    case 0x900A1f:
        i_parser.PrintString("devdesc", "could not find target");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCRD_LOAD");
        i_parser.PrintString("reasoncode", "RC_TGT_ATTR_NOTFOUND");
        break;

    case 0x900120:
        i_parser.PrintString("devdesc", "Input Target Pointer is NULL");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCRD_SET_PROC_INF");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBJECT");
        i_parser.PrintString("userdata1", "Index of proc target");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    case 0x900620:
        i_parser.PrintString("devdesc", "Input Target Pointer is NULL");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCRD_SET_PROC_INF:");
        i_parser.PrintString("reasoncode", "HDAT::RC_EMPTY_TARGET_LIST");
        break;

    case 0x900521:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_PCRD_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x901a2a:
        i_parser.PrintString("devdesc", "Null passed for spirah ms addr");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_GET_SPIRAH");
        i_parser.PrintString("reasoncode", "HDAT::RC_NULL_PTR_PASSED");
        break;

    case 0x900529:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_SPIRAH_DTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        i_parser.PrintString("userdata1", "Spirah address hi");
        i_parser.PrintString("userdata2", "Spirah address lo");
        break;

    case 0x900A2c:
        i_parser.PrintString("devdesc", "The target attribute not found");
        i_parser.PrintString("moduleid", "HDAT::MOD_HBRT_LOAD_DATA");
        i_parser.PrintString("reasoncode", "HDAT::RC_TGT_ATTR_NOTFOUND");
        break;

    case 0x90052c:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_HBRT_LOAD_DATA");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x900525:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_SERVICEDATA_CTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x900101:
        i_parser.PrintString("devdesc", "Input Target Pointer is NULL");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_IS_FUNCTIONAL");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBJECT");
        break;

    case 0x900104:
        i_parser.PrintString("devdesc", "Input Target Pointer is NULL");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_CARD_ID");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBJECT");
        break;

    case 0x900404:
        i_parser.PrintString("devdesc", "Target is not currently supported");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_CARD_ID");
        i_parser.PrintString("reasoncode", "HDAT::RC_TARGET_UNSUPPORTED");
        break;

    case 0x900604:
        i_parser.PrintString("devdesc", "Target list is empty");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_CARD_ID");
        i_parser.PrintString("reasoncode", "HDAT::RC_EMPTY_TARGET_LIST");
        break;

    case 0x901622:
        i_parser.PrintString("devdesc", "PVPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_PVPD_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_PVPD_FAIL");
        i_parser.PrintString("userdata1", "pvpd record");
        i_parser.PrintString("userdata2", "pvpd keyword");
        break;

    case 0x901522:
        i_parser.PrintString("devdesc", "PVPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_PVPD_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_PVPD_READ_FAIL");
        i_parser.PrintString("userdata1", "pvpd record");
        i_parser.PrintString("userdata2", "pvpd keyword");
        break;

    case 0x90162f:
        i_parser.PrintString("devdesc", "PVPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_PVPD_FULL_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_PVPD_FAIL");
        i_parser.PrintString("userdata1", "pvpd record");
        break;

    case 0x90152f:
        i_parser.PrintString("devdesc", "PVPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_PVPD_FULL_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_PVPD_READ_FAIL");
        i_parser.PrintString("userdata1", "pvpd record");
        break;

    case 0x900D11:
        i_parser.PrintString("devdesc", "Device read failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_VPD");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_READ_FAIL");
        break;

    case 0x900D30:
        i_parser.PrintString("devdesc", "Device read failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_MVPD");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_READ_FAIL");
        break;

    case 0x900F12:
        i_parser.PrintString("devdesc", "CVPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_CVPD_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_CVPD_FAIL");
        i_parser.PrintString("userdata1", "cvpd record");
        i_parser.PrintString("userdata2", "cvpd keyword");
        break;

    case 0x900E12:
        i_parser.PrintString("devdesc", "CVPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_CVPD_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_CVPD_READ_FAIL");
        i_parser.PrintString("userdata1", "cvpd record");
        i_parser.PrintString("userdata2", "cvpd keyword");
        break;

    case 0x901013:
        i_parser.PrintString("devdesc", "SPD read fail");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_SPD_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_SPD_READ_FAIL");
        i_parser.PrintString("userdata1", "spd keyword");
        break;

    case 0x901c2d:
        i_parser.PrintString("devdesc", "Device read failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_FULL_MVPD_READ_FUNC");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_READ_VPD_FAIL");
        break;

    case 0x901e34:
        i_parser.PrintString("devdesc", "Invalid OBUS brick ID");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_SMP_LINK_INFO");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBUS_BRICKID");
        break;

    case 0x901f34:
        i_parser.PrintString("devdesc", "Invalid OBUS Freq Bucket");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_SMP_LINK_INFO");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBUS_FREQ_BUCKET");
        break;

    case 0x902034:
        i_parser.PrintString("devdesc", "Undefined Proc model and ec");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_SMP_LINK_INFO");
        i_parser.PrintString("reasoncode", "HDAT::RC_UNDEFINED_PROC_MODEL_EC");
        break;

    case 0x902134:
        i_parser.PrintString("devdesc", "Invalid OBUS PLL frequency value");
        i_parser.PrintString("moduleid", "HDAT::MOD_UTIL_SMP_LINK_INFO");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBUS_PLL_FREQ");
        break;

    case 0x900528:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_SPIRAS_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x901927:
        i_parser.PrintString("devdesc", "could not create the data area from spiras");
        i_parser.PrintString("moduleid", "HDAT::MOD_SPIRAS_CREATE_DATA_AREA");
        i_parser.PrintString("reasoncode", "HDAT::RC_DATA_AREA_FAIL");
        break;

    case 0x900526:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_NODEDATA_DTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x90010D:
        i_parser.PrintString("devdesc", "input Target pointer is NULL");
        i_parser.PrintString("moduleid", "HDAT::MOD_IOHUB_FETCH_DAUGHTER");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_OBJECT");
        break;

    case 0x90040D:
        i_parser.PrintString("devdesc", "Target class not supported");
        i_parser.PrintString("moduleid", "HDAT::MOD_IOHUB_FETCH_DAUGHTER");
        i_parser.PrintString("reasoncode", "HDAT::RC_TARGET_UNSUPPORTED");
        break;

    case 0x90060D:
        i_parser.PrintString("devdesc", "node returned empty Target list");
        i_parser.PrintString("moduleid", "HDAT::MOD_IOHUB_FETCH_DAUGHTER");
        i_parser.PrintString("reasoncode", "HDAT::RC_EMPTY_TARGET_LIST");
        break;

    case 0x900B0E:
        i_parser.PrintString("devdesc", "memory alloc failed in calloc");
        i_parser.PrintString("moduleid", "HDAT::MOD_IOHUB_BUILD_DAUGHTER");
        i_parser.PrintString("reasoncode", "HDAT::RC_MEM_ALLOC_FAIL");
        break;

    case 0x90050F:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_IOHUB_LOAD_DATA");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x90051b:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_MSVPD_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x901114:
        i_parser.PrintString("devdesc", "Exceeded limit of number of mainstore VPD In Memory Trace array entries");
        i_parser.PrintString("moduleid", "MOD_ADD_IMT_ADDR_RANGE");
        i_parser.PrintString("reasoncode", "RC_ERC_MAX_EXCEEDED");
        i_parser.PrintString("userdata1", "current number of array entries");
        i_parser.PrintString("userdata2", "maximum number of array entries");
        i_parser.PrintString("userdata3", "none");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x901115:
        i_parser.PrintString("devdesc", "Exceeded limit of number of mainstore VPD In Memory Trace array entries");
        i_parser.PrintString("moduleid", "MOD_ADD_UE_ADDR_RANGE");
        i_parser.PrintString("reasoncode", "RC_ERC_MAX_EXCEEDED");
        i_parser.PrintString("userdata1", "current number of array entries");
        i_parser.PrintString("userdata2", "maximum number of array entries");
        i_parser.PrintString("userdata3", "none");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x901116:
        i_parser.PrintString("devdesc", "Exceeded limit of number of mainstore VPD Reserved Hostboot array entries");
        i_parser.PrintString("moduleid", "MOD_ADD_RES_HB_ADDR_RANGE");
        i_parser.PrintString("reasoncode", "RC_ERC_MAX_EXCEEDED");
        i_parser.PrintString("userdata1", "current number of array entries");
        i_parser.PrintString("userdata2", "maximum number of array entries");
        i_parser.PrintString("userdata3", "none");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x901117:
        i_parser.PrintString("devdesc", "Exceeded limit of number of mainstore area array entries");
        i_parser.PrintString("moduleid", "MOD_ADD_MS_AREA_FRU");
        i_parser.PrintString("reasoncode", "RC_ERC_MAX_EXCEEDED");
        i_parser.PrintString("userdata1", "current array entry count");
        i_parser.PrintString("userdata2", "maximum array entry count");
        i_parser.PrintString("userdata3", "ID number of mainstore area that wasn't added");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x901218:
        i_parser.PrintString("devdesc", "Attempted to add a RAM FRU for an invalid mainstore area");
        i_parser.PrintString("moduleid", "MOD_ADD_RAM_FRU");
        i_parser.PrintString("reasoncode", "RC_ERC_NO_PARENT");
        i_parser.PrintString("userdata1", "main store area id");
        i_parser.PrintString("userdata2", "current count of main store areas");
        i_parser.PrintString("userdata3", "none");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x901119:
        i_parser.PrintString("devdesc", "Failed trying to add another entry to a mainstore area address range array");
        i_parser.PrintString("moduleid", "MOD_ADD_ADDR_RANGE");
        i_parser.PrintString("reasoncode", "RC_ERC_MAX_EXCEEDED");
        i_parser.PrintString("userdata1", "current number of array entries");
        i_parser.PrintString("userdata2", "maximum number of array entries");
        i_parser.PrintString("userdata3", "ID number of mainstore area");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x90111a:
        i_parser.PrintString("devdesc", "Failed trying to add another entry to a mainstore area RAM array");
        i_parser.PrintString("moduleid", "MOD_ADD_RAM");
        i_parser.PrintString("reasoncode", "RC_ERC_MAX_EXCEEDED");
        i_parser.PrintString("userdata1", "current number of array entries");
        i_parser.PrintString("userdata2", "maximum number of array entries");
        i_parser.PrintString("userdata3", "ID number of mainstore area");
        i_parser.PrintString("userdata4", "none");
        break;

    case 0x90050A:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_IPLPARMS_DESTRUCTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x901823:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_PROCESS_FRU");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_UNMAP_FAIL");
        break;

    case 0x901724:
        i_parser.PrintString("devdesc", "process fru funciton failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_BUILD_SPECIFIED_VPD");
        i_parser.PrintString("reasoncode", "HDAT::RC_PROCESS_FRU_FAIL");
        i_parser.PrintString("userdata1", "Spira data area");
        i_parser.PrintString("userdata2", "Hdat fru type");
        break;

    case 0x901b2b:
        i_parser.PrintString("devdesc", "map a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_NACA_GET_MEM");
        i_parser.PrintString("reasoncode", "HDAT::RC_INVALID_NACA");
        break;

    case 0x90052b:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_NACA_GET_MEM");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x90141c:
        i_parser.PrintString("devdesc", "Master proc target returned is Null");
        i_parser.PrintString("moduleid", "HDAT::MOD_GET_PATH_INFO");
        i_parser.PrintString("reasoncode", "HDAT::RC_MASTER_PROC_TARGET_NULL");
        break;

    case 0x90141d:
        i_parser.PrintString("devdesc", "Master proc target returned is Null");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_SP_SUBSYS_CTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_MASTER_PROC_TARGET_NULL");
        break;

    case 0x90051e:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_SP_SUBSYS_DTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    case 0x900531:
        i_parser.PrintString("devdesc", "Unmap a mapped region failed");
        i_parser.PrintString("moduleid", "HDAT::MOD_HDAT_IPMI_DTOR");
        i_parser.PrintString("reasoncode", "HDAT::RC_DEV_MAP_FAIL");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x9000, SrcDataParse, ERRL_CID_HOSTBOOT);
