/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0xD0301:
        i_parser.PrintString("devdesc", "fsiScomPerformOp> Invalid data length (!= 8 bytes)");
        i_parser.PrintString("moduleid", "FSISCOM::MOD_FSISCOM_PERFORMOP");
        i_parser.PrintString("reasoncode", "FSISCOM::RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "SCOM Address");
        i_parser.PrintString("userdata2", "Data Length");
        break;

    case 0xD0401:
        i_parser.PrintString("devdesc", "fsiScomPerformOp> Address contains more than 31 bits.");
        i_parser.PrintString("moduleid", "FSISCOM::MOD_FSISCOM_PERFORMOP");
        i_parser.PrintString("reasoncode", "FSISCOM::RC_INVALID_ADDRESS");
        i_parser.PrintString("userdata1", "SCOM Address");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    case 0xD0101:
        i_parser.PrintString("devdesc", "fsiScomPerformOp> Error returned from SCOM Engine after write");
        i_parser.PrintString("moduleid", "FSISCOM::MOD_FSISCOM_PERFORMOP");
        i_parser.PrintString("reasoncode", "FSISCOM::RC_WRITE_ERROR");
        i_parser.PrintString("userdata1", "SCOM Addr");
        i_parser.PrintString("userdata2[00:31]", "Target HUID");
        i_parser.PrintString("userdata2[32:63]", "SCOM Status Reg");
        break;

    case 0xD0201:
        i_parser.PrintString("devdesc", "fsiScomPerformOp> Error returned from SCOM Engine after read.");
        i_parser.PrintString("moduleid", "FSISCOM::MOD_FSISCOM_PERFORMOP");
        i_parser.PrintString("reasoncode", "FSISCOM::RC_READ_ERROR");
        i_parser.PrintString("userdata1", "SCOM Addr");
        i_parser.PrintString("userdata2[00:31]", "Target HUID");
        i_parser.PrintString("userdata2[32:63]", "SCOM Status Reg");
        break;

    case 0xD0501:
        i_parser.PrintString("devdesc", "fsiScomPerformOp> Unsupported Operation Type specified");
        i_parser.PrintString("moduleid", "FSISCOM::MOD_FSISCOM_PERFORMOP");
        i_parser.PrintString("reasoncode", "FSISCOM::RC_INVALID_OPTYPE");
        i_parser.PrintString("userdata1[0:31]", "Operation Type (i_opType) : 0=READ, 1=WRITE");
        i_parser.PrintString("userdata1[32:64]", "Input scom address");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0xD00, SrcDataParse, ERRL_CID_HOSTBOOT);
