/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x1F0101:
        i_parser.PrintString("devdesc", "IPC service provider received an unexpected message.");
        i_parser.PrintString("moduleid", "IPC::MOD_IPCSP_MSGHDLR");
        i_parser.PrintString("reasoncode", "IPC::RC_INVALID_MSG_TYPE");
        i_parser.PrintString("userdata1", "Message type");
        i_parser.PrintString("userdata2", "Data word 0 of message");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1F00, SrcDataParse, ERRL_CID_HOSTBOOT);
