/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x265500:
        i_parser.PrintString("devdesc", "No OCC master was found");
        i_parser.PrintString("moduleid", "HTMGT_MOD_LOAD_START_STATUS");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_MASTER_NOT_FOUND");
        i_parser.PrintString("userdata1", "number of OCCs");
        break;

    case 0x262500:
        i_parser.PrintString("devdesc", "OCCs were not loaded/started successfully");
        i_parser.PrintString("moduleid", "HTMGT_MOD_LOAD_START_STATUS");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_START_FAIL");
        i_parser.PrintString("userdata1", "Failing OCC HUID");
        break;

    case 0x264506:
        i_parser.PrintString("devdesc", "No OCC target found for proc Target,");
        i_parser.PrintString("moduleid", "HTMGT_MOD_PROCESS_OCC_RESET");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_PARAMETER");
        i_parser.PrintString("userdata1", "Processor HUID");
        break;

    case 0x2616E1:
        i_parser.PrintString("devdesc", "Operation not allowed, system is in safe mode");
        i_parser.PrintString("moduleid", "HTMGT_MOD_ENABLE_OCC_ACTUATION");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_CRIT_FAILURE");
        i_parser.PrintString("userdata1[0:31]", "OCC activate [1==true][0==false]");
        i_parser.PrintString("userdata1[32:63]", "return code triggering safe mode");
        i_parser.PrintString("userdata2[0:31]", "safeMode flag");
        i_parser.PrintString("userdata2[32:63]", "OCC instance");
        break;

    case 0x262409:
        i_parser.PrintString("devdesc", "Specified OCC not available");
        i_parser.PrintString("moduleid", "HTMGT_MOD_PASS_THRU");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_UNAVAILABLE");
        i_parser.PrintString("userdata1", "command data[0-7]");
        i_parser.PrintString("userdata2", "command data length");
        break;

    case 0x264509:
        i_parser.PrintString("devdesc", "Invalid pass thru command data");
        i_parser.PrintString("moduleid", "HTMGT_MOD_PASS_THRU");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_PARAMETER");
        i_parser.PrintString("userdata1", "command data[0-7]");
        i_parser.PrintString("userdata2", "command data length");
        break;

    case 0x262309:
        i_parser.PrintString("devdesc", "Invalid pass thru command");
        i_parser.PrintString("moduleid", "HTMGT_MOD_PASS_THRU");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_DATA");
        i_parser.PrintString("userdata1", "command data[0-7]");
        i_parser.PrintString("userdata2", "command data length");
        break;

    case 0x261D7D:
        i_parser.PrintString("devdesc", "Bad FRU data received in OCC error log");
        i_parser.PrintString("moduleid", "HTMGT_MOD_BAD_FRU_CALLOUTS");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_ERROR_LOG");
        i_parser.PrintString("userdata1[0-15]", "OCC elog id");
        i_parser.PrintString("userdata1[16-31]", "Bad callout index");
        break;

    case 0x261D7F:
        i_parser.PrintString("devdesc", "No FRU callouts found for non-info OCC Error Log");
        i_parser.PrintString("moduleid", "HTMGT_MOD_MISMATCHING_SEVERITY");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_ERROR_LOG");
        i_parser.PrintString("userdata1[0-15]", "OCC elog id");
        i_parser.PrintString("userdata1[16-31]", "OCC severity");
        break;

    case 0x260E90:
        i_parser.PrintString("devdesc", "Unable to send cmd to OCC exception");
        i_parser.PrintString("moduleid", "HTMGT_MOD_SEND_OCC_CMD");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_EXCEPTION");
        i_parser.PrintString("userdata1", "OCC command");
        i_parser.PrintString("userdata2", "comm established");
        i_parser.PrintString("userdata3", "OCC state");
        i_parser.PrintString("userdata4", "exception");
        break;

    case 0x262490:
        i_parser.PrintString("devdesc", "OCC comm not established or command is not supported");
        i_parser.PrintString("moduleid", "HTMGT_MOD_SEND_OCC_CMD");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_UNAVAILABLE");
        i_parser.PrintString("userdata1", "OCC command");
        i_parser.PrintString("userdata2", "comm established");
        i_parser.PrintString("userdata3", "OCC state");
        i_parser.PrintString("userdata4", "1");
        break;

    case 0x260190:
        i_parser.PrintString("devdesc", "OCC is not valid");
        i_parser.PrintString("moduleid", "HTMGT_MOD_SEND_OCC_CMD");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INTERNAL_ERROR");
        i_parser.PrintString("userdata1", "OCC command type");
        break;

    case 0x2601E0:
        i_parser.PrintString("devdesc", "OCC reported exception");
        i_parser.PrintString("moduleid", "HTMGT_MOD_HANLDE_OCC_EXCEPTION");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INTERNAL_ERROR");
        i_parser.PrintString("userdata1[0-31]", "rsp status");
        i_parser.PrintString("userdata1[32-63]", "exception data length");
        i_parser.PrintString("userdata2[0-31]", "OCC instance");
        i_parser.PrintString("userdata2[32-63]", "exception data");
        break;

    case 0x263591:
        i_parser.PrintString("devdesc", "Timeout waiting for OCC response");
        i_parser.PrintString("moduleid", "HTMGT_MOD_WRITE_OCC_CMD");
        i_parser.PrintString("reasoncode", "HTMGT_RC_TIMEOUT");
        i_parser.PrintString("userdata1[0-15]", "command");
        i_parser.PrintString("userdata1[16-31]", "read timeout");
        i_parser.PrintString("userdata2[0-15]", "response sequence number");
        i_parser.PrintString("userdata2[16-31]", "response status");
        break;

    case 0x261894:
        i_parser.PrintString("devdesc", "Invalid response length received");
        i_parser.PrintString("moduleid", "HTMGT_MOD_PARSE_OCC_RSP");
        i_parser.PrintString("reasoncode", "HTMGT_RC_SEND_FAIL");
        i_parser.PrintString("userdata1[0-15]", "response length");
        i_parser.PrintString("userdata1[16-31]", "response buffer[0-3]");
        i_parser.PrintString("userdata2[0-15]", "response buffer[4-7]");
        break;

    case 0x261B92:
        i_parser.PrintString("devdesc", "Invalid length in OCC response");
        i_parser.PrintString("moduleid", "HTMGT_MOD_CHECK_OCC_RSP");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_CMD_FAIL");
        i_parser.PrintString("userdata1[0-15]", "OCC command type");
        i_parser.PrintString("userdata1[16-31]", "response data length");
        break;

    case 0x261992:
        i_parser.PrintString("devdesc", "OCC response had checksum failure");
        i_parser.PrintString("moduleid", "HTMGT_MOD_CHECK_OCC_RSP");
        i_parser.PrintString("reasoncode", "HTMGT_RC_CHECKSUM_FAIL");
        i_parser.PrintString("userdata1", "OCC command type");
        i_parser.PrintString("userdata2", "sequence number");
        i_parser.PrintString("userdata3", "checksum");
        i_parser.PrintString("userdata4", "calculated checksum");
        break;

    case 0x261B05:
        i_parser.PrintString("devdesc", "Set of OCC state failed");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCC_SET_STATE");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_CMD_FAIL");
        i_parser.PrintString("userdata1[0-31]", "OCC instance");
        i_parser.PrintString("userdata1[32-63]", "Requested state");
        i_parser.PrintString("userdata2[0-31]", "OCC response status");
        i_parser.PrintString("userdata2[32-63]", "current OCC state");
        break;

    case 0x260105:
        i_parser.PrintString("devdesc", "Set state only allowed on master OCC");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCC_SET_STATE");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INTERNAL_ERROR");
        i_parser.PrintString("userdata1", "OCC instance");
        i_parser.PrintString("userdata2", "Requested state");
        break;

    case 0x261608:
        i_parser.PrintString("devdesc", "Homer pointer is nullptr, unable to communicate with the OCCs. Leaving system in safe mode.");
        i_parser.PrintString("moduleid", "HTMGT_MOD_BUILD_OCCS");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_CRIT_FAILURE");
        i_parser.PrintString("userdata1", "OCC Instance");
        i_parser.PrintString("userdata2", "homer virtual address");
        break;

    case 0x262408:
        i_parser.PrintString("devdesc", "No functional OCCs were found");
        i_parser.PrintString("moduleid", "HTMGT_MOD_BUILD_OCCS");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_UNAVAILABLE");
        i_parser.PrintString("userdata1", "functional processor count");
        break;

    case 0x260104:
        i_parser.PrintString("devdesc", "Unable to set state of master OCC");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCCMGR_SET_STATE");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INTERNAL_ERROR");
        break;

    case 0x262604:
        i_parser.PrintString("devdesc", "OCC did not change to requested state");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCCMGR_SET_STATE");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_UNEXPECTED_STATE");
        i_parser.PrintString("userdata1[0-31]", "requested state");
        i_parser.PrintString("userdata1[32-63]", "OCC state");
        i_parser.PrintString("userdata2", "OCC instance");
        break;

    case 0x262304:
        i_parser.PrintString("devdesc", "Invalid OCC state requested");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCCMGR_SET_STATE");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_DATA");
        i_parser.PrintString("userdata1", "requested state");
        break;

    case 0x261607:
        i_parser.PrintString("devdesc", "OCC reset threshold reached. Leaving OCCs in reset state");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCC_RESET");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_CRIT_FAILURE");
        i_parser.PrintString("userdata1", "return code triggering safe mode");
        i_parser.PrintString("userdata2", "OCC instance");
        break;

    case 0x26050B:
        i_parser.PrintString("devdesc", "Set of OCC state failed");
        i_parser.PrintString("moduleid", "HTMGT_MOD_WAIT_FOR_CHECKPOINT");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_NOT_READY");
        i_parser.PrintString("userdata1", "OCC instance");
        i_parser.PrintString("userdata2", "last OCC checkpoint");
        break;

    case 0x260502:
        i_parser.PrintString("devdesc", "OCC not ready for target state");
        i_parser.PrintString("moduleid", "HTMGT_MOD_WAIT_FOR_OCC_READY");
        i_parser.PrintString("reasoncode", "HTMGT_RC_OCC_NOT_READY");
        i_parser.PrintString("userdata1[0-15]", "OCC instance");
        i_parser.PrintString("userdata1[16-31]", "poll attempts");
        i_parser.PrintString("userdata2[0-15]", "target ready bit");
        break;

    case 0x261C76:
        i_parser.PrintString("devdesc", "Invalid POLL response length");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCC_POLL");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "OCC instance");
        break;

    case 0x262276:
        i_parser.PrintString("devdesc", "Invalid role is POLL response");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCC_POLL");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_ROLE");
        i_parser.PrintString("userdata1[0-15]", "OCC instance");
        i_parser.PrintString("userdata[16-31]", "response state");
        i_parser.PrintString("userdata2[0-15]", "expected role");
        i_parser.PrintString("userdata2[16-31]", "response status byte");
        break;

    case 0x262376:
        i_parser.PrintString("devdesc", "Invalid OCC present data in POLL response");
        i_parser.PrintString("moduleid", "HTMGT_MOD_OCC_POLL");
        i_parser.PrintString("reasoncode", "HTMGT_RC_INVALID_DATA");
        i_parser.PrintString("userdata1[0-15]", "OCC instance");
        i_parser.PrintString("userdata1[16-31]", "response OCC present");
        i_parser.PrintString("userdata2[0-15]", "expected OCC present");
        i_parser.PrintString("userdata2[16-31]", "response status byte");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2600, SrcDataParse, ERRL_CID_HOSTBOOT);
