/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x110F09:
        i_parser.PrintString("devdesc", "Could not register mailbox message queue");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_INIT");
        i_parser.PrintString("reasoncode", "MBOX::RC_KERNEL_REG_FAILED");
        i_parser.PrintString("userdata1", "rc from msq_q_register");
        break;

    case 0x111304:
        i_parser.PrintString("devdesc", "IPC Message data corrupted");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_HNDLR");
        i_parser.PrintString("reasoncode", "MBOX::RC_IPC_INVALID_DATA");
        i_parser.PrintString("userdata1", "IPC Data Area MSG Queue ID");
        break;

    case 0x110C04:
        i_parser.PrintString("devdesc", "Invalid message type sent to mailbox msgQ");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_HNDLR");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_MBOX_MSG_TYPE");
        i_parser.PrintString("userdata1", "Message type");
        break;

    case 0x111008:
        i_parser.PrintString("devdesc", "Mailbox is disabled, message dropped.");
        i_parser.PrintString("moduleid", "MOD_MBOXSRV_SENDMSG");
        i_parser.PrintString("reasoncode", "RC_MAILBOX_DISABLED");
        i_parser.PrintString("userdata1", "queue_id");
        i_parser.PrintString("userdata2", "message type");
        break;

    case 0x110E08:
        i_parser.PrintString("devdesc", "Failed to allocate a DMA buffer. Message dropped.");
        i_parser.PrintString("moduleid", "MOD_MBOXSRV_SENDMSG");
        i_parser.PrintString("reasoncode", "RC_INVALID_DMA_LENGTH");
        i_parser.PrintString("userdata1", "DMA length requested");
        i_parser.PrintString("userdata2", "queue_id");
        break;

    case 0x111205:
        i_parser.PrintString("devdesc", "Invalid msg or msg queue");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_RCV");
        i_parser.PrintString("reasoncode", "MBOX::RC_MSG_SEND_ERROR");
        i_parser.PrintString("userdata1", "rc from msg_send()");
        i_parser.PrintString("userdata2", "msg queue id");
        break;

    case 0x110205:
        i_parser.PrintString("devdesc", "Message from FSP. Message type is not within a valid range. Message dropped.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_RCV");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_MESSAGE_TYPE");
        i_parser.PrintString("userdata1", "msg queue");
        i_parser.PrintString("userdata2", "msg type");
        break;

    case 0x110507:
        i_parser.PrintString("devdesc", "Message from FSP. An invalid message queue ID or mesage type was sent to the FSP.");
        i_parser.PrintString("moduleid", "MOD_MBOXSRV_FSP_MSG");
        i_parser.PrintString("reasoncode", "RC_INVALID_QUEUE");
        i_parser.PrintString("userdata1", "msg queue");
        i_parser.PrintString("userdata2", "msg type");
        break;

    case 0x110207:
        i_parser.PrintString("devdesc", "Message from FSP to HB MBOX of an unknown type");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_FSP_MSG");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_MESSAGE_TYPE");
        i_parser.PrintString("userdata1", "msg type");
        i_parser.PrintString("userdata2", "msg queue id");
        break;

    case 0x110503:
        i_parser.PrintString("devdesc", "Invalid message or message queue");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_SEND");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_QUEUE");
        i_parser.PrintString("userdata1", "returncode from msg_sendrecv()");
        break;

    case 0x110D03:
        i_parser.PrintString("devdesc", "Host boot mailbox service is not available at this time.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_SEND");
        i_parser.PrintString("reasoncode", "MBOX::RC_MBOX_SERVICE_NOT_READY");
        i_parser.PrintString("userdata1", "The destination message queue id");
        break;

    case 0x110706:
        i_parser.PrintString("devdesc", "Message queue already registered with mailbox using a different queue.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXREGISTER");
        i_parser.PrintString("reasoncode", "MBOX::RC_ALREADY_REGISTERED");
        i_parser.PrintString("userdata1", "queue_id_t queueId");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x110A04:
        i_parser.PrintString("devdesc", "Mailbox Data Write attempted before ACK.");
        i_parser.PrintString("moduleid", "MOD_MBOXSRV_HNDLR");
        i_parser.PrintString("reasoncode", "RC_DATA_WRITE_ERR");
        i_parser.PrintString("userdata1", "Status from MB device driver");
        break;

    case 0x110B04:
        i_parser.PrintString("devdesc", "Mailbox Hardware detected parity error.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_HNDLR");
        i_parser.PrintString("reasoncode", "MBOX::RC_PARITY_ERR");
        i_parser.PrintString("userdata1", "Status from MB device driver");
        break;

    case 0x110904:
        i_parser.PrintString("devdesc", "Retry failed. Bad status indicated in PIB status reg.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_HNDLR");
        i_parser.PrintString("reasoncode", "MBOX::RC_ILLEGAL_OP");
        i_parser.PrintString("userdata1", "Status from MB device driver");
        break;

    case 0x11120C:
        i_parser.PrintString("devdesc", "Invalid msg or msg queue");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRV_IPC_MSG");
        i_parser.PrintString("reasoncode", "MBOX::RC_MSG_SEND_ERROR");
        i_parser.PrintString("userdata1", "rc from msg_send()");
        i_parser.PrintString("userdata2", "msg queue id");
        break;

    case 0x11050C:
        i_parser.PrintString("devdesc", "Invalid message queue ID");
        i_parser.PrintString("moduleid", "MOD_MBOXSRV_IPC_MSG");
        i_parser.PrintString("reasoncode", "RC_INVALID_QUEUE");
        i_parser.PrintString("userdata1", "msg queue");
        i_parser.PrintString("userdata2", "msg type");
        break;

    case 0x11050A:
        i_parser.PrintString("devdesc", "Message from FSP. Message not claimed by any Hostboot service.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXSRC_UNCLAIMED");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_QUEUE");
        i_parser.PrintString("userdata1", "msg queue");
        i_parser.PrintString("userdata2", "msg type");
        break;

    case 0x11050B:
        i_parser.PrintString("devdesc", "Error sending IPC message");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOX_SEND");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_QUEUE");
        i_parser.PrintString("userdata1", "returncode from msg_send()");
        i_parser.PrintString("userdata2", "q_handle");
        break;

    case 0x11110B:
        i_parser.PrintString("devdesc", "An invalid node was specified");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOX_SEND");
        i_parser.PrintString("reasoncode", "MBOX::RC_IPC_INVALID_NODE");
        i_parser.PrintString("userdata1", "The destination queue id");
        i_parser.PrintString("userdata2", "The node");
        break;

    case 0x110D06:
        i_parser.PrintString("devdesc", "Mailbox service is not available now.");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXREGISTER");
        i_parser.PrintString("reasoncode", "MBOX::RC_MBOX_SERVICE_NOT_READY");
        i_parser.PrintString("userdata1", "queue_id_t queueId");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x11120D:
        i_parser.PrintString("devdesc", "Message send to mailbox sp failed");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOX_MSGQ_FAIL");
        i_parser.PrintString("reasoncode", "MBOX::RC_MSG_SEND_ERROR");
        i_parser.PrintString("userdata1", "kernel errno");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x110102:
        i_parser.PrintString("devdesc", "MboxDD::write> Invalid data length (> msg_t size)");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXDD_WRITE");
        i_parser.PrintString("reasoncode", "MBOX::RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "Target ID String...");
        i_parser.PrintString("userdata2", "Data Length");
        break;

    case 0x110402:
        i_parser.PrintString("devdesc", "MboxDD::write> Message still pending");
        i_parser.PrintString("moduleid", "MBOX::MOD_MBOXDD_WRITE");
        i_parser.PrintString("reasoncode", "MBOX::RC_MSG_PENDING");
        i_parser.PrintString("userdata1", "Target ID String...");
        i_parser.PrintString("userdata2", "Status/Control Register");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1100, SrcDataParse, ERRL_CID_HOSTBOOT);
