/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x250e07:
        i_parser.PrintString("devdesc", "VPD data is invalid size");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMIFRU_INV");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_VPD_DATA");
        i_parser.PrintString("userdata1", "Size of vpd data");
        break;

    case 0x250306:
        i_parser.PrintString("devdesc", "msg_send() failed");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISRV_POSTEVENT");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SEND");
        i_parser.PrintString("userdata1", "rc from msq_send()");
        break;

    case 0x250201:
        i_parser.PrintString("devdesc", "msg_sendrecv() failed");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISRV_SEND");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENDRECV");
        i_parser.PrintString("userdata1", "rc from msq_sendrecv()");
        break;

    case 0x250301:
        i_parser.PrintString("devdesc", "msg_send() failed");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISRV_SEND");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SEND");
        i_parser.PrintString("userdata1", "rc from msq_send()");
        break;

    case 0x250f08:
        i_parser.PrintString("devdesc", "The passed in sensor number is not valid.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_TYPE");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENSOR_NUMBER");
        i_parser.PrintString("userdata1", "IPMI Sensor Number");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250d08:
        i_parser.PrintString("devdesc", "The sensor could not be found based upon the sensor number.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_TYPE");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_NOT_FOUND");
        i_parser.PrintString("userdata1", "IPMI Sensor Number");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250f09:
        i_parser.PrintString("devdesc", "The passed in sensor number is not valid.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_ENTITY_ID");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENSOR_NUMBER");
        i_parser.PrintString("userdata1", "IPMI Sensor Number");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250d09:
        i_parser.PrintString("devdesc", "The sensor could not be found based upon the sensor number.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_ENTITY_ID");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_NOT_FOUND");
        i_parser.PrintString("userdata1", "IPMI Sensor Number");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250f0A:
        i_parser.PrintString("devdesc", "The passed in sensor number is not valid.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_NAME");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENSOR_NUMBER");
        i_parser.PrintString("userdata1", "IPMI Sensor Number");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250d0A:
        i_parser.PrintString("devdesc", "The sensor could not be found based upon the sensor number.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_NAME");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_NOT_FOUND");
        i_parser.PrintString("userdata1", "IPMI Sensor Number");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250102:
        i_parser.PrintString("devdesc", "msg_respond() failed");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISRV_REPLY");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_QRESPONSE");
        i_parser.PrintString("userdata1", "rc from msg_respond()");
        break;

    case 0x250902:
        i_parser.PrintString("devdesc", "an async completion code was not CC_OK");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISRV_REPLY");
        i_parser.PrintString("reasoncode", "IPMI::RC_READ_EVENT_FAILURE");
        i_parser.PrintString("userdata1", "command of message");
        i_parser.PrintString("userdata2", "completion code");
        break;

    case 0x250503:
        i_parser.PrintString("devdesc", "Set sensor reading command failed.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_NOT_SETTABLE");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        i_parser.PrintString("userdata2", "bytes [0-1]sensor name bytes [2-3]sensor number bytes [4-7]HUID of target.");
        break;

    case 0x250603:
        i_parser.PrintString("devdesc", "Set sensor reading command failed.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_EVENT_DATA_NOT_SETTABLE");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        i_parser.PrintString("userdata2", "bytes[0-3]sensor number bytes[4-7]HUID of target.");
        break;

    case 0x250403:
        i_parser.PrintString("devdesc", "Command not valid for this sensor.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENSOR_CMD");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        i_parser.PrintString("userdata2", "bytes [0-1]sensor name bytes [2-3]sensor number bytes [4-7]HUID of target.");
        break;

    case 0x250703:
        i_parser.PrintString("devdesc", "Requested sensor is not present.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_NOT_PRESENT");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        i_parser.PrintString("userdata2", "bytes [0-1]sensor name bytes [2-3]sensor number bytes [4-7]HUID of target.");
        break;

    case 0x250803:
        i_parser.PrintString("devdesc", "Set sensor reading command failed.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_SET_SENSOR_FAILURE");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        i_parser.PrintString("userdata2", "bytes [0-1]sensor name bytes [2-3]sensor number bytes [4-7]HUID of target.");
        break;

    case 0x250d03:
        i_parser.PrintString("devdesc", "Requested sensor attribute not found.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_NOT_FOUND");
        i_parser.PrintString("userdata1", "Returned sensor number.");
        i_parser.PrintString("userdata2", "bytes [0-3]sensor name bytes [4-7]HUID of target.");
        break;

    case 0x250b03:
        i_parser.PrintString("devdesc", "Set sensor reading command failed.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_SENSOR_READING_NOT_AVAIL");
        i_parser.PrintString("userdata1", "sensor status indicating reason for reading not available");
        i_parser.PrintString("userdata2[0:31]", "sensor number");
        i_parser.PrintString("userdata2[32:64]", "HUID of target");
        break;

    case 0x250c03:
        i_parser.PrintString("devdesc", "Request to get sensor type form the bmc failed.");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR");
        i_parser.PrintString("reasoncode", "IPMI::RC_GET_SENSOR_TYPE_CMD_FAILED");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        break;

    case 0x25100B:
        i_parser.PrintString("devdesc", "The sensor returned an invalid setting");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_REBOOTCNTRL");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENSOR_SETTING");
        i_parser.PrintString("userdata1", "Invalid reboot control setting");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x25100C:
        i_parser.PrintString("devdesc", "The sensor returned an invalid setting");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMISENSOR_HBVOLATILE");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENSOR_SETTING");
        i_parser.PrintString("userdata1", "Invalid hb volatile control setting");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x250a04:
        i_parser.PrintString("devdesc", "Request to get power limit information failed");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMIDCMI");
        i_parser.PrintString("reasoncode", "IPMI::RC_DCMI_CMD_FAILED");
        i_parser.PrintString("userdata1", "BMC IPMI Completion code.");
        break;

    case 0x250205:
        i_parser.PrintString("devdesc", "ipmi_msg() failed");
        i_parser.PrintString("moduleid", "IPMI::MOD_IPMIRT");
        i_parser.PrintString("reasoncode", "IPMI::RC_INVALID_SENDRECV");
        i_parser.PrintString("userdata1[0:31]", "rc from ipmi_msg()");
        i_parser.PrintString("userdata1[32:46]", "netfn of failing msg");
        i_parser.PrintString("userdata1[47:63]", "cmd of failing msg");
        i_parser.PrintString("userdata2", "length of failing msg");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2500, SrcDataParse, ERRL_CID_HOSTBOOT);
