/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x50903:
        i_parser.PrintString("devdesc", "IStep failed and HW deconfigured. Looped back to an earlier istep (Reconfigure loop).");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "ISTEP_RECONFIG_LOOP_ENTERED");
        i_parser.PrintString("userdata1[0:15]", "Istep that failed");
        i_parser.PrintString("userdata1[16:31]", "Substep that failed");
        i_parser.PrintString("userdata1[32:47]", "Istep that reconfig looped back to");
        i_parser.PrintString("userdata1[48:63]", "Substep that reconfig looped back to");
        i_parser.PrintString("userdata2", "The number of reconfigs loops tried");
        break;

    case 0x51103:
        i_parser.PrintString("devdesc", "Istep skip prevented in secure mode");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "ISTEP_SKIP_ATTEMPTED");
        i_parser.PrintString("userdata1[00:31]", "istep requested");
        i_parser.PrintString("userdata1[32:64]", "substep requested");
        i_parser.PrintString("userdata2[00:31]", "highest istep allowed");
        i_parser.PrintString("userdata2[32:64]", "highest substep allowed");
        break;

    case 0x50803:
        i_parser.PrintString("devdesc", "Request to send Istep Complete msg to Fsp, but no outstanding message from Fsp found.");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "NO_MSG_PRESENT");
        i_parser.PrintString("userdata1", "Current Istep");
        i_parser.PrintString("userdata2", "Current SubStep");
        break;

    case 0x50b03:
        i_parser.PrintString("devdesc", "Received shutdown request from FSP");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "SHUTDOWN_REQUESTED_BY_FSP");
        i_parser.PrintString("userdata1", "Current IStep");
        i_parser.PrintString("userdata2", "Current SubStep");
        break;

    case 0x51003:
        i_parser.PrintString("devdesc", "Received shutdown request due to deconfigure outside of reconfig loop");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "SHUTDOWN_NOT_RECONFIG_LOOP");
        i_parser.PrintString("userdata1", "Current IStep");
        i_parser.PrintString("userdata2", "Current SubStep");
        break;

    case 0x51203:
        i_parser.PrintString("devdesc", "Istep processing has terminated due to normal shutdown activity, secure boot key transition, or terminating error");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "ISTEP_PROCESSING_DISABLED");
        i_parser.PrintString("userdata1", "Istep Requested");
        i_parser.PrintString("userdata2", "Substep Requested");
        break;

    case 0x50d03:
        i_parser.PrintString("devdesc", "Istep messaged received by non-master node.");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "ISTEP_NON_MASTER_NODE_MSG");
        i_parser.PrintString("userdata1", "Istep Requested");
        i_parser.PrintString("userdata2", "Substep Requested");
        break;

    case 0x50c03:
        i_parser.PrintString("devdesc", "handleProcFabIovalidMsg called during MPIPL, which is illegal.");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "ISTEP_INVALID_ON_MPIPL");
        i_parser.PrintString("userdata1[0:31]", "MPIPL State");
        i_parser.PrintString("userdata1[32:63]", "N/A");
        i_parser.PrintString("userdata2[0:31]", "N/A");
        i_parser.PrintString("userdata2[32:63]", "N/A.");
        break;

    case 0x50a03:
        i_parser.PrintString("devdesc", "Hostboot has requested a reconfig loop due to a hardware error.  Causes could be: - deconfiguration during an istep outside of the the reconfig loop - deconfiguration while running in istep mode - deconfiguration in mfg mode - exceeded the number of allowed reconfig attempts - recoverable hardware error that requires a reboot to clear out");
        i_parser.PrintString("moduleid", "ISTEP_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "ISTEP_FAILED_DUE_TO_DECONFIG");
        i_parser.PrintString("userdata1[00:15]", "Istep that failed");
        i_parser.PrintString("userdata1[16:31]", "SubStep that failed");
        i_parser.PrintString("userdata1[32:47]", "Desired istep");
        i_parser.PrintString("userdata1[48:63]", "Desired substep");
        i_parser.PrintString("userdata2[00:07]", "Value of ATTR_RECONFIGURE_LOOP - 0x01 = DECONFIGURE - 0x02 = BAD_DQ_BIT_SET - 0x04 = RCD_PARITY_ERROR");
        i_parser.PrintString("userdata2[08:15]", "Manufacturing Mode (MNFG_FLAG_SRC_TERM)");
        i_parser.PrintString("userdata2[16:23]", "Largest number of RCD reboots (ATTR_RCD_PARITY_RECONFIG_LOOP_COUNT)");
        i_parser.PrintString("userdata2[24:31]", "Number of RCD reboots allowed (ATTR_RCD_PARITY_RECONFIG_LOOPS_ALLOWED)");
        i_parser.PrintString("userdata2[32:39]", "RCD parity error threshold (ATTR_MNFG_TH_RCD_PARITY_ERRORS)");
        i_parser.PrintString("userdata2[40:63]", "Unused");
        break;

    case 0x50f05:
        i_parser.PrintString("devdesc", "This error log was intentionally created in order to induce a reconfigure loop for testing purposes.");
        i_parser.PrintString("moduleid", "RECONFIG_LOOP_TEST_ID");
        i_parser.PrintString("reasoncode", "RECONFIG_LOOP_TEST_RC");
        break;

    case 0x50701:
        i_parser.PrintString("devdesc", "Initialization Service failed to load a module needed to load a function or task. UserDetails will contain the name of the function or task.");
        i_parser.PrintString("moduleid", "BASE_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "INITSVC_LOAD_MODULE_FAILED");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x50101:
        i_parser.PrintString("devdesc", "Initialization Service failed to start a task.");
        i_parser.PrintString("moduleid", "BASE_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "START_TASK_FAILED");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "task id or task return code");
        break;

    case 0x50501:
        i_parser.PrintString("devdesc", "Initialization Service launched a task and the task returned an error.");
        i_parser.PrintString("moduleid", "BASE_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "WAIT_TASK_FAILED");
        i_parser.PrintString("userdata1", "task id or task return code");
        i_parser.PrintString("userdata2", "returned status from task");
        break;

    case 0x50201:
        i_parser.PrintString("devdesc", "Initialization Service attempted to start a function within a module but the function failed to launch");
        i_parser.PrintString("moduleid", "BASE_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "START_FN_FAILED");
        i_parser.PrintString("userdata1", "task return code");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x50601:
        i_parser.PrintString("devdesc", "Initialization Service launched a function and the task returned an error.");
        i_parser.PrintString("moduleid", "BASE_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "WAIT_FN_FAILED");
        i_parser.PrintString("userdata1", "task id or task return code");
        i_parser.PrintString("userdata2", "returned status from task");
        break;

    case 0x50401:
        i_parser.PrintString("devdesc", "Could not FLUSH virtual memory.");
        i_parser.PrintString("moduleid", "BASE_INITSVC_MOD_ID");
        i_parser.PrintString("reasoncode", "SHUTDOWN_FLUSH_FAILED");
        i_parser.PrintString("userdata1", "returncode from mm_remove_pages()");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x50304:
        i_parser.PrintString("devdesc", "One or more CxxTest Unit Tests failed.");
        i_parser.PrintString("moduleid", "CXXTEST_MOD_ID");
        i_parser.PrintString("reasoncode", "CXXTEST_FAILED_TEST");
        i_parser.PrintString("userdata1", "number of failed tests");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x500, SrcDataParse, ERRL_CID_HOSTBOOT);
