/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Tue May 15 13:26:15 2018
 * Image Id:    hb0515b_1820.920
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x270B01:
        i_parser.PrintString("devdesc", "Invalid operation type.");
        i_parser.PrintString("moduleid", "TPMDD_PERFORM_OP");
        i_parser.PrintString("reasoncode", "TPM_DEVICE_NOT_AVAILABLE");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2", "Operation Type");
        break;

    case 0x270801:
        i_parser.PrintString("devdesc", "TPM buffer length > 4 for read vendor op");
        i_parser.PrintString("moduleid", "TPMDD_PERFORM_OP");
        i_parser.PrintString("reasoncode", "TPM_OVERFLOW_ERROR");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0-31]", "Operation");
        i_parser.PrintString("userdata2[32-63]", "Buffer Length      (in Bytes)");
        break;

    case 0x270101:
        i_parser.PrintString("devdesc", "Invalid operation type.");
        i_parser.PrintString("moduleid", "TPMDD_PERFORM_OP");
        i_parser.PrintString("reasoncode", "TPM_INVALID_OPERATION");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2", "Operation Type");
        break;

    case 0x27010C:
        i_parser.PrintString("devdesc", "presenceDetect> Invalid data length (!= 1 bytes)");
        i_parser.PrintString("moduleid", "TPMDD_TPMPRESENCEDETECT");
        i_parser.PrintString("reasoncode", "TPM_INVALID_OPERATION");
        i_parser.PrintString("userdata1", "Data Length");
        break;

    case 0x270204:
        i_parser.PrintString("devdesc", "The Device type not supported (addrSize)");
        i_parser.PrintString("moduleid", "TPMDD_PREPAREADDRESS");
        i_parser.PrintString("reasoncode", "TPM_INVALID_DEVICE_TYPE");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2", "Address Size (aka Device Type)");
        break;

    case 0x270305:
        i_parser.PrintString("devdesc", "TPM attribute was not found");
        i_parser.PrintString("moduleid", "TPMDD_READATTRIBUTES");
        i_parser.PrintString("reasoncode", "TPM_ATTR_INFO_NOT_FOUND");
        i_parser.PrintString("userdata1", "HUID of target");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x270705:
        i_parser.PrintString("devdesc", "Invalid address offset size");
        i_parser.PrintString("moduleid", "TPMDD_READATTRIBUTES");
        i_parser.PrintString("reasoncode", "TPM_INVALID_ADDR_OFFSET_SIZE");
        i_parser.PrintString("userdata1", "HUID of target");
        i_parser.PrintString("userdata2", "Address Offset Size");
        break;

    case 0x270C05:
        i_parser.PrintString("devdesc", "Invalid address offset size");
        i_parser.PrintString("moduleid", "TPMDD_READATTRIBUTES");
        i_parser.PrintString("reasoncode", "TPM_BUS_SPEED_LOOKUP_FAIL");
        i_parser.PrintString("userdata1", "HUID of target");
        i_parser.PrintString("userdata2", "Address Offset Size");
        break;

    case 0x270506:
        i_parser.PrintString("devdesc", "I2C master entity path doesn't exist.");
        i_parser.PrintString("moduleid", "TPMDD_GETI2CMASTERTARGET");
        i_parser.PrintString("reasoncode", "TPM_I2C_MASTER_PATH_ERROR");
        i_parser.PrintString("userdata1", "HUID of target");
        i_parser.PrintString("userdata2", "Compressed Entity Path");
        break;

    case 0x270606:
        i_parser.PrintString("devdesc", "I2C master path target is null.");
        i_parser.PrintString("moduleid", "TPMDD_GETI2CMASTERTARGET");
        i_parser.PrintString("reasoncode", "TPM_TARGET_NULL");
        i_parser.PrintString("userdata1", "HUID of target");
        i_parser.PrintString("userdata2", "Compressed Entity Path");
        break;

    case 0x270A0B:
        i_parser.PrintString("devdesc", "TPM timeout waiting for stsValid");
        i_parser.PrintString("moduleid", "TPMDD_READSTSREGVALID");
        i_parser.PrintString("reasoncode", "TPM_TIMEOUT");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0:31]", "Operation");
        i_parser.PrintString("userdata2[32:63]", "STS Reg");
        break;

    case 0x270A07:
        i_parser.PrintString("devdesc", "Timeout waiting for TPM to enter command ready state.");
        i_parser.PrintString("moduleid", "TPMDD_POLLFORCOMMMANDREADY");
        i_parser.PrintString("reasoncode", "TPM_TIMEOUT");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2", "STS Reg");
        break;

    case 0x270A08:
        i_parser.PrintString("devdesc", "Timeout waiting for TPM data available.");
        i_parser.PrintString("moduleid", "TPMDD_POLLFORDATAAVAIL");
        i_parser.PrintString("reasoncode", "TPM_TIMEOUT");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2", "STS Reg");
        break;

    case 0x270809:
        i_parser.PrintString("devdesc", "TPM expected less data during FIFO write");
        i_parser.PrintString("moduleid", "TPMDD_WRITEFIFO");
        i_parser.PrintString("reasoncode", "TPM_OVERFLOW_ERROR");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0:31]", "Current byte");
        i_parser.PrintString("userdata2[32:63]", "Buffer Length      (in Bytes)");
        break;

    case 0x270A09:
        i_parser.PrintString("devdesc", "TPM timeout writing to FIFO");
        i_parser.PrintString("moduleid", "TPMDD_WRITEFIFO");
        i_parser.PrintString("reasoncode", "TPM_TIMEOUT");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0:31]", "Current Byte");
        i_parser.PrintString("userdata2[32:63]", "Buffer Length      (in Bytes)");
        break;

    case 0x270909:
        i_parser.PrintString("devdesc", "TPM expected more data during FIFO write");
        i_parser.PrintString("moduleid", "TPMDD_WRITEFIFO");
        i_parser.PrintString("reasoncode", "TPM_UNDERFLOW_ERROR");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0:31]", "Current Byte");
        i_parser.PrintString("userdata2[32:63]", "Buffer Length      (in Bytes)");
        break;

    case 0x27080A:
        i_parser.PrintString("devdesc", "TPM provided more data during FIFO read then buffer space provided");
        i_parser.PrintString("moduleid", "TPMDD_READFIFO");
        i_parser.PrintString("reasoncode", "TPM_OVERFLOW_ERROR");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0:15]", "Operation");
        i_parser.PrintString("userdata2[16:31]", "Current Byte");
        i_parser.PrintString("userdata2[32:63]", "Buffer Length      (in Bytes)");
        break;

    case 0x270A0A:
        i_parser.PrintString("devdesc", "TPM timeout writing to FIFO");
        i_parser.PrintString("moduleid", "TPMDD_READFIFO");
        i_parser.PrintString("reasoncode", "TPM_TIMEOUT");
        i_parser.PrintString("userdata1", "TPM");
        i_parser.PrintString("userdata2[0:15]", "Operation");
        i_parser.PrintString("userdata2[16:31]", "Current Byte");
        i_parser.PrintString("userdata2[32:63]", "Buffer Length      (in Bytes)");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2700, SrcDataParse, ERRL_CID_HOSTBOOT);
