#!/bin/bash

# Automatically generated by Hostboot's ./genErrlParsers.pl
# Do not modify this file in the FSP tree, it is provided by
# Hostboot and will be overwritten
#
#-------------------------------------------------------------
# SRC Parsers
#-------------------------------------------------------------
rm *.o
rm *.a
export OBJECT_MODE=64
g++  -g -std=c++0x -m64  -D__HOSTBOOT_MODULE -DLOGPARSER -I. -I../ -I../targeting -I../../include -I../../include/util -I../../include/extras -I../../include/genfiles  -c *.C

g++ -std=c++0x -m64 -I./prdf -D__AIX -DPRDF_HOSTBOOT_ERRL_PLUGIN -D__HOSTBOOT_MODULE -DLOGPARSER -DPRDPARSER -I../ -I../../include -I../../include/extras -I../../include/genfiles -I../../include/util -c prdf/*.err.C

g++ -std=c++0x -m64 -I./prdf -D__AIX -DPRDF_HOSTBOOT_ERRL_PLUGIN -D__HOSTBOOT_MODULE -DLOGPARSER -DPRDPARSER -I../ -I../../include -I../../include/extras -I../../include/genfiles -I../../include/util -c prdf/*.reg.C

g++ -std=c++0x -m64 -I./prdf -D__AIX -DPRDF_HOSTBOOT_ERRL_PLUGIN -D__HOSTBOOT_MODULE -DLOGPARSER -DPRDPARSER -I../ -I../../include -I../../include/extras -I../../include/genfiles -I../../include/util -c prdf/prdfLogParse.C prdf/prdfLogParse_common.C prdf/prdfMemLogParse.C prdf/prdfProcLogParse.C prdf/prdrErrlPluginsSupt.C prdf/prdfParserUtils.C prdf/prdfBitString.C

ar rvs libhbplugins.a *.o

