/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x190101:
        i_parser.PrintString("devdesc", "ScanDD::scanPerformOp> Invalid ringlength");
        i_parser.PrintString("moduleid", "SCAN::MOD_SCANDD_DDOP");
        i_parser.PrintString("reasoncode", "SCAN::RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "SCAN Ring Address");
        i_parser.PrintString("userdata2", "SCAN ring length");
        break;

    case 0x190201:
        i_parser.PrintString("devdesc", "ScanDD::scanPerformOp> Invalid Ring Address");
        i_parser.PrintString("moduleid", "SCAN::MOD_SCANDD_DDOP");
        i_parser.PrintString("reasoncode", "SCAN::RC_INVALID_RING_ADDRESS");
        i_parser.PrintString("userdata1", "SCAN Ring Address");
        i_parser.PrintString("userdata2", "TARGET");
        break;

    case 0x190401:
        i_parser.PrintString("devdesc", "ScanDD::scanPerformOp> Invalid IObuf length");
        i_parser.PrintString("moduleid", "SCAN::MOD_SCANDD_DDOP");
        i_parser.PrintString("reasoncode", "SCAN::RC_INVALID_BUF_SIZE");
        i_parser.PrintString("userdata1", "SCAN IO buffer length");
        i_parser.PrintString("userdata2", "SCAN ring length");
        break;

    case 0x190301:
        i_parser.PrintString("devdesc", "ScanDD::scanPerformOp> Invalid operation type");
        i_parser.PrintString("moduleid", "SCAN::MOD_SCANDD_DDOP");
        i_parser.PrintString("reasoncode", "SCAN::RC_INVALID_OPERATION");
        i_parser.PrintString("userdata1", "SCAN Address");
        i_parser.PrintString("userdata2", "Operation Type (i_opType)");
        break;

    case 0x190c02:
        i_parser.PrintString("devdesc", "ScanDD::scanDoScan> Got a data mismatch when reading back the header");
        i_parser.PrintString("moduleid", "SCAN::MOD_SCANDD_DOSCAN");
        i_parser.PrintString("reasoncode", "SCAN::RC_HEADER_DATA_MISMATCH");
        i_parser.PrintString("userdata1", "SCAN Ring Address");
        i_parser.PrintString("userdata2", "Operation Type (i_opType)");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1900, SrcDataParse, ERRL_CID_HOSTBOOT);
