/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0xA0105:
        i_parser.PrintString("devdesc", "FsiDD::ddOp> Invalid data length (!= 4,2,1 bytes)");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_DDOP");
        i_parser.PrintString("reasoncode", "FSI::RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "FSI Address");
        i_parser.PrintString("userdata2", "Data Length");
        break;

    case 0xA0905:
        i_parser.PrintString("devdesc", "FsiDD::ddOp> Target is NULL");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_DDOP");
        i_parser.PrintString("reasoncode", "FSI::RC_NULL_TARGET");
        i_parser.PrintString("userdata1", "FSI Address");
        i_parser.PrintString("userdata2", "Operation Type (i_opType) : 0=READ, 1=WRITE");
        break;

    case 0xA0A05:
        i_parser.PrintString("devdesc", "FsiDD::ddOp> Target is unsupported Master Sentinel");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_DDOP");
        i_parser.PrintString("reasoncode", "FSI::RC_MASTER_TARGET");
        i_parser.PrintString("userdata1", "FSI Address");
        i_parser.PrintString("userdata2", "Operation Type (i_opType) : 0=READ, 1=WRITE");
        break;

    case 0xA0805:
        i_parser.PrintString("devdesc", "FsiDD::ddOp> Invalid operation type");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_DDOP");
        i_parser.PrintString("reasoncode", "FSI::RC_INVALID_OPERATION");
        i_parser.PrintString("userdata1", "FSI Address");
        i_parser.PrintString("userdata2", "Operation Type (i_opType)");
        break;

    case 0xA120C:
        i_parser.PrintString("devdesc", "FsiDD::initializeHardware> Unexpected attribute data for remote FSI link");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_INITIALIZEHARDWARE");
        i_parser.PrintString("reasoncode", "FSI::RC_BAD_ATTRIBUTES");
        i_parser.PrintString("userdata1[00:31]", "Slave HUID");
        i_parser.PrintString("userdata1[32:63]", "Slave FSI LinkId");
        i_parser.PrintString("userdata2[00:31]", "Master HUID");
        i_parser.PrintString("userdata2[32:63]", "Master FSI LinkId");
        break;

    case 0xA0404:
        i_parser.PrintString("devdesc", "FsiDD::handleOpbErrors> Error during FSI access");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_HANDLEOPBERRORS");
        i_parser.PrintString("reasoncode", "FSI::RC_OPB_ERROR");
        i_parser.PrintString("userdata1[00:31]", "Relative FSI Address");
        i_parser.PrintString("userdata1[32:63]", "Absolute FSI Address");
        i_parser.PrintString("userdata2[00:31]", "OPB Status Register");
        i_parser.PrintString("userdata2[32:63]", "FSI Master HUID");
        break;

    case 0xA0306:
        i_parser.PrintString("devdesc", "FsiDD::pollForComplete> Error during FSI access");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_POLLFORCOMPLETE");
        i_parser.PrintString("reasoncode", "FSI::RC_OPB_TIMEOUT");
        i_parser.PrintString("userdata1[0:31]", "Relative FSI Address");
        i_parser.PrintString("userdata1[32:63]", "Absolute FSI Address");
        i_parser.PrintString("userdata2", "OPB Status Register");
        break;

    case 0xA0606:
        i_parser.PrintString("devdesc", "FsiDD::pollForComplete> Read valid never came on");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_POLLFORCOMPLETE");
        i_parser.PrintString("reasoncode", "FSI::RC_OPB_NO_READ_VALID");
        i_parser.PrintString("userdata1[0:31]", "Relative FSI Address");
        i_parser.PrintString("userdata1[32:63]", "Absolute FSI Address");
        i_parser.PrintString("userdata2", "OPB Status Register");
        break;

    case 0xA0B09:
        i_parser.PrintString("devdesc", "FsiDD::genFullFsiAddr> Master Type is not supported");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_GENFULLFSIADDR");
        i_parser.PrintString("reasoncode", "FSI::RC_FSI_NOT_SUPPORTED");
        i_parser.PrintString("userdata1", "Target of FSI Operation");
        i_parser.PrintString("userdata2[32:39]", "Physical Node of FSI Master processor");
        i_parser.PrintString("userdata2[40:47]", "Physical Position of FSI Master processor");
        i_parser.PrintString("userdata2[48:55]", "FSI Master type (0=MFSI,1=CMFSI,2=NO_MASTER)");
        i_parser.PrintString("userdata2[56:63]", "Slave link/port number");
        break;

    case 0xA0C09:
        i_parser.PrintString("devdesc", "FsiDD::genFullFsiAddr> Cannot chain 2 masters");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_GENFULLFSIADDR");
        i_parser.PrintString("reasoncode", "FSI::RC_INVALID_FSI_PATH_1");
        i_parser.PrintString("userdata1[0:31]", "Target of FSI Operation");
        i_parser.PrintString("userdata1[32:63]", "Target's FSI Master Chip");
        i_parser.PrintString("userdata2[0:7]", "Physical Node of FSI Master processor  [target's master]");
        i_parser.PrintString("userdata2[8:15]", "Physical Position of FSI Master processor  [target's master]");
        i_parser.PrintString("userdata2[16:23]", "FSI Master type (0=MFSI,1=CMFSI,2=NO_MASTER)  [target's master]");
        i_parser.PrintString("userdata2[24:31]", "Slave link/port number  [target's master]");
        i_parser.PrintString("userdata2[32:39]", "Physical Node of FSI Master processor  [master's master]");
        i_parser.PrintString("userdata2[40:47]", "Physical Position of FSI Master processor  [master's master]");
        i_parser.PrintString("userdata2[48:55]", "FSI Master type (0=MFSI,1=CMFSI,2=NO_MASTER)  [master's master]");
        i_parser.PrintString("userdata2[56:63]", "Slave link/port number  [master's master]");
        break;

    case 0xA0D09:
        i_parser.PrintString("devdesc", "FsiDD::genFullFsiAddr> Invalid master type for the target's master");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_GENFULLFSIADDR");
        i_parser.PrintString("reasoncode", "FSI::RC_INVALID_FSI_PATH_2");
        i_parser.PrintString("userdata1[0:31]", "Target of FSI Operation");
        i_parser.PrintString("userdata1[32:63]", "Target's FSI Master Chip");
        i_parser.PrintString("userdata2[0:7]", "Physical Node of FSI Master processor  [target's master]");
        i_parser.PrintString("userdata2[8:15]", "Physical Position of FSI Master processor  [target's master]");
        i_parser.PrintString("userdata2[16:23]", "FSI Master type (0=MFSI,1=CMFSI,2=NO_MASTER)  [target's master]");
        i_parser.PrintString("userdata2[24:31]", "Slave link/port number  [target's master]");
        i_parser.PrintString("userdata2[32:39]", "Physical Node of FSI Master processor  [master's master]");
        i_parser.PrintString("userdata2[40:47]", "Physical Position of FSI Master processor  [master's master]");
        i_parser.PrintString("userdata2[48:55]", "FSI Master type (0=MFSI,1=CMFSI,2=NO_MASTER)  [master's master]");
        i_parser.PrintString("userdata2[56:63]", "Slave link/port number  [master's master]");
        break;

    case 0xA110A:
        i_parser.PrintString("devdesc", "FsiDD::checkForErrors> Error discovered in MAEB");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_CHECKFORERRORS");
        i_parser.PrintString("reasoncode", "FSI::RC_ERROR_IN_MAEB");
        i_parser.PrintString("userdata1[0:7]", "Physical Node of FSI Master processor");
        i_parser.PrintString("userdata1[8:15]", "Physical Position of FSI Master processor");
        i_parser.PrintString("userdata1[16:23]", "FSI Master type (0=MFSI,1=CMFSI)");
        i_parser.PrintString("userdata1[24:31]", "Slave link/port number");
        i_parser.PrintString("userdata2", "MAEB from master");
        break;

    case 0xA0E0B:
        i_parser.PrintString("devdesc", "FsiDD::verifyPresent> Target was never detected during FSI Init");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIDD_VERIFYPRESENT");
        i_parser.PrintString("reasoncode", "FSI::RC_TARGET_NEVER_DETECTED");
        i_parser.PrintString("userdata1[0:31]", "HUID of Master Proc");
        i_parser.PrintString("userdata1[32:63]", "Detected Slaves");
        i_parser.PrintString("userdata2[0:31]", "HUID of FSI Target");
        i_parser.PrintString("userdata2[32:63]", "HUID of FSI Master");
        break;

    case 0xA0120:
        i_parser.PrintString("devdesc", "presenceDetect> Invalid data length (!= 1 bytes)");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIPRES_PROCPRESENCEDETECT");
        i_parser.PrintString("reasoncode", "FSI::RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "Data Length");
        break;

    case 0xA0F20:
        i_parser.PrintString("devdesc", "presenceDetect> FSI and MVPD do not agree");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIPRES_PROCPRESENCEDETECT");
        i_parser.PrintString("reasoncode", "FSI::RC_FSI_MVPD_MISMATCH");
        i_parser.PrintString("userdata1", "HUID of processor");
        i_parser.PrintString("userdata2[0:31]", "FSI Presence");
        i_parser.PrintString("userdata2[32:63]", "MVPD Presence");
        break;

    case 0xA0121:
        i_parser.PrintString("devdesc", "presenceDetect> Invalid data length (!= 1 bytes)");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIPRES_MEMBPRESENCEDETECT");
        i_parser.PrintString("reasoncode", "FSI::RC_INVALID_LENGTH");
        i_parser.PrintString("userdata1", "Data Length");
        break;

    case 0xA1021:
        i_parser.PrintString("devdesc", "presenceDetect> FSI and CVPD do not agree");
        i_parser.PrintString("moduleid", "FSI::MOD_FSIPRES_MEMBPRESENCEDETECT");
        i_parser.PrintString("reasoncode", "FSI::RC_FSI_CVPD_MISMATCH");
        i_parser.PrintString("userdata1", "HUID of membuffer");
        i_parser.PrintString("userdata2[0:31]", "FSI Presence");
        i_parser.PrintString("userdata2[32:63]", "VPD Presence");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0xA00, SrcDataParse, ERRL_CID_HOSTBOOT);
