/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x220D01:
        i_parser.PrintString("devdesc", "Unsupported Target Type passed in");
        i_parser.PrintString("moduleid", "SBE_FIND_IN_PNOR");
        i_parser.PrintString("reasoncode", "SBE_INVALID_INPUT");
        i_parser.PrintString("userdata1", "Target Unit Id");
        i_parser.PrintString("userdata2", "Target Type");
        break;

    case 0x220701:
        i_parser.PrintString("devdesc", "Unsupported EYE-CATCHER found in TOC");
        i_parser.PrintString("moduleid", "SBE_FIND_IN_PNOR");
        i_parser.PrintString("reasoncode", "SBE_INVALID_EYECATCHER");
        i_parser.PrintString("userdata1", "SBE TOC EYE-CATCHER");
        i_parser.PrintString("userdata2", "Expected EYE-CATCHER");
        break;

    case 0x220601:
        i_parser.PrintString("devdesc", "SBE partition contains unsupported version of Table of Contents");
        i_parser.PrintString("moduleid", "SBE_FIND_IN_PNOR");
        i_parser.PrintString("reasoncode", "SBE_UNSUPPORTED_TOC");
        i_parser.PrintString("userdata1[0:31]", "CHIP EC");
        i_parser.PrintString("userdata1[32:63]", "Expected TOC Version");
        i_parser.PrintString("userdata2[0:31]", "SBE TOC Version");
        i_parser.PrintString("userdata2[32:63]", "SBE TOC EyeCatch");
        break;

    case 0x220801:
        i_parser.PrintString("devdesc", "SBE image for current chip EC was not found in PNOR");
        i_parser.PrintString("moduleid", "SBE_FIND_IN_PNOR");
        i_parser.PrintString("reasoncode", "SBE_EC_NOT_FOUND");
        i_parser.PrintString("userdata1[0:31]", "CHIP EC");
        i_parser.PrintString("userdata1[32:63]", "PNOR Section ID");
        i_parser.PrintString("userdata2[0:31]", "SBE TOC Version");
        i_parser.PrintString("userdata2[32:63]", "SBE TOC EyeCatch");
        break;

    case 0x22110B:
        i_parser.PrintString("devdesc", "Unsuccessful in creating Customized SBE Image");
        i_parser.PrintString("moduleid", "SBE_CUSTOMIZE_IMG");
        i_parser.PrintString("reasoncode", "SBE_P8_XIP_CUSTOMIZE_UNSUCCESSFUL");
        i_parser.PrintString("userdata1[0:31]", "procIOMask in/out parameter");
        i_parser.PrintString("userdata1[32:63]", "rc of procedure");
        i_parser.PrintString("userdata2[0:31]", "coreMask of target");
        i_parser.PrintString("userdata2[32:63]", "coreCount - updated on the loops");
        break;

    case 0x220A03:
        i_parser.PrintString("devdesc", "SB Keyword in MVPD has invalid size");
        i_parser.PrintString("moduleid", "SBE_GETSET_MVPD_VERSION");
        i_parser.PrintString("reasoncode", "SBE_MVPD_LEN_INVALID");
        i_parser.PrintString("userdata1", "Discovered VPD Size");
        i_parser.PrintString("userdata2", "Expected VPD Size");
        break;

    case 0x220B04:
        i_parser.PrintString("devdesc", "Image Version not found in PNOR SBE image.");
        i_parser.PrintString("moduleid", "SBE_READ_PNOR_VERSION");
        i_parser.PrintString("reasoncode", "SBE_VERSION_NOT_FOUND");
        i_parser.PrintString("userdata1", "Not Used");
        i_parser.PrintString("userdata2", "Not Used");
        break;

    case 0x220E08:
        i_parser.PrintString("devdesc", "Invalid Boot SEEPROM Side Found");
        i_parser.PrintString("moduleid", "SBE_GET_TARGET_INFO_STATE");
        i_parser.PrintString("reasoncode", "SBE_INVALID_SEEPROM_SIDE");
        i_parser.PrintString("userdata1", "Temporary Current Side");
        i_parser.PrintString("userdata2", "SBE State Current Side");
        break;

    case 0x220F09:
        i_parser.PrintString("devdesc", "ECC or Data Miscompare Fail Reading Back SBE Verion Information");
        i_parser.PrintString("moduleid", "SBE_GET_SEEPROM_INFO");
        i_parser.PrintString("reasoncode", "SBE_ECC_FAIL");
        i_parser.PrintString("userdata1[0:15]", "ECC Status");
        i_parser.PrintString("userdata1[16:31]", "SEEPROM Side");
        i_parser.PrintString("userdata1[32:47]", "RC on Data Compare with ECC");
        i_parser.PrintString("userdata1[48:63]", "<unused>");
        i_parser.PrintString("userdata2[0:31]", "Size - No Ecc");
        i_parser.PrintString("userdata2[32:63]", "Size - ECC");
        break;

    case 0x220402:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> mm_remove_pages RELEASE failed");
        i_parser.PrintString("moduleid", "SBE_UPDATE_SEEPROMS");
        i_parser.PrintString("reasoncode", "SBE_REMOVE_PAGES_FOR_EC");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_remove_pages");
        break;

    case 0x22100A:
        i_parser.PrintString("devdesc", "Bad Path in decisionUpdateTree: cur=PERM/DIRTY");
        i_parser.PrintString("moduleid", "SBE_DECISION_TREE");
        i_parser.PrintString("reasoncode", "SBE_PERM_SIDE_DIRTY_BAD_PATH");
        i_parser.PrintString("userdata1", "System Situation");
        i_parser.PrintString("userdata2", "Update Actions");
        break;

    case 0x22120C:
        i_parser.PrintString("devdesc", "Successful Update of SBE SEEPROM SBE Verion Information");
        i_parser.PrintString("moduleid", "SBE_PERFORM_UPDATE_ACTIONS");
        i_parser.PrintString("reasoncode", "SBE_INFO_LOG");
        i_parser.PrintString("userdata1[0:31]", "Update Actions Enum");
        i_parser.PrintString("userdata1[32:63]", "Customized Data CRC");
        i_parser.PrintString("userdata2[0:31]", "Original SEEPROM 0 CRC");
        i_parser.PrintString("userdata2[32:63]", "Original SEEPROM 1 CRC");
        break;

    case 0x220106:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> Error from mm_alloc_block");
        i_parser.PrintString("moduleid", "SBE_CREATE_TEST_SPACE");
        i_parser.PrintString("reasoncode", "SBE_ALLOC_BLOCK_FAIL");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_alloc_block");
        break;

    case 0x220206:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> Error from mm_set_permission on creation");
        i_parser.PrintString("moduleid", "SBE_CREATE_TEST_SPACE");
        i_parser.PrintString("reasoncode", "SBE_SET_PERMISSION_FAIL");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_set_permission");
        break;

    case 0x220307:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> mm_remove_pages RELEASE failed");
        i_parser.PrintString("moduleid", "SBE_CLEANUP_TEST_SPACE");
        i_parser.PrintString("reasoncode", "SBE_REMOVE_PAGES_FAIL");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_remove_pages");
        break;

    case 0x220207:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> Error from mm_set_permission on cleanup");
        i_parser.PrintString("moduleid", "SBE_CLEANUP_TEST_SPACE");
        i_parser.PrintString("reasoncode", "SBE_SET_PERMISSION_FAIL");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_set_permission");
        break;

    case 0x22150D:
        i_parser.PrintString("devdesc", "SBE Image Verion Miscompare with Master Target");
        i_parser.PrintString("moduleid", "SBE_MASTER_VERSION_COMPARE");
        i_parser.PrintString("reasoncode", "SBE_MASTER_VERSION_DOWNLEVEL");
        i_parser.PrintString("userdata1", "Master Target HUID");
        i_parser.PrintString("userdata2", "Master Target Loop Index");
        break;

    case 0x22140D:
        i_parser.PrintString("devdesc", "Error Associated with Updating this Target");
        i_parser.PrintString("moduleid", "SBE_MASTER_VERSION_COMPARE");
        i_parser.PrintString("reasoncode", "SBE_ERROR_ON_UPDATE");
        i_parser.PrintString("userdata1[0:31]", "Target HUID");
        i_parser.PrintString("userdata1[32:63]", "Original Error PLID");
        i_parser.PrintString("userdata2[0:31]", "Original Error EID");
        i_parser.PrintString("userdata2[32:63]", "Original Error Reason Code");
        break;

    case 0x22130D:
        i_parser.PrintString("devdesc", "SBE Verion Miscompare with Master Target");
        i_parser.PrintString("moduleid", "SBE_MASTER_VERSION_COMPARE");
        i_parser.PrintString("reasoncode", "SBE_MISCOMPARE_WITH_MASTER_VERSION");
        i_parser.PrintString("userdata1", "Master Target HUID");
        i_parser.PrintString("userdata2", "Comparison Target HUID");
        break;

    case 0x221708:
        i_parser.PrintString("devdesc", "System does not support 2000 MHZ nest frequency required for Low power Turismo");
        i_parser.PrintString("moduleid", "SBE_GET_TARGET_INFO_STATE");
        i_parser.PrintString("reasoncode", "SBE_NO_2000_MHZ_NEST_FREQ_CAP");
        i_parser.PrintString("userdata1", "Processor HUID");
        i_parser.PrintString("userdata2", "MRW nest frequency capabilities");
        break;

    case 0x221808:
        i_parser.PrintString("devdesc", "System not can have mix of low and high power Turismo parts");
        i_parser.PrintString("moduleid", "SBE_GET_TARGET_INFO_STATE");
        i_parser.PrintString("reasoncode", "SBE_INCONSISTENT_NEST_FREQ");
        i_parser.PrintString("userdata1", "Processor HUID");
        break;

    case 0x221612:
        i_parser.PrintString("devdesc", "sbe_xip_get/set_scalar() failed when accessing the HBB Address MMIO offset in 'standalone_mbox2_value'");
        i_parser.PrintString("moduleid", "SBE_FIXUP_GOLDEN_HBB");
        i_parser.PrintString("reasoncode", "SBE_IMAGE_GET_SET_SCALAR_FAIL");
        i_parser.PrintString("userdata1", "Return Code of failed operation");
        break;

    case 0x22040F:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> mm_remove_pages RELEASE failed");
        i_parser.PrintString("moduleid", "SBE_READ_SBE_IMAGE");
        i_parser.PrintString("reasoncode", "SBE_REMOVE_PAGES_FOR_EC");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_remove_pages");
        break;

    case 0x220F0F:
        i_parser.PrintString("devdesc", "ECC Fail Reading SBE Image");
        i_parser.PrintString("moduleid", "SBE_READ_SBE_IMAGE");
        i_parser.PrintString("reasoncode", "SBE_ECC_FAIL");
        i_parser.PrintString("userdata1[0:15]", "ECC Status");
        i_parser.PrintString("userdata1[16:31]", "SEEPROM Side");
        i_parser.PrintString("userdata1[32:63]", "Target HUID");
        i_parser.PrintString("userdata2[0:31]", "Size - No Ecc");
        i_parser.PrintString("userdata2[32:63]", "Size - ECC");
        break;

    case 0x220410:
        i_parser.PrintString("devdesc", "updateProcessorSbeSeeproms> mm_remove_pages RELEASE failed");
        i_parser.PrintString("moduleid", "SBE_WRITE_SBE_IMAGE");
        i_parser.PrintString("reasoncode", "SBE_REMOVE_PAGES_FOR_EC");
        i_parser.PrintString("userdata1", "Requested Address");
        i_parser.PrintString("userdata2", "rc from mm_remove_pages");
        break;

    case 0x220F11:
        i_parser.PrintString("devdesc", "ECC Fail Reading SBE Image");
        i_parser.PrintString("moduleid", "SBE_GET_SBE_IMAGE_SIZE");
        i_parser.PrintString("reasoncode", "SBE_ECC_FAIL");
        i_parser.PrintString("userdata1[0:15]", "ECC Status");
        i_parser.PrintString("userdata1[16:31]", "SEEPROM Side");
        i_parser.PrintString("userdata1[32:63]", "Target HUID");
        i_parser.PrintString("userdata2[0:31]", "Size - No Ecc");
        i_parser.PrintString("userdata2[32:63]", "Size - ECC");
        break;

    case 0x22160E:
        i_parser.PrintString("devdesc", "sbe_xip_get/set_scalar() failed when accessing the                          HBB Address MMIO offset in 'standalone_mbox2_value'");
        i_parser.PrintString("moduleid", "SBE_RESOLVE_HBB_ADDR");
        i_parser.PrintString("reasoncode", "SBE_IMAGE_GET_SET_SCALAR_FAIL");
        i_parser.PrintString("userdata1", "Return Code of failed operation");
        i_parser.PrintString("userdata2", "True/False if Get (true) or Set (false) Op failed");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2200, SrcDataParse, ERRL_CID_HOSTBOOT);
