/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x9170D:
        i_parser.PrintString("devdesc", "NULL TARG Target passed to attribute access macro");
        i_parser.PrintString("moduleid", "MOD_ATTR_GET_TARGETING_TARGET");
        i_parser.PrintString("reasoncode", "RC_EMBEDDED_NULL_TARGET_PTR");
        break;

    case 0x91C0D:
        i_parser.PrintString("devdesc", "Unexpected Target Type passed to attribute access macro");
        i_parser.PrintString("moduleid", "MOD_ATTR_GET_TARGETING_TARGET");
        i_parser.PrintString("reasoncode", "RC_UNEXPECTED_TARGET_TYPE");
        i_parser.PrintString("userdata1", "Target Type");
        i_parser.PrintString("userdata2", "Expected Target Type");
        break;

    case 0x91305:
        i_parser.PrintString("devdesc", "Failed to get requested attribute. Possible causes: Invalid target, attribute not implemented, attribute not present on given target, target service not initialized");
        i_parser.PrintString("moduleid", "MOD_PLAT_ATTR_SVC_GET_TARG_ATTR");
        i_parser.PrintString("reasoncode", "RC_FAILED_TO_ACCESS_ATTRIBUTE");
        i_parser.PrintString("userdata1", "Platform attribute ID");
        i_parser.PrintString("userdata2", "FAPI target type, or NULL if system target");
        break;

    case 0x91306:
        i_parser.PrintString("devdesc", "Failed to Set requested attribute. Possible causes: Invalid target, attribute not implemented, attribute not present on given target, target service not initialized");
        i_parser.PrintString("moduleid", "MOD_PLAT_ATTR_SVC_SET_TARG_ATTR");
        i_parser.PrintString("reasoncode", "RC_FAILED_TO_ACCESS_ATTRIBUTE");
        i_parser.PrintString("userdata1", "Platform attribute ID");
        i_parser.PrintString("userdata2", "FAPI target type, or NULL if system target");
        break;

    case 0x92927:
        i_parser.PrintString("devdesc", "fapiPlatGetVpdVersion could not find the expected 1 mba from the passed dimm target");
        i_parser.PrintString("moduleid", "fapi::MOD_PLAT_ATTR_SVC_CEN_DQ_TO_DIMM_CONN_DQ");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_MBA");
        i_parser.PrintString("userdata1", "Number of MBAs");
        i_parser.PrintString("userdata2", "DIMM HUID");
        break;

    case 0x9150E:
        i_parser.PrintString("devdesc", "Failed to get the FAPI Target name due to unrecognized TARGETING Target model");
        i_parser.PrintString("moduleid", "MOD_ATTR_GET_TARGET_NAME");
        i_parser.PrintString("reasoncode", "RC_ATTR_BAD_TARGET_PARAM");
        i_parser.PrintString("userdata1", "TARGETING Target model");
        break;

    case 0x92918:
        i_parser.PrintString("devdesc", "fapiPlatGetVpdVersion could not find the expected 1 mba from the passed dimm target");
        i_parser.PrintString("moduleid", "fapi::MOD_PLAT_ATTR_SVC_GET_VPD_VERSION");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_MBA");
        i_parser.PrintString("userdata1", "Number of MBAs");
        i_parser.PrintString("userdata2", "DIMM HUID");
        break;

    case 0x9291A:
        i_parser.PrintString("devdesc", "fapiPlatDimmGetBadDqBitmap could not find the expected 1 mba from the passed dimm target");
        i_parser.PrintString("moduleid", "fapi::MOD_PLAT_ATTR_SVC_GET_BADDQ_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_MBA");
        i_parser.PrintString("userdata1", "Number of MBAs");
        i_parser.PrintString("userdata2", "DIMM HUID");
        break;

    case 0x9291B:
        i_parser.PrintString("devdesc", "fapiPlatDimmSetBadDqBitmap could not find the expected 1 mba from the passed dimm target");
        i_parser.PrintString("moduleid", "fapi::MOD_PLAT_ATTR_SVC_SET_BADDQ_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_MBA");
        i_parser.PrintString("userdata1", "Number of MBAs");
        i_parser.PrintString("userdata2", "DIMM HUID");
        break;

    case 0x93322:
        i_parser.PrintString("devdesc", "Failed due to wrong DIMM type");
        i_parser.PrintString("moduleid", "MOD_GET_RCD_CNTL_WORD");
        i_parser.PrintString("reasoncode", "RC_INVALID_DIMM_TYPE");
        i_parser.PrintString("userdata1", "DIMM TYPE");
        break;

    case 0x93A28:
        i_parser.PrintString("devdesc", "fapiPlatGetNodeMemAttrData could not find the single node associated with this membuf target");
        i_parser.PrintString("moduleid", "MOD_PLAT_ATTR_SVC_GET_MEM_ATTR_DATA");
        i_parser.PrintString("reasoncode", "RC_NO_SINGLE_NODE");
        i_parser.PrintString("userdata1", "Number of Nodes");
        i_parser.PrintString("userdata2", "MEMBUF Target HUID");
        break;

    case 0x91328:
        i_parser.PrintString("devdesc", "Failed to get requested attribute. Possible causes: Invalid target, attribute not implemented, attribute not present on given target, target service not initialized");
        i_parser.PrintString("moduleid", "MOD_PLAT_ATTR_SVC_GET_MEM_ATTR_DATA");
        i_parser.PrintString("reasoncode", "RC_FAILED_TO_ACCESS_ATTRIBUTE");
        i_parser.PrintString("userdata1[0:31]", "Platform attribute ID");
        i_parser.PrintString("userdata1[32:64]", "MEMBUF Target");
        i_parser.PrintString("userdata2", "FAPI target type, or NULL if system target");
        break;

    case 0x90f02:
        i_parser.PrintString("devdesc", "HW Procedure generated error. See User Data.");
        i_parser.PrintString("moduleid", "MOD_HWP_RC_TO_ERRL");
        i_parser.PrintString("reasoncode", "RC_HWP_GENERATED_ERROR");
        i_parser.PrintString("userdata1", "RC value from HWP");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x91712:
        i_parser.PrintString("devdesc", "Target has embedded null target pointer");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_OTHER_SIDE_OF_MEM_CHANNEL");
        i_parser.PrintString("reasoncode", "fapi::RC_EMBEDDED_NULL_TARGET_PTR");
        break;

    case 0x92212:
        i_parser.PrintString("devdesc", "fapiGetOtherSideOfMemChannel could not find exactly one target on the other side of the correct state");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_OTHER_SIDE_OF_MEM_CHANNEL");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_MEMBUFF");
        i_parser.PrintString("userdata1", "Number of Memory Buffers");
        i_parser.PrintString("userdata2", "MCS HUID");
        break;

    case 0x92112:
        i_parser.PrintString("devdesc", "fapiGetOtherSideOfMemChannel could not find exactly one target on the other side of the correct state");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_OTHER_SIDE_OF_MEM_CHANNEL");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_MCS");
        i_parser.PrintString("userdata1", "Number of MCSs");
        i_parser.PrintString("userdata2", "Membuf HUID");
        break;

    case 0x91112:
        i_parser.PrintString("devdesc", "fapiGetOtherSideOfMemChannel request for unsupported or invalid target type");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_OTHER_SIDE_OF_MEM_CHANNEL");
        i_parser.PrintString("reasoncode", "fapi::RC_UNSUPPORTED_REQUEST");
        i_parser.PrintString("userdata1", "Requested type");
        i_parser.PrintString("userdata2", "Unsupported Target HUID");
        break;

    case 0x92312:
        i_parser.PrintString("devdesc", "fapiGetOtherSideOfMemChannel target not present or functional as requested");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_OTHER_SIDE_OF_MEM_CHANNEL");
        i_parser.PrintString("reasoncode", "fapi::RC_STATE_MISMATCH");
        i_parser.PrintString("userdata1", "Requested state");
        i_parser.PrintString("userdata2", "Other Target HUID");
        break;

    case 0x91003:
        i_parser.PrintString("devdesc", "fapiGetChildChiplets request for non-chip");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_CHILD_CHIPLETS");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_REQUEST");
        i_parser.PrintString("userdata1", "Type of input target");
        i_parser.PrintString("userdata2", "Input Target HUID");
        break;

    case 0x91103:
        i_parser.PrintString("devdesc", "fapiGetChildChiplets request for unsupported or invalid chiplet type");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_CHILD_CHIPLETS");
        i_parser.PrintString("reasoncode", "fapi::RC_UNSUPPORTED_REQUEST");
        i_parser.PrintString("userdata1", "Type of requested chiplet");
        i_parser.PrintString("userdata2", "Input Chip Target HUID");
        break;

    case 0x91703:
        i_parser.PrintString("devdesc", "Target has embedded null target pointer");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_CHILD_CHIPLETS");
        i_parser.PrintString("reasoncode", "fapi::RC_EMBEDDED_NULL_TARGET_PTR");
        break;

    case 0x9170A:
        i_parser.PrintString("devdesc", "Target has embedded null target pointer");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_ASSOCIATE_DIMMS");
        i_parser.PrintString("reasoncode", "fapi::RC_EMBEDDED_NULL_TARGET_PTR");
        break;

    case 0x91004:
        i_parser.PrintString("devdesc", "fapiGetParentChip request for non-chiplet");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_PARENT_CHIP");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_REQUEST");
        i_parser.PrintString("userdata1", "Type of input target");
        i_parser.PrintString("userdata2", "Input Target HUID");
        break;

    case 0x91704:
        i_parser.PrintString("devdesc", "Target has embedded null target pointer");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_PARENT_CHIP");
        i_parser.PrintString("reasoncode", "fapi::RC_EMBEDDED_NULL_TARGET_PTR");
        break;

    case 0x91204:
        i_parser.PrintString("devdesc", "fapiGetParentChip did not find one parent");
        i_parser.PrintString("moduleid", "fapi::MOD_FAPI_GET_PARENT_CHIP");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_SINGLE_PARENT");
        i_parser.PrintString("userdata1", "Input Chiplet Target HUID");
        break;

    case 0x92C1D:
        i_parser.PrintString("devdesc", "Override message received from HWSV contains NULL data pointer");
        i_parser.PrintString("moduleid", "fapi::MOD_ATTR_OVERRIDE");
        i_parser.PrintString("reasoncode", "fapi::RC_NULL_POINTER");
        i_parser.PrintString("userdata1", "Attribute Tank (FAPI/TARG)");
        i_parser.PrintString("userdata2", "Size of attribute overrides");
        break;

    case 0x92D1E:
        i_parser.PrintString("devdesc", "Error code from hypervisor wakeup call");
        i_parser.PrintString("moduleid", "fapi::MOD_PLAT_SPECIAL_WAKEUP");
        i_parser.PrintString("reasoncode", "fapi::RC_RT_WAKEUP_FAILED");
        i_parser.PrintString("userdata1", "Hypervisor return code");
        i_parser.PrintString("userdata2", "Chiplet HUID");
        break;

    case 0x91D13:
        i_parser.PrintString("devdesc", "Attempt to read an MVPD field using an invalid record");
        i_parser.PrintString("moduleid", "MOD_MBVPD_ACCESS");
        i_parser.PrintString("reasoncode", "RC_INVALID_RECORD");
        i_parser.PrintString("userdata1", "Record enumerator");
        break;

    case 0x91E13:
        i_parser.PrintString("devdesc", "Attempt to read an MVPD field using an invalid keyword");
        i_parser.PrintString("moduleid", "MOD_MBVPD_ACCESS");
        i_parser.PrintString("reasoncode", "RC_INVALID_KEYWORD");
        i_parser.PrintString("userdata1", "Keyword enumerator");
        break;

    case 0x91407:
        i_parser.PrintString("devdesc", "Attempt to access CFAM register on the master processor chip");
        i_parser.PrintString("moduleid", "fapi::MOD_VERIFY_CFAM_ACCESS_TARGET");
        i_parser.PrintString("reasoncode", "fapi::RC_CFAM_ACCESS_ON_PROC_ERR");
        i_parser.PrintString("userdata1", "Target HUID");
        i_parser.PrintString("userdata2", "CFAM address being accessed");
        break;

    case 0x91609:
        i_parser.PrintString("devdesc", "Invalid num of parent chip found for input CFAM target chiplet");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_CFAM_CHIP_TARGET");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_NUM_PARENT_CHIP");
        i_parser.PrintString("userdata1", "Number of parent chip found");
        i_parser.PrintString("userdata2", "Chiplet HUID");
        break;

    case 0x91D0F:
        i_parser.PrintString("devdesc", "Attempt to read an MVPD field using an invalid record");
        i_parser.PrintString("moduleid", "MOD_MVPD_ACCESS");
        i_parser.PrintString("reasoncode", "RC_INVALID_RECORD");
        i_parser.PrintString("userdata1", "Record enumerator");
        break;

    case 0x91E0F:
        i_parser.PrintString("devdesc", "Attempt to read an MVPD field using an invalid keyword");
        i_parser.PrintString("moduleid", "MOD_MVPD_ACCESS");
        i_parser.PrintString("reasoncode", "RC_INVALID_KEYWORD");
        i_parser.PrintString("userdata1", "Keyword enumerator");
        break;

    case 0x93526:
        i_parser.PrintString("devdesc", "Input buffer size is smaller than expected length.");
        i_parser.PrintString("moduleid", "fapi::MOD_PLAT_MVPD_GET_VLTG_BUCKET_ATTR");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_SIZE");
        i_parser.PrintString("userdata1", "Invalid input length");
        i_parser.PrintString("userdata2", "Expected length");
        break;

    case 0x93725:
        i_parser.PrintString("devdesc", "Invalid bucket id found for the voltage data.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_VER_ONE_VOLTAGE_BUCKET_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_PARAM");
        i_parser.PrintString("userdata1", "Invalid bucket id");
        break;

    case 0x93525:
        i_parser.PrintString("devdesc", "Not enough voltage data to read bucket data.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_VER_ONE_VOLTAGE_BUCKET_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_SIZE");
        i_parser.PrintString("userdata1", "Voltage data length");
        i_parser.PrintString("userdata2", "Expected length");
        break;

    case 0x93825:
        i_parser.PrintString("devdesc", "Bucket id from PR keyword does not match bucket id in the voltage data");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_VER_ONE_VOLTAGE_BUCKET_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_DATA_MISMATCH");
        i_parser.PrintString("userdata1[0:31]", "Voltage bucket id");
        i_parser.PrintString("userdata1[32:63]", "PR bucket id");
        i_parser.PrintString("userdata2", "Voltage bucket id offset");
        break;

    case 0x93425:
        i_parser.PrintString("devdesc", "Not enough bucket data to fill output data.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_VER_ONE_VOLTAGE_BUCKET_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_DATA");
        i_parser.PrintString("userdata1", "Bucket data length");
        i_parser.PrintString("userdata2", "Output Data size");
        break;

    case 0x93924:
        i_parser.PrintString("devdesc", "Unsupported #V keyword data version found.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_POUNDV_BUCKET_DATA");
        i_parser.PrintString("reasoncode", "fapi::RC_DATA_NOT_SUPPORTED");
        i_parser.PrintString("userdata1[0:31]", "Unsupported version");
        i_parser.PrintString("userdata1[32:63]", "Expected version");
        i_parser.PrintString("userdata2", "#V KW data size");
        break;

    case 0x9180B:
        i_parser.PrintString("devdesc", "Platform generated error. See User Data.");
        i_parser.PrintString("moduleid", "MOD_EDI_EI_IO_RUN_TRAINING");
        i_parser.PrintString("reasoncode", "RC_MIXED_PBUS_CONNECTION");
        i_parser.PrintString("userdata1", "Endpoint1 bus type");
        i_parser.PrintString("userdata2", "Endpoint2 bus type");
        break;

    case 0x9190B:
        i_parser.PrintString("devdesc", "Platform generated error.");
        i_parser.PrintString("moduleid", "MOD_EDI_EI_IO_RUN_TRAINING");
        i_parser.PrintString("reasoncode", "RC_SAME_CHIP_PBUS_CONNECTION");
        break;

    case 0x91A0B:
        i_parser.PrintString("devdesc", "Platform generated error. See User Data.");
        i_parser.PrintString("moduleid", "MOD_EDI_EI_IO_RUN_TRAINING");
        i_parser.PrintString("reasoncode", "RC_CONFLICT_PBUS_CONNECTION");
        i_parser.PrintString("userdata1", "Bus endpoint target pointer1");
        i_parser.PrintString("userdata2", "Bus endpoint target pointer2");
        break;

    case 0x92817:
        i_parser.PrintString("devdesc", "HB got an incorrect type message.  HB did not provide the correct message type in the istep. Userdata1 shows the message type passed in");
        i_parser.PrintString("moduleid", "fapi::MOD_VDDR_SEND_MSG");
        i_parser.PrintString("reasoncode", "fapi::RC_INCORRECT_MSG_TYPE");
        i_parser.PrintString("userdata1", "i_msgType");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x92516:
        i_parser.PrintString("devdesc", "The hwsv returned a message where the extra data was null.  This should not happen so need to tell HostBoot to stop the ipl");
        i_parser.PrintString("moduleid", "fapi::MOD_VDDR_PROC_VDDR_MSG");
        i_parser.PrintString("reasoncode", "fapi::RC_VDDR_EMPTY_MSG");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x92716:
        i_parser.PrintString("devdesc", "The hwsv returned a message where there was an error when the powr function was called. userdata1 contains the errorlog plid from hwsv generated by the powr function");
        i_parser.PrintString("moduleid", "fapi::MOD_VDDR_PROC_VDDR_MSG");
        i_parser.PrintString("reasoncode", "fapi::RC_VDDR_POWR_ERR");
        i_parser.PrintString("userdata1", "l_errPlid");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x92815:
        i_parser.PrintString("devdesc", "HB got an incorrect type message. HWSV did not populate the message correctly or mbox corrupted the message");
        i_parser.PrintString("moduleid", "fapi::MOD_VDDR_PROC_MSG");
        i_parser.PrintString("reasoncode", "fapi::RC_INCORRECT_MSG_TYPE");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x92615:
        i_parser.PrintString("devdesc", "The hwsv found an error while processing the message so it sent an error message back to indicate to HostBoot to stop the IPL. Userdata1 will have the error PLID from hwsv's errorlog");
        i_parser.PrintString("moduleid", "fapi::MOD_VDDR_PROC_MSG");
        i_parser.PrintString("reasoncode", "fapi::RC_VDDR_ERROR_MSG");
        i_parser.PrintString("userdata1", "error PLID from hwsv");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x9362B:
        i_parser.PrintString("devdesc", "Invalid nest frequency found for given membuf");
        i_parser.PrintString("moduleid", "MOD_FIND_MIN_DMI_SPD");
        i_parser.PrintString("reasoncode", "RC_INVALID_FREQ");
        i_parser.PrintString("userdata1", "HUID of membuf");
        i_parser.PrintString("userdata2", "[0:7] membuf frequency enumeration value");
        i_parser.PrintString("userdata2", "[8:15] dmi bus speed enumeration value");
        break;

    case 0x9362A:
        i_parser.PrintString("devdesc", "Invalid nest found for given membuf");
        i_parser.PrintString("moduleid", "MOD_SET_NEST_FREQ");
        i_parser.PrintString("reasoncode", "RC_INVALID_FREQ");
        i_parser.PrintString("userdata1", "HUID of membuf");
        i_parser.PrintString("userdata2", "[0:7] membuf frequency enumeration value");
        i_parser.PrintString("userdata2", "[8:15] dmi bus speed enumeration value");
        break;

    case 0x92A1C:
        i_parser.PrintString("devdesc", "messages from other nodes have not returned in time");
        i_parser.PrintString("moduleid", "fapi::MOD_HOST_COALESCE_HOST,");
        i_parser.PrintString("reasoncode", "fapi::RC_HOST_TIMER_EXPIRED,");
        i_parser.PrintString("userdata1", "MAX_TIME_ALLOWED_MS");
        i_parser.PrintString("userdata2", "Number of nodes that have not responded");
        break;

    case 0x92B1C:
        i_parser.PrintString("devdesc", "host coalesce host timer thread failed");
        i_parser.PrintString("moduleid", "fapi::MOD_HOST_COALESCE_HOST,");
        i_parser.PrintString("reasoncode", "fapi::RC_HOST_TIMER_THREAD_FAIL,,");
        i_parser.PrintString("userdata1", "l_tidretrc,");
        i_parser.PrintString("userdata2", "l_childsts,");
        break;

    case 0x93E2D:
        i_parser.PrintString("devdesc", "xz-embedded has returned an error. the return code can be found in xz.h");
        i_parser.PrintString("moduleid", "fapi::MOD_START_XZ_PAYLOAD");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_RETURN_XZ_CODE");
        i_parser.PrintString("userdata1", "Return code from xz-embedded");
        i_parser.PrintString("userdata2[0:31]", "Original Payload Size");
        i_parser.PrintString("userdata2[32:63]", "Uncompressed Payload Size");
        break;

    case 0x93C29:
        i_parser.PrintString("devdesc", "When WOF is enabled, the WOF Freq Uplift index must be within range of the number of rows in the frequency uplift table. 0=not found.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_WOF_FREQ_UPLIFT_SELECTED");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_WOF_INDEX");
        i_parser.PrintString("userdata1[0:31]", "Proc HUID");
        i_parser.PrintString("userdata1[32:63]", "WOF Freq Uplift Index");
        i_parser.PrintString("userdata2[0:31]", "Number of active cores");
        i_parser.PrintString("userdata2[32:63]", "Nomimal Frequency");
        break;

    case 0x93423:
        i_parser.PrintString("devdesc", "Either nominal, max turbo or min power save frequency for the processor HUID (userdata1) is zero");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_SYS_FREQ");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_DATA");
        i_parser.PrintString("userdata1[0:31]", "Proc HUID");
        i_parser.PrintString("userdata1[32:63]", "Nominal frequency");
        i_parser.PrintString("userdata2[0:31]", "Max Turbo frequency from VPD");
        i_parser.PrintString("userdata2[32:63]", "Min Power Save frequency from VPD");
        break;

    case 0x93B23:
        i_parser.PrintString("devdesc", "When WOF is enabled, ultra turbo freq should not be 0");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_SYS_FREQ");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_ULTRA_TURBO_FREQ");
        i_parser.PrintString("userdata1", "Proc HUID");
        i_parser.PrintString("userdata2", "Invalid ultra turbo frequency");
        break;

    case 0x93623:
        i_parser.PrintString("devdesc", "Nominal frequency(userdata1) does not match nominal frequency(userdata2) on other cores. Should be the same for all chips.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_SYS_FREQ");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_FREQ");
        i_parser.PrintString("userdata1", "Invalid frequency");
        i_parser.PrintString("userdata2", "Expected frequency");
        break;

    case 0x92E10:
        i_parser.PrintString("devdesc", "Request given to load payload into mirrored memory, but no mirrored memory exists at that location.");
        i_parser.PrintString("moduleid", "fapi::MOD_EXIT_CACHE_CONTAINED,");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_MIRRORED_MEMORY,");
        i_parser.PrintString("userdata1", "Mirrored Memory Address");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x91F10:
        i_parser.PrintString("devdesc", "Failure extending memory to 32MEG after exiting cache contained mode.");
        i_parser.PrintString("moduleid", "fapi::MOD_EXIT_CACHE_CONTAINED");
        i_parser.PrintString("reasoncode", "fapi::RC_MM_EXTEND_FAILED");
        i_parser.PrintString("userdata1", "rc from mm_extend");
        i_parser.PrintString("userdata2", "<UNUSED>");
        break;

    case 0x91D11:
        i_parser.PrintString("devdesc", "getCacheDeconfig> Master core is not mapped to a LRPx Module VPD Record.");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_CACHE_DECONFIG");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_RECORD");
        i_parser.PrintString("userdata1", "Master Core Number");
        i_parser.PrintString("userdata2", "Master processor chip huid");
        break;

    case 0x92011:
        i_parser.PrintString("devdesc", "getCacheDeconfig> LRPx Record, CH keyword is incorrect size");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_CACHE_DECONFIG");
        i_parser.PrintString("reasoncode", "fapi::RC_INCORRECT_KEWORD_SIZE");
        i_parser.PrintString("userdata1", "Master Core Number");
        i_parser.PrintString("userdata2", "CH Keyword Size");
        break;

    case 0x91B0C:
        i_parser.PrintString("devdesc", "activate_threads> Could not find a target for the master core");
        i_parser.PrintString("moduleid", "fapi::MOD_THREAD_ACTIVATE");
        i_parser.PrintString("reasoncode", "fapi::RC_NO_MASTER_CORE_TARGET");
        i_parser.PrintString("userdata1", "Master cpu id (NNNCCCPPPPTTT)");
        i_parser.PrintString("userdata2", "Master processor chip huid");
        break;

    case 0x93120:
        i_parser.PrintString("devdesc", "PROC or OCC expected");
        i_parser.PrintString("moduleid", "fapi::MOD_GET_OCC_CHIP_TARGET");
        i_parser.PrintString("reasoncode", "fapi::RC_TARGET_UNSUPPORTED");
        i_parser.PrintString("userdata1", "Target Type");
        i_parser.PrintString("userdata2", "Target HUID");
        break;

    case 0x93221:
        i_parser.PrintString("devdesc", "Improper data size, data is not 8 byte aligned.");
        i_parser.PrintString("moduleid", "fapi::MOD_ACCESS_OCB_INDIRECT_CHANNEL");
        i_parser.PrintString("reasoncode", "fapi::RC_INVALID_DATA_BUFFER_LENGTH");
        i_parser.PrintString("userdata1", "Length of requested buffer size(in Bytes) to perform read operation.");
        i_parser.PrintString("userdata2", "OCI address");
        break;

    case 0x93D2C:
        i_parser.PrintString("devdesc", "ecmd insert failed for l_occFirData");
        i_parser.PrintString("moduleid", "fapi::MOD_OCC_LOAD_HOST_DATA_TO_SRAM");
        i_parser.PrintString("reasoncode", "fapi::RC_ECMD_INSERT_FAILED");
        i_parser.PrintString("userdata1", "Return Code");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x92414:
        i_parser.PrintString("devdesc", "mm_block_unmap() returns error");
        i_parser.PrintString("moduleid", "fapi::MOD_OCC_LOAD_START_ALL_OCCS");
        i_parser.PrintString("reasoncode", "fapi::RC_MM_UNMAP_ERR");
        i_parser.PrintString("userdata1", "Return Code");
        i_parser.PrintString("userdata2", "Unmap address");
        break;

    case 0x90101:
        i_parser.PrintString("devdesc", "InitFile HW Procedure requested an invalid attribute");
        i_parser.PrintString("moduleid", "MOD_FAPI_RC_TO_ERRL");
        i_parser.PrintString("reasoncode", "RC_INVALID_ATTR_GET");
        break;

    case 0x90201:
        i_parser.PrintString("devdesc", "Request for EC features on an attribute without EC features");
        i_parser.PrintString("moduleid", "MOD_FAPI_RC_TO_ERRL");
        i_parser.PrintString("reasoncode", "RC_INVALID_CHIP_EC_FEATURE_GET");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x900, SrcDataParse, ERRL_CID_HOSTBOOT);
