/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x1C0702:
        i_parser.PrintString("devdesc", "The provided address is over 32 bits long which makes it invalid.");
        i_parser.PrintString("moduleid", "IBSCOM_SANITY_CHECK");
        i_parser.PrintString("reasoncode", "IBSCOM_INVALID_ADDRESS");
        i_parser.PrintString("userdata1", "Inband Scom  address");
        i_parser.PrintString("userdata2", "<none>");
        break;

    case 0x1C0102:
        i_parser.PrintString("devdesc", "Inband  buffer size < 8 bytes or NULL data buffer");
        i_parser.PrintString("moduleid", "IBSCOM_SANITY_CHECK");
        i_parser.PrintString("reasoncode", "IBSCOM_INVALID_DATA_BUFFER");
        i_parser.PrintString("userdata1", "Buffer size");
        i_parser.PrintString("userdata2", "Inband Scom  address");
        break;

    case 0x1C0202:
        i_parser.PrintString("devdesc", "inband scom invalid operation type");
        i_parser.PrintString("moduleid", "IBSCOM_SANITY_CHECK");
        i_parser.PrintString("reasoncode", "IBSCOM_INVALID_OP_TYPE");
        i_parser.PrintString("userdata1", "Operation type");
        i_parser.PrintString("userdata2", "inband scom address");
        break;

    case 0x1C0303:
        i_parser.PrintString("devdesc", "System configuration does not have a Parent MCS for the current centaur.");
        i_parser.PrintString("moduleid", "IBSCOM_GET_TARG_VIRT_ADDR");
        i_parser.PrintString("reasoncode", "IBSCOM_INVALID_CONFIG");
        i_parser.PrintString("userdata1[0:31]", "HUID of Centaur Target");
        i_parser.PrintString("userdata2", "Not Used");
        break;

    case 0x1C0A04:
        i_parser.PrintString("devdesc", "Previous error disabled ibscom, so forcing a retry via FSI");
        i_parser.PrintString("moduleid", "IBSCOM_DO_IBSCOM");
        i_parser.PrintString("reasoncode", "IBSCOM_RETRY_DUE_TO_ERROR");
        i_parser.PrintString("userdata1[0:31]", "HUID of Centaur Target");
        i_parser.PrintString("userdata1[32:64]", "SCOM Address");
        i_parser.PrintString("userdata2", "Not Used");
        break;

    case 0x1C0504:
        i_parser.PrintString("devdesc", "SUE Encountered when collecting IBSCOM Error Data");
        i_parser.PrintString("moduleid", "IBSCOM_DO_IBSCOM");
        i_parser.PrintString("reasoncode", "IBSCOM_SUE_IN_ERR_PATH");
        i_parser.PrintString("userdata1[0:31]", "HUID of Centaur Target");
        i_parser.PrintString("userdata1[32:64]", "SCOM Address");
        i_parser.PrintString("userdata2", "Not Used");
        break;

    case 0x1C0904:
        i_parser.PrintString("devdesc", "Detected error doesn't match the address we failed on");
        i_parser.PrintString("moduleid", "IBSCOM_DO_IBSCOM");
        i_parser.PrintString("reasoncode", "IBSCOM_WRONG_ERROR");
        i_parser.PrintString("userdata1[0:31]", "HUID of Centaur Target");
        i_parser.PrintString("userdata1[32:64]", "SCOM Address");
        i_parser.PrintString("userdata2", "Contents of MBSIBERR0 register");
        break;

    case 0x1C0604:
        i_parser.PrintString("devdesc", "Bus failure when attempting to perform IBSCOM operation.  IBSCOM disabled.");
        i_parser.PrintString("moduleid", "IBSCOM_DO_IBSCOM");
        i_parser.PrintString("reasoncode", "IBSCOM_BUS_FAILURE");
        i_parser.PrintString("userdata1[0:31]", "HUID of Centaur Target");
        i_parser.PrintString("userdata1[32:64]", "SCOM Address");
        i_parser.PrintString("userdata2", "Contents of MBSIBERR0 register");
        break;

    case 0x1C0804:
        i_parser.PrintString("devdesc", "PIB error when attempting to perform IBSCOM operation.");
        i_parser.PrintString("moduleid", "IBSCOM_DO_IBSCOM");
        i_parser.PrintString("reasoncode", "IBSCOM_PIB_FAILURE");
        i_parser.PrintString("userdata1[0:31]", "HUID of Centaur Target");
        i_parser.PrintString("userdata1[32:64]", "SCOM Address");
        i_parser.PrintString("userdata2", "Contents of MBSIBERR0 register");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1C00, SrcDataParse, ERRL_CID_HOSTBOOT);
