/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x30504:
        i_parser.PrintString("devdesc", "Indirect SCOM Read error");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_READ_FAIL");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30604:
        i_parser.PrintString("devdesc", "Indirect SCOM complete bit did not come on");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_READ_TIMEOUT");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30704:
        i_parser.PrintString("devdesc", "Indirect SCOM Write failed for this address");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_WRITE_FAIL");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30804:
        i_parser.PrintString("devdesc", "Indirect SCOM complete bit did not come on");
        i_parser.PrintString("moduleid", "SCOM::SCOM_CHECK_INDIRECT_AND_DO_SCOM");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INDIRECT_WRITE_TIMEOUT");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Indirect Scom Status Register");
        break;

    case 0x30301:
        i_parser.PrintString("devdesc", "Scom Translate not supported for this type");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_TRANS_INVALID_TYPE");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Target Type that failed");
        break;

    case 0x30101:
        i_parser.PrintString("devdesc", "Invalid address for that unit");
        i_parser.PrintString("moduleid", "SCOM::SCOM_TRANSLATE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_ADDR");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Unit type that failed");
        break;

    case 0x30102:
        i_parser.PrintString("devdesc", "Invalid Address for the mask passed in.");
        i_parser.PrintString("moduleid", "SCOM::SCOM_PERFORM_TRANSLATE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_INVALID_ADDR");
        i_parser.PrintString("userdata1", "Address");
        i_parser.PrintString("userdata2", "Unit type that failed");
        break;

    case 0x30202:
        i_parser.PrintString("devdesc", "Did not find parent type requested");
        i_parser.PrintString("moduleid", "SCOM::SCOM_PERFORM_TRANSLATE");
        i_parser.PrintString("reasoncode", "SCOM::SCOM_NO_MATCHING_PARENT");
        i_parser.PrintString("userdata1", "Parent type requested");
        i_parser.PrintString("userdata2", "Unit type that failed");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x300, SrcDataParse, ERRL_CID_HOSTBOOT);
