/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x230200:
        i_parser.PrintString("devdesc", "Invalid GPIO device type");
        i_parser.PrintString("moduleid", "GPIO_PERFORM_OP");
        i_parser.PrintString("reasoncode", "GPIO_I2C_TARGET_NOT_FOUND");
        i_parser.PrintString("userdata1", "Device type");
        i_parser.PrintString("userdata2", "HUID of target");
        break;

    case 0x230300:
        i_parser.PrintString("devdesc", "Invalid GPIO device type");
        i_parser.PrintString("moduleid", "GPIO_PERFORM_OP");
        i_parser.PrintString("reasoncode", "GPIO_INVALID_OP");
        i_parser.PrintString("userdata1", "OP type");
        i_parser.PrintString("userdata2", "HUID of target");
        break;

    case 0x230003:
        i_parser.PrintString("devdesc", "Invalid GPIO device type");
        i_parser.PrintString("moduleid", "GPIO_READATTRIBUTES");
        i_parser.PrintString("reasoncode", "GPIO_INVALID_DEVICE_TYPE");
        i_parser.PrintString("userdata1", "Device type");
        i_parser.PrintString("userdata2", "HUID of target");
        break;

    case 0x230103:
        i_parser.PrintString("devdesc", "GPIO device attribute was not found");
        i_parser.PrintString("moduleid", "GPIO_READATTRIBUTES");
        i_parser.PrintString("reasoncode", "GPIO_ATTR_INFO_NOT_FOUND");
        i_parser.PrintString("userdata1", "HUID of target");
        i_parser.PrintString("userdata2", "GPIO device type");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2300, SrcDataParse, ERRL_CID_HOSTBOOT);
