/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x160406:
        i_parser.PrintString("devdesc", "Unable to load LID via host interface.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_RT");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_RC_FAIL");
        i_parser.PrintString("userdata1", "Return code from lid_load call.");
        i_parser.PrintString("userdata2", "Lid number");
        break;

    case 0x160A06:
        i_parser.PrintString("devdesc", "Unable to find Lid.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_RT");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_NOT_FOUND");
        i_parser.PrintString("userdata1", "Lid number");
        break;

    case 0x160906:
        i_parser.PrintString("devdesc", "Unable to unload LID via host interface.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_RT");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_UNLOAD_RC_FAIL");
        i_parser.PrintString("userdata1", "Return code from lid_unload call.");
        break;

    case 0x160404:
        i_parser.PrintString("devdesc", "The LID transfer code on the FSP side was unable to fulfill the LID GET_INFO request.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLIDSIZE");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_RC_FAIL");
        i_parser.PrintString("userdata1", "return code from FSP");
        i_parser.PrintString("userdata2", "LID ID");
        break;

    case 0x160805:
        i_parser.PrintString("devdesc", "Insufficient space provided for LID by calling function.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLIDPNOR");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_INVAL_SIZE_PNOR");
        i_parser.PrintString("userdata1[0:31]", "LID size found in pnor");
        i_parser.PrintString("userdata1[32:63]", "Reserved space provided");
        i_parser.PrintString("userdata2", "LID ID");
        break;

    case 0x160605:
        i_parser.PrintString("devdesc", "Insufficient space provided for LID by calling function.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLIDPNOR");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_INVAL_SIZE");
        i_parser.PrintString("userdata1[0:31]", "LID size found in Ext Img");
        i_parser.PrintString("userdata1[32:63]", "Reserved space provided");
        i_parser.PrintString("userdata2", "LID ID");
        break;

    case 0x160403:
        i_parser.PrintString("devdesc", "The LID transfer code on the FSP side was unable to fulfill the LID SEND_TO_HB request.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLID");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_RC_FAIL");
        i_parser.PrintString("userdata1", "return code from FSP");
        i_parser.PrintString("userdata2", "LID ID");
        break;

    case 0x160503:
        i_parser.PrintString("devdesc", "DMA message contains data for wrong LID.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLID");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_INVAL_DATA");
        i_parser.PrintString("userdata1[0:31]", "received LID ID");
        i_parser.PrintString("userdata1[32:63]", "expected LID ID");
        i_parser.PrintString("userdata2[0:31]", "pointer to extra data");
        break;

    case 0x160603:
        i_parser.PrintString("devdesc", "Insufficient space provided for LID by calling function.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLID");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_INVAL_SIZE");
        i_parser.PrintString("userdata1[0:31]", "Allocated Size");
        i_parser.PrintString("userdata1[32:63]", "Size needed for current data page");
        i_parser.PrintString("userdata2[32:63]", "Lid ID");
        break;

    case 0x160703:
        i_parser.PrintString("devdesc", "Invalid Message type received from FSP when transferring LID pages.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_GETLID");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_UNSUP_MSG");
        i_parser.PrintString("userdata1", "LID ID");
        i_parser.PrintString("userdata2", "Message Type");
        break;

    case 0x160B07:
        i_parser.PrintString("devdesc", "Error returned from mm_remove_pages when evicting lid from memory.");
        i_parser.PrintString("moduleid", "Util::UTIL_LIDMGR_CLEANUP");
        i_parser.PrintString("reasoncode", "Util::UTIL_LIDMGR_MM_FAIL");
        i_parser.PrintString("userdata1[00:31]", "LID ID");
        i_parser.PrintString("userdata1[32:63]", "rc from mm_remove_pages");
        i_parser.PrintString("userdata2", "Virtual address being removed");
        break;

    case 0x160201:
        i_parser.PrintString("devdesc", "Bad memory pointer received.");
        i_parser.PrintString("moduleid", "Util::UTIL_MOD_MEM_READ");
        i_parser.PrintString("reasoncode", "Util::UTIL_ERC_BAD_PTR");
        i_parser.PrintString("userdata1[0:31]", "Task ID.");
        i_parser.PrintString("userdata1[31:64]", "End of File (boolean)");
        i_parser.PrintString("userdata2", "Address of memory buffer.");
        break;

    case 0x160301:
        i_parser.PrintString("devdesc", "End of file reached.");
        i_parser.PrintString("moduleid", "Util::UTIL_MOD_MEM_READ");
        i_parser.PrintString("reasoncode", "Util::UTIL_ERC_EOF");
        i_parser.PrintString("userdata1[0:31]", "Task ID.");
        i_parser.PrintString("userdata1[31:64]", "End of File (boolean)");
        i_parser.PrintString("userdata2", "Address of memory buffer.");
        break;

    case 0x160202:
        i_parser.PrintString("devdesc", "Bad memory pointer received.");
        i_parser.PrintString("moduleid", "Util::UTIL_MOD_MEM_WRITE");
        i_parser.PrintString("reasoncode", "Util::UTIL_ERC_BAD_PTR");
        i_parser.PrintString("userdata1[0:31]", "Task ID.");
        i_parser.PrintString("userdata1[31:64]", "End of File (boolean)");
        i_parser.PrintString("userdata2", "Address of memory buffer.");
        break;

    case 0x160302:
        i_parser.PrintString("devdesc", "End of file reached.");
        i_parser.PrintString("moduleid", "Util::UTIL_MOD_MEM_WRITE");
        i_parser.PrintString("reasoncode", "Util::UTIL_ERC_EOF");
        i_parser.PrintString("userdata1[0:31]", "Task ID.");
        i_parser.PrintString("userdata1[31:64]", "End of File (boolean)");
        i_parser.PrintString("userdata2", "Address of memory buffer.");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1600, SrcDataParse, ERRL_CID_HOSTBOOT);
