/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x210201:
        i_parser.PrintString("devdesc", "Error retrieving attribute");
        i_parser.PrintString("moduleid", "DEVTREE::MOD_DEVTREE_BLD_MEM");
        i_parser.PrintString("reasoncode", "DEVTREE::RC_ATTR_MEMBASE_GET_FAIL");
        i_parser.PrintString("userdata1", "Return code from ATTR_GET");
        i_parser.PrintString("userdata2", "Attribute Id that failed");
        break;

    case 0x210101:
        i_parser.PrintString("devdesc", "Error retrieving attribute");
        i_parser.PrintString("moduleid", "DEVTREE::MOD_DEVTREE_BLD_MEM");
        i_parser.PrintString("reasoncode", "DEVTREE::RC_ATTR_MEMSIZE_GET_FAIL");
        i_parser.PrintString("userdata1", "Return code from ATTR_GET");
        i_parser.PrintString("userdata2", "Attribute Id that failed");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x2100, SrcDataParse, ERRL_CID_HOSTBOOT);
