/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x80602:
        i_parser.PrintString("devdesc", "Module is not a data module");
        i_parser.PrintString("moduleid", "VFS_RT_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_INVALID_DATA_MODULE");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x80502:
        i_parser.PrintString("devdesc", "Module does not exist");
        i_parser.PrintString("moduleid", "VFS_RT_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_MODULE_DOES_NOT_EXIST");
        i_parser.PrintString("userdata1", "0");
        i_parser.PrintString("userdata2", "0");
        break;

    case 0x80301:
        i_parser.PrintString("devdesc", "Could not allocate virtual memory.");
        i_parser.PrintString("moduleid", "VFS_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_ALLOC_VMEM_FAILED");
        i_parser.PrintString("userdata1", "returncode from mm_alloc_block()");
        i_parser.PrintString("userdata2", "Size of memory to allocate");
        break;

    case 0x80703:
        i_parser.PrintString("devdesc", "VFS RP Task crashed.");
        i_parser.PrintString("moduleid", "VFS_WATCHER");
        i_parser.PrintString("reasoncode", "VFS_TASK_CRASHED");
        i_parser.PrintString("userdata1", "tidRc");
        i_parser.PrintString("userdata2", "task Rc");
        break;

    case 0x80704:
        i_parser.PrintString("devdesc", "VFS Task crashed.");
        i_parser.PrintString("moduleid", "VFS_MODULE_LOAD_MONITOR");
        i_parser.PrintString("reasoncode", "VFS_TASK_CRASHED");
        i_parser.PrintString("userdata1", "tidRc");
        i_parser.PrintString("userdata2", "Task Status");
        break;

    case 0x80401:
        i_parser.PrintString("devdesc", "Could not set permissions on virtual memory.");
        i_parser.PrintString("moduleid", "VFS_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_PERMS_VMEM_FAILED");
        i_parser.PrintString("userdata1", "returncode from mm_set_permission()");
        i_parser.PrintString("userdata2", "message type (LOAD or UNLOAD)");
        break;

    case 0x80501:
        i_parser.PrintString("devdesc", "Requested module does not exist.");
        i_parser.PrintString("moduleid", "VFS_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_MODULE_DOES_NOT_EXIST");
        i_parser.PrintString("userdata1", "first 8 bytes of module name");
        i_parser.PrintString("userdata2", "next 8 bytes of module name");
        break;

    case 0x80705:
        i_parser.PrintString("devdesc", "VFS Task crashed.");
        i_parser.PrintString("moduleid", "VFS_MODULE_EXEC_MONITOR");
        i_parser.PrintString("reasoncode", "VFS_TASK_CRASHED");
        i_parser.PrintString("userdata1", "tidRc");
        i_parser.PrintString("userdata2", "task Rc");
        break;

    case 0x80101:
        i_parser.PrintString("devdesc", "Could not load/unload module.");
        i_parser.PrintString("moduleid", "VFS_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_LOAD_FAILED");
        i_parser.PrintString("userdata1", "returncode from msg_sendrecv()");
        i_parser.PrintString("userdata2", "VfsMessages type [LOAD | UNLOAD]");
        break;

    case 0x80601:
        i_parser.PrintString("devdesc", "Module is not a data module");
        i_parser.PrintString("moduleid", "VFS_MODULE_ID");
        i_parser.PrintString("reasoncode", "VFS_INVALID_DATA_MODULE");
        i_parser.PrintString("userdata1", "First 8 bytes of module name");
        i_parser.PrintString("userdata2", "Next 8 bytes of module name");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x800, SrcDataParse, ERRL_CID_HOSTBOOT);
