/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x1B0200:
        i_parser.PrintString("devdesc", "Kernel encountered an unhandled exception.");
        i_parser.PrintString("moduleid", "KERNEL::MOD_KERNEL_INVALID");
        i_parser.PrintString("reasoncode", "KERNEL::RC_SHUTDOWN");
        i_parser.PrintString("userdata1", "Failing address");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x1B0300:
        i_parser.PrintString("devdesc", "Kernel encountered an unhandled exception.");
        i_parser.PrintString("moduleid", "KERNEL::MOD_KERNEL_INVALID");
        i_parser.PrintString("reasoncode", "KERNEL::RC_UNHANDLED_EX");
        i_parser.PrintString("userdata1", "Exception type");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    case 0x1B0100:
        i_parser.PrintString("devdesc", "Kernel has asserted");
        i_parser.PrintString("moduleid", "KERNEL::MOD_KERNEL_INVALID");
        i_parser.PrintString("reasoncode", "KERNEL::RC_ASSERT");
        i_parser.PrintString("userdata1", "Failing address");
        i_parser.PrintString("userdata2", "<unused>");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1B00, SrcDataParse, ERRL_CID_HOSTBOOT);
