/*
 * Automatically generated by Hostboot's ./genErrlParsers.pl
 * Do not modify this file in the FSP tree, it is provided by
 * Hostboot and will be overwritten
 *
 * TimeStamp:   Thu Apr 12 08:28:51 2018
 * Image Id:    hb0412a_1815.861
 *
 */

#include <errlplugins.H>
#include <errlusrparser.H>
#include <srcisrc.H>

static bool SrcDataParse(ErrlUsrParser & i_parser,
                         const SrciSrc & i_src)
{
    uint32_t l_error = (i_src.reasonCode() << 8) + i_src.moduleId();
    bool l_success = true;

    switch(l_error)
    {
    case 0x180101:
        i_parser.PrintString("devdesc", "ATTN test case failed");
        i_parser.PrintString("moduleid", "ATTN_TEST_FAKE_CALL_PRD");
        i_parser.PrintString("reasoncode", "ATTN_TEST_ATTN_FAIL");
        i_parser.PrintString("userdata1", "Input attention list size");
        i_parser.PrintString("userdata2", "Expected attention list size");
        break;

    default:
        l_success = false;
        break;
    };
    return l_success;
}

static errl::SrcPlugin g_SrcPlugin(0x1800, SrcDataParse, ERRL_CID_HOSTBOOT);
