#!/bin/bash

# Automatically generated by Hostboot's ./genErrlParsers.pl
# Do not modify this file in the FSP tree, it is provided by
# Hostboot and will be overwritten
#
#-------------------------------------------------------------
# SRC Parsers
#-------------------------------------------------------------

rm *.o
rm *.a

g++ -g -std=c++0x -I. -I../ -I../../include -I../../include/util  -D_X86NFP -DPARSER -c *.C

ar rvs libfspplugins.a *.o

