#include <prdrErrlPluginsSupt.H>
PRDR_ERROR_SIGNATURE_TABLE_START ( 0x21, 0x9000 )
	PRDR_ERROR_SIGNATURE ( 0x98f00000, "N/A", "N/A" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0000, "CXAFIR[0]", "CXA Informational PE" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0001, "CXAFIR[1]", "CXA System Xstop PE" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0002, "CXAFIR[2]", "CXA CE on Master array." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0003, "CXAFIR[3]", "CXA UE on Master array." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0004, "CXAFIR[4]", "CXA Timer expired recoverable error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0005, "CXAFIR[5]", "Recovery sequencer hang detection" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0006, "CXAFIR[6]", "XPT saw UE on PB data" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0007, "CXAFIR[7]", "XPT saw SUE on PB data" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0008, "CXAFIR[8]", "Correctable error on Snooper array." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0009, "CXAFIR[9]", "Uncorrectable error on Snooper array." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c000a, "CXAFIR[10]", "RECOVERY_FAILED: CAPP recovery failed" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c000b, "CXAFIR[11]", "Illegal LPC BAR access" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c000c, "CXAFIR[12]", "XPT recoverable error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c000d, "CXAFIR[13]", "Recoverable errors detected in Master" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c000e, "CXAFIR[14]", "spare" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c000f, "CXAFIR[15]", "Scom satellite parity error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0010, "CXAFIR[16]", "CXA System checkstop errors in master" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0011, "CXAFIR[17]", "CXA System checkstop errors in Snooper" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0012, "CXAFIR[18]", "CXA  transport System checkstop errors" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0013, "CXAFIR[19]", "CXA Master uOP FIR 1 for lab use" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0014, "CXAFIR[20]", "CXA Master uOP FIR 2 for lab use" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0015, "CXAFIR[21]", "CXA Master uOP FIR 3 for lab use" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0016, "CXAFIR[22]", "Snooper uOP FIR 1 for lab use" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0017, "CXAFIR[23]", "Snooper uOP FIR 2 for lab use" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0018, "CXAFIR[24]", "Snooper uOP FIR 3 for lab use" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0019, "CXAFIR[25]", "Misc informational PowerBus error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c001a, "CXAFIR[26]", "CXA Parity error on PowerBus interface" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c001b, "CXAFIR[27]", "CXA: Any PowerBus data hang poll error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c001c, "CXAFIR[28]", "CXA: PowerBus command hang error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c001d, "CXAFIR[29]", "CXA: PB Addr Error detected by APC : ld" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c001e, "CXAFIR[30]", "CXA PB Addr Err detected by APC : st" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c001f, "CXAFIR[31]", "CXA: PPHB0 or PHB1 i linkdown" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0020, "CXAFIR[32]", "APC ack_dead or ack_ed_dead" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0021, "CXAFIR[33]", "CXA Any PowerBus command hang error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0022, "CXAFIR[34]", "CXA CE on data received from PB" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0023, "CXAFIR[35]", "CXA: UE on data received from PowerBus" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0024, "CXAFIR[36]", "CXA: SUE on data received from PowerBus" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0025, "CXAFIR[37]", "CXA: TLBI Timeout error." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0026, "CXAFIR[38]", "CXA: TLBI seq_err." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0027, "CXAFIR[39]", "CXA: TLBI bad op error." )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0028, "CXAFIR[40]", "CXA: PE on TLBI sequence number" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0029, "CXAFIR[41]", "APC received ack_dead or ack_ed_dead" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c002a, "CXAFIR[42]", "TimeBase error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c002b, "CXAFIR[43]", "XPT Informational Error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c002c, "CXAFIR[44]", "Command_queue_CE" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c002d, "CXAFIR[45]", "Command_queue_UE" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c002e, "CXAFIR[46]", "PSL credit timeout error" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c002f, "CXAFIR[47]", "spare" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0030, "CXAFIR[48]", "Hypervisor asserted" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0031, "CXAFIR[49]", "spare" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0032, "CXAFIR[50]", "SCOM err" )
	PRDR_ERROR_SIGNATURE ( 0xbd1c0033, "CXAFIR[51]", "SCOM err" )
//---- Extra Signatures ----
PRDR_ERROR_SIGNATURE_TABLE_END
